from cfgy2 import *
import cfgy2, builder, bisect
SQ = hashlib.sha256(open(OUT+'h41/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y41.json'))
setup(QID="A02441", SRC="16Mk5yx4eWixoWgInVQrBZke6Q1Vzv929", SHA=SQ, TAG="YMJH05", N=89, SUBJ="수학(하)", SEC="S05A",
      FNAME="05 함수(지학사) 91제.hwp", UNIT="Ⅴ. 함수", BIG="Ⅴ. 함수", EXAM="5. 함수 91제", MID="함수")
cfgy2.P.update(BOOK="지학사 수학(하)", GRADE="고1", MEMO_X="파일명 91제·빠른 정답 91개는 개념정리 빈칸 문항 2개(30번 ⑨⑩, 67번 ①②)를 별도 항목으로 분리한 것 — 본문 문항 89개, 이를 병합하면 정렬 일치; ")
B = [1, 15, 21, 28, 41, 54, 67, 77]
MIDS = ["함수의 뜻과 그래프", "합성함수", "역함수", "함수(중단원 마무리)", "유리함수", "무리함수", "유리함수와 무리함수(중단원 마무리)", "함수와 그래프 종합(대단원 마무리)"]
SECS = [f"S05{chr(65+j)}" for j in range(len(B))]
for s, mid in zip(SECS, MIDS): builder.SECTIONS[s] = ("5. 함수 91제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, DRW, MC = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "서술형(그래프 그리기)", "객관식(5지선다)"
F1, F2, F3, R1, R2 = "함수", "합성함수", "역함수", "유리함수", "무리함수"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = SECS[bisect.bisect_right(B, q) - 1]
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·그래프 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건·보기(수식/표 객체) 본문 미추출 — 파일 정답 기준")
OP = dict(review="REVIEW-개방형", chk="개방형·발표/토론 활동 — 정답 풀이참조")
r(1, F1, "FUNC.DEFINITION.CONTEXT", "y가 x의 함수인지(준비)", "함수의 뜻", "하", S, "(1) 함수 (2) 함수", "판정", 2)
r(2, F1, "FUNC.LINEAR.IDENTIFY", "일차함수 찾기(준비)", "일차함수", "하", S, "(1), (3)", "번호")
r(3, F1, "FUNC.QUADRATIC.GRAPH", "이차함수 그래프 그리기(준비)", "이차함수의 그래프", "하", DRW, "꼭짓점 (1, −1), 원점·(2, 0) 지나는 포물선", "그래프", fig="그래프", final="(빠른 정답 공란)")
r(4, F1, "FUNC.CORRESPONDENCE.POEMS", "시 제목-시인 대응(탐구)", "함수의 뜻;대응", "하", ACT, "풀이참조", "서술", 2, fig="표", final="풀이참조", **FK)
r(5, F1, "FUNC.DOMAIN_CODOMAIN_RANGE.DIAGRAM", "대응 그림에서 함수와 정의역·공역·치역", "함수의 뜻;정의역;치역", "하", S, "(1) 정의역 {1,2,3}, 공역 {a,b,c,d}, 치역 {b,c}", "집합", fig="그림", **FK)
r(6, F1, "FUNC.DOMAIN_CODOMAIN_RANGE.FORMULA", "식으로 주어진 함수 정의역·공역·치역(예제)", "정의역;공역;치역", "하", S, "정의역 {1,2,3}, 공역 {−1,0,1,2,3}, 치역 {−1,1,3}", "집합")
r(7, F1, "FUNC.DOMAIN_RANGE.REAL", "일차·이차함수 정의역·치역", "정의역;치역", "하", S, "(1) 정의역·치역 실수 전체 (2) 정의역 실수 전체, 치역 {y|y≥−1}", "집합", 2)
r(8, F1, "FUNC.EQUALITY.FIND_PARAMS", "두 함수가 같을 조건", "서로 같은 함수", "하", S, "a=3, b=−2", chk="독립풀이 일치(a+b=1, 2a+b=4)")
r(9, F1, "FUNC.GRAPH.ORDERED_PAIRS", "함수의 그래프(순서쌍) 나타내기(탐구)", "함수의 그래프", "하", ACT, "풀이참조", "집합+그래프", 2, fig="그림", final="풀이참조", **FK)
r(10, F1, "FUNC.GRAPH.VERTICAL_LINE_TEST", "함수의 그래프 판별", "함수의 그래프", "하", S, "(1), (3)", "번호", fig="그래프", **FK)
r(11, F1, "FUNC.BIJECTION.PROOF_LINEAR", "일차함수 일대일대응 증명(예제)", "일대일대응", "하", PRF, "x₁≠x₂ ⇒ f(x₁)−f(x₂)=2(x₁−x₂)≠0, 치역=공역 → 일대일대응", "증명", final="풀이참조")
r(12, F1, "FUNC.ONE_TO_ONE.IDENTIFY", "일대일함수 찾고 일대일대응 확인", "일대일함수;일대일대응", "하", D, "(1) f(x)=−x+2: 일대일함수이자 일대일대응 (2) |x|: 일대일함수 아님", "서술", 2, final="풀이참조", chk="독립풀이 = 해설 결과 일치(빠른 정답 '풀이 참조')")
r(13, F1, "FUNC.IDENTITY_CONSTANT.GRAPH", "항등함수·상수함수 그래프 찾기", "항등함수;상수함수", "하", S, "항등함수 (1), 상수함수 (3)", "번호", fig="그래프", **FK)
r(14, F1, "FUNC.BIJECTION.LINEAR_INTERVAL", "구간에서 일대일함수·일대일대응 조건(탐구)", "일대일함수;일대일대응", "중하", ACT, "(1) 1≤b≤2 (2) a=2, b=1 또는 a=−2, b=3", "부등식+값", 2, c=M, i=M, trap="a<0이면 끝점 대응 반대")
r(15, F2, "COMPOSITE.CORRESPONDENCE.ACTIVITY", "작품-작가-국가 대응 합성(탐구)", "합성함수", "하", ACT, "풀이참조", "서술", 2, fig="그림", final="풀이참조", **OP)
r(16, F2, "COMPOSITE.VALUE.LINEAR", "합성함수의 함숫값", "합성함수", "하", S, "(1) 1 (2) 7 (3) 3", "값(소문항별)", 3)
r(17, F2, "COMPOSITE.FORMULA.QUADRATIC", "합성함수 식(예제)", "합성함수", "하", S, "(1) (g∘f)(x)=2x²+3 (2) (f∘g)(x)=4x²+4x+2", "식(소문항별)", 2, trap="f∘g≠g∘f")
r(18, F2, "COMPOSITE.FORMULA.LINEAR", "합성함수 식", "합성함수", "하", S, "(1) (g∘f)(x)=6x+3 (2) (f∘g)(x)=6x+1", "식(소문항별)", 2)
r(19, F2, "COMPOSITE.COMMUTE.FIND_PARAM", "f∘g=g∘f 되는 a", "합성함수", "하", S, "−2", chk="독립풀이 일치(2a−1=a−3)")
r(20, F2, "COMPOSITE.CONTEXT.DISCOUNT", "할인 함수 합성 비교(서술)", "합성함수", "중하", D, "(f∘g)(x)=0.9x−900 > (g∘f)(x)=0.9x−1000 → g∘f의 할인 폭이 더 큼", "서술", final="풀이참조(해설: g∘f가 할인 가격이 더 크다)", i=M, review="REVIEW-개방형", chk="독립풀이 = 해설 일치(해설은 '할인 가격'을 할인액 의미로 사용 — 표현 모호)")
r(21, F3, "INVERSE.CORRESPONDENCE.LADDER", "사다리 타기 대응과 역대응(탐구)", "역함수;일대일대응", "하", ACT, "풀이참조", "서술", 2, fig="그림", final="풀이참조", **FK)
r(22, F3, "INVERSE.VALUE.BASIC", "역함수 값과 f∘f⁻¹", "역함수", "하", S, "(1) 3 (2) 3", "값(소문항별)", 2)
r(23, F3, "INVERSE.FORMULA.LINEAR", "일차함수 역함수(예제)", "역함수", "하", S, "y=3x+6", "식")
r(24, F3, "INVERSE.FORMULA.LINEAR", "일차함수 역함수", "역함수", "하", S, "(1) y=x−6 (2) y=−2x+10", "식(소문항별)", 2)
r(25, F3, "INVERSE.COMPOSITE_PROPERTY.VERIFY", "(g∘f)⁻¹=f⁻¹∘g⁻¹ 확인", "역함수;합성함수", "중하", PRF, "(g∘f)(x)=−2x+2의 역함수 −x/2+1 = f⁻¹(g⁻¹(x)) 확인", "증명", final="풀이참조", i=M)
r(26, F3, "INVERSE.GRAPH.SYMMETRY", "역함수 그래프 그리기", "역함수의 그래프", "하", DRW, "y=x 대칭: (1) y=2x+2 (2) y=−x+1", "그래프", 2, fig="그래프", final="(빠른 정답 공란)")
r(27, F3, "INVERSE.GRAPH.PIECEWISE", "구간별 함수의 역함수 그래프", "역함수의 그래프", "중하", DRW, "y=x 대칭 그래프: y=2x (0≤x<1), y=(x+3)/2 (1≤x≤3)", "그래프", fig="그래프", final="(빠른 정답 공란)", i=M)
r(28, F1, "CONCEPT.SUMMARY.FUNCTION_TERMS", "개념 정리 빈칸: 정의역·공역·치역", "함수의 뜻", "하", S, "① 정의역 ② 공역 ③ 치역", "용어")
r(29, F1, "CONCEPT.SUMMARY.FUNCTION_TYPES", "개념 정리 빈칸: 함수의 종류", "일대일함수;일대일대응;항등함수;상수함수", "하", S, "④ f(x₁)≠f(x₂) ⑤ 일대일대응 ⑥ 항등함수 ⑦ 상수함수", "용어")
r(30, F2, "CONCEPT.SUMMARY.COMPOSITE_INVERSE", "개념 정리 빈칸: 합성함수·역함수", "합성함수;역함수", "하", S, "⑧ 합성함수 ⑨ 역함수 ⑩ y=x", "용어", final="⑧ 합성함수 (빠른 정답 별도 항목: ⑨ 역함수 ⑩ y=x)")
r(31, F1, "FUNC.DEFINITION.CHOICES_INTEGER_SETS", "정수 집합 사이 함수 고르기", "함수의 뜻", "하", S, "ㄴ, ㄷ, ㄹ", "보기", chk="보기는 해설에서 확인(ㄱ y=x, ㄴ y=x+1, ㄷ y=x², ㄹ y=|x|+1): ㄱ은 −1↦−1∉Y — 독립풀이 일치")
r(32, F1, "FUNC.TYPES.GRAPH_IDENTIFY", "그래프로 일대일대응·항등·상수함수 찾기", "일대일대응;항등함수;상수함수", "하", S, "풀이참조", "번호", fig="그래프", final="풀이참조", **FK)
r(33, F2, "COMPOSITE.VALUE.PIECEWISE", "구간별 함수 합성값", "합성함수", "하", S, "(1) −17 (2) 3", "값(소문항별)", 2, chk="독립풀이 일치(g(3)=8→f(8)=−17, f(1)=2→g(2)=3)")
r(34, F3, "INVERSE.VALUE.FIND_PARAM", "f⁻¹(1)=2인 a", "역함수", "하", S, "a=−1", trap="f⁻¹(1)=2 ⇔ f(2)=1")
r(35, F1, "FUNC.EQUALITY.ABS", "|x| 포함 두 함수가 같을 조건", "서로 같은 함수", "하", S, "a=2, b=−5")
r(36, F2, "COMPOSITE.FORMULA.LINEAR", "합성함수 식", "합성함수", "하", S, "(1) (g∘f)(x)=6x−4 (2) (f∘g)(x)=6x+7", "식(소문항별)", 2, final="(1) 6x−4 (2) 6x+7", chk="독립풀이 = 해설 결과 일치(빠른 정답 '풀이 참조')")
r(37, F2, "COMPOSITE.COMMUTE.FIXED_POINT", "f∘g=g∘f일 때 g가 지나는 정점", "합성함수;정점", "중", S, "(2/3, 2/3)", "좌표", c=M, i=M, chk="독립풀이 일치(b=(2−2a)/3 → g(x)=a(x−2/3)+2/3)")
r(38, F2, "COMPOSITE.FIND_INNER_VALUE", "f∘h=g일 때 h(3)", "합성함수", "하", S, "0")
r(39, F3, "INVERSE.GRAPH.READ_VALUES", "그래프와 y=x로 합성·역함수 값", "역함수;합성함수", "중하", S, "(1) c (2) b", "문자(소문항별)", 2, fig="그래프", **FK)
r(40, F3, "INVERSE.CONTEXT.CAESAR_CIPHER", "카이사르 암호와 역함수(활동)", "역함수", "하", ACT, "풀이참조", "서술", fig="그림", final="풀이참조", **OP)
r(41, R1, "FRACTION.ARITHMETIC.LINEAR_TERMS", "분수 계수 식 정리(준비)", "분수식", "하", S, "(1) 5x/6 (2) 7x/12", "식(소문항별)", 2)
r(42, R1, "INVERSE_PROPORTION.IDENTIFY", "반비례 관계 찾기(준비)", "반비례", "하", S, "(2), (3)", "번호")
r(43, R1, "TRANSLATION.LINE_PARABOLA", "도형의 평행이동(준비)", "도형의 평행이동", "하", S, "(1) y=2x−5 (2) y=x²−4x+3", "식(소문항별)", 2)
r(44, R1, "INVERSE_PROPORTION.CONTEXT.BOYLE", "보일 법칙과 반비례 그래프(탐구)", "반비례;유리함수", "하", ACT, "풀이참조", "서술", fig="그래프", final="풀이참조", **OP)
r(45, R1, "RATIONAL_EXPR.ARITHMETIC", "유리식의 사칙계산", "유리식", "중하", S, "(1) (2x+3)/(x+1) (2) 2/(x²−2x) (3) 1/(x−2) (4) (x−3)/(x²+x)", "식(소문항별)", 4, c=M)
r(46, R1, "RATIONAL_FUNC.DOMAIN", "유리함수 정의역", "유리함수", "하", S, "(1) {x|x≠−1/2} (2) {x|x≠2}", "집합", 2)
r(47, R1, "RATIONAL_FUNC.GRAPH.BASIC", "y=k/x 그래프", "유리함수의 그래프", "하", DRW, "풀이참조(k>0: 1·3사분면, k<0: 2·4사분면)", "그래프", 4, fig="그래프", final="풀이참조")
r(48, R1, "RATIONAL_FUNC.GRAPH.ASYMPTOTES", "평행이동 꼴 그래프·점근선(예제)", "유리함수의 그래프;점근선", "하", DRW, "점근선 x=1, y=2", "그래프+식", fig="그래프")
r(49, R1, "RATIONAL_FUNC.GRAPH.ASYMPTOTES", "평행이동 꼴 그래프·점근선", "유리함수의 그래프;점근선", "하", DRW, "(1) x=−1, y=−2 (2) x=2, y=0", "그래프+식(소문항별)", 2, fig="그래프", final="풀이참조(해설: (1) x=−1, y=−2 (2) x=2, y=0)")
r(50, R1, "RATIONAL_FUNC.GRAPH.STANDARD_FORM", "(−x−3)/(x+1) 그래프·점근선(예제)", "유리함수의 그래프;점근선", "하", DRW, "y=−2/(x+1)−1; 점근선 x=−1, y=−1", "그래프+식", fig="그래프")
r(51, R1, "RATIONAL_FUNC.GRAPH.STANDARD_FORM", "표준형 변형 그래프·점근선", "유리함수의 그래프;점근선", "중하", DRW, "(1) x=−1, y=2 (2) x=1/2, y=−1/2", "그래프+식(소문항별)", 2, fig="그래프", c=M, final="풀이참조(해설: (1) x=−1, y=2 (2) x=1/2, y=−1/2)")
r(52, R1, "RATIONAL_FUNC.CONTEXT.TRAPEZOID", "넓이 일정 사다리꼴 높이 함수(탐구)", "유리함수", "중하", ACT, "(1) f(x)=6/(x+2) (3) 1≤x≤4에서 1≤y≤2", "식+범위", 3, fig="그림", **FK)
r(53, R1, "RATIONAL_FUNC.PARAMETER.SOFTWARE", "k, p, q 변화와 그래프(탐구)", "유리함수의 그래프", "하", ACT, "풀이참조", "서술", fig="그래프", final="풀이참조", **OP)
r(54, R2, "IRRATIONAL_FUNC.CONTEXT.SQUARE_SIDE", "정사각형 넓이와 한 변(탐구)", "무리함수", "하", ACT, "y=√x (풀이참조)", "식+그래프", 3, fig="그래프", final="풀이참조", **OP)
r(55, R2, "IRRATIONAL_EXPR.RATIONALIZE", "무리식 간단히", "무리식;분모의 유리화", "중하", S, "(1) 4√x/(x−1) (2) 0", "식(소문항별)", 2, c=M)
r(56, R2, "IRRATIONAL_FUNC.DOMAIN", "무리함수 정의역", "무리함수", "하", S, "(1) {x|x≤1/2} (2) {x|x≥−1}", "집합", 2)
r(57, R2, "IRRATIONAL_FUNC.GRAPH.BASIC", "y=√(−x) 그래프(예제)", "무리함수의 그래프", "하", DRW, "풀이참조(y=√x의 y축 대칭)", "그래프", fig="그래프", final="풀이참조")
r(58, R2, "IRRATIONAL_FUNC.GRAPH.REFLECTION", "y=−√x, y=−√(−x) 그래프", "무리함수의 그래프", "하", DRW, "풀이참조(x축·원점 대칭)", "그래프", 2, fig="그래프", final="풀이참조")
r(59, R2, "IRRATIONAL_FUNC.GRAPH.BASIC", "y=√(2x) 그래프(예제)", "무리함수의 그래프", "하", DRW, "풀이참조", "그래프", fig="그래프", final="풀이참조")
r(60, R2, "IRRATIONAL_FUNC.GRAPH.REFLECTION", "y=±√(±2x) 그래프", "무리함수의 그래프", "하", DRW, "풀이참조", "그래프", 3, fig="그래프", final="풀이참조")
r(61, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "평행이동 무리함수 그래프·정의역·치역", "무리함수의 그래프", "하", DRW, "(1) 정의역 {x|x≥−2}, 치역 {y|y≤4} (2) 정의역 {x|x≤−2}, 치역 {y|y≥1}", "그래프+집합", 2, fig="그래프", final="풀이참조(해설 결과 동일)")
r(62, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "√(2x−4)+1 그래프·정의역·치역(예제)", "무리함수의 그래프", "하", DRW, "정의역 {x|x≥2}, 치역 {y|y≥1}", "그래프+집합", fig="그래프", final="x=−1, y=−1 (원답지) — 독립풀이·해설: 정의역 {x|x≥2}, 치역 {y|y≥1}",
  ready="REVIEW", status="정답 불일치(빠른 정답 'x=−1, y=−1' vs 독립풀이·해설)", trust="중간(빠른 정답 오기 — 50번 점근선 답 복사로 보임)", review="REVIEW-정답충돌",
  conflict="빠른 정답 'x=−1, y=−1'은 50번 점근선 답과 동일한 복사 오류로 보임 — 동일 파일 해설은 정의역 {x|x≥2}, 치역 {y|y≥1}", chk="독립풀이 정의역 x≥2, 치역 y≥1(해설 일치); 원답지 유지·충돌 기록")
r(63, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "무리함수 그래프·정의역·치역", "무리함수의 그래프", "하", DRW, "(1) 정의역 {x|x≤−3}, 치역 {y|y≥0} (2) 정의역 {x|x≥1/3}, 치역 {y|y≤1}", "그래프+집합", 2, fig="그래프", final="풀이참조(해설 결과 동일)")
r(64, R2, "IRRATIONAL_FUNC.CONTEXT.WIND_CHILL", "체감온도 무리함수 식·그래프", "무리함수", "하", DRW, "y=−4√x+3 (x≥0)", "식+그래프", fig="그래프", final="풀이참조")
r(65, R2, "IRRATIONAL_FUNC.CONGRUENT_BY_TRANSFORM", "이동으로 겹쳐지는 무리함수 a(탐구)", "무리함수의 그래프;평행이동;대칭이동", "중하", ACT, "a=4 또는 a=−4", c=M, chk="독립풀이 일치(√(4(x−5/4))+3, |a|=4)")
r(66, R2, "IRRATIONAL_FUNC.PARAMETER.SOFTWARE", "a, b, c 변화와 그래프(탐구)", "무리함수의 그래프", "하", ACT, "풀이참조", "서술", 3, fig="그래프", final="풀이참조", **OP)
r(67, R2, "CONCEPT.SUMMARY.RATIONAL_IRRATIONAL", "개념 정리 빈칸: 유리·무리함수", "유리함수;무리함수", "하", S, "① A/B ② 유리함수 ④ x=p ⑤ y=q ⑥ 근호 ⑦ ≥ ⑧ 무리함수 ⑨ ≥p ⑩ ≤p", "용어", final="⑥ 근호 ⑦ ≥ (빠른 정답 별도 항목: ① A/B ② 유리함수)", **CK)
r(68, R1, "RATIONAL_FUNC.DOMAIN_RANGE_ASYMPTOTE", "유리함수 그래프·정의역·치역·점근선", "유리함수의 그래프;점근선", "하", DRW, "(1) x≠−1, y≠2, 점근선 x=−1, y=2 (2) x≠−2, y≠−1, 점근선 x=−2, y=−1", "그래프+집합", 2, fig="그래프", final="풀이참조(해설 결과 동일)")
r(69, R1, "RATIONAL_FUNC.TRANSLATION.THROUGH_POINT", "평행이동 유리함수가 지나는 점", "유리함수의 그래프;평행이동", "하", S, "2/3")
r(70, R2, "IRRATIONAL_FUNC.DOMAIN_RANGE", "무리함수 그래프·정의역·치역", "무리함수의 그래프", "하", DRW, "(1) x≥−3, y≥−2 (2) x≤1, y≥−1", "그래프+집합", 2, fig="그래프", final="풀이참조(해설 결과 동일)")
r(71, R2, "IRRATIONAL_FUNC.TRANSLATION.FIND_PARAM", "평행이동 무리함수 지나는 점으로 a", "무리함수의 그래프;평행이동", "하", S, "3")
r(72, R1, "RATIONAL_FUNC.GRAPH.FIND_COEFFS", "그래프로 유리함수 계수", "유리함수의 그래프", "중하", S, "a=2, b=−1, c=−1", fig="그래프", **FK)
r(73, R1, "RATIONAL_FUNC.INEQUALITY.BOUNDS", "유리식 사이 부등식 항상 성립 a, b", "유리함수;부등식", "중", S, "a≤1, b≥3", "부등식", c=M, i=M, chk="독립풀이 일치(x>0으로 나눠 3/(x−1)∈[1,3])")
r(74, R1, "RATIONAL_FUNC.CONTEXT.CLEANUP_COST", "쓰레기 수거 비용 유리함수", "유리함수", "중하", S, "75 %", c=M, chk="독립풀이 일치(3k=kx/(100−x))")
r(75, R2, "IRRATIONAL_FUNC.GRAPH.FIND_COEFFS", "그래프로 무리함수 계수", "무리함수의 그래프", "중하", S, "a=−1, b=1, c=2", fig="그래프", **FK)
r(76, R2, "IRRATIONAL_FUNC.AREA.SYMMETRY", "두 무리함수 사이 넓이", "무리함수의 그래프;대칭", "중", S, "24", c=M, i=H, chk="독립풀이 일치(g(x)=f(−x)+6 → 넓이=6×4)")
r(77, F1, "FUNC.EQUALITY.DOMAIN_TWO_POINTS", "같은 함수 될 정의역 a+b(객관식)", "서로 같은 함수;근과 계수의 관계", "하", MC, "② (6)", "선택지", final="②")
r(78, F3, "INVERSE.COMPOSITE.CANCEL", "g∘f∘g 값(객관식)", "역함수;합성함수", "하", MC, "④ (4)", "선택지", final="④", trap="f∘g=항등")
r(79, F3, "INVERSE.FUNCTIONAL_EQUATION", "f(2x−1)=3x+3에서 f(3)+f⁻¹(3)(객관식)", "역함수", "중하", MC, "③ (8)", "선택지", final="③", c=M, chk="독립풀이 일치(f(3)=9, f⁻¹(3)=−1)")
r(80, R1, "RATIONAL_FUNC.MAX_MIN.INTERVAL", "구간 유리함수 최대·최소 합(객관식)", "유리함수", "하", MC, "⑤ (5/4)", "선택지", final="⑤")
r(81, R1, "RATIONAL_FUNC.PROPERTIES.CHOICE", "유리함수 성질 옳은 것(객관식)", "유리함수의 그래프", "하", MC, "④", "선택지", final="④", chk="독립풀이 일치(y=−2/(x+1)+2: 대칭점 (−1,2))")
r(82, R2, "IRRATIONAL_FUNC.PROPERTIES.CHOICE", "무리함수 성질 옳은 것(객관식)", "무리함수의 그래프", "하", MC, "⑤", "선택지", final="⑤", chk="독립풀이 일치(정의역 x≤2, 치역 y≥2, y절편 (0,4), 제1·2사분면)")
r(83, R2, "IRRATIONAL_FUNC.MEETS_SEGMENT.COUNT", "선분과 만나는 정수 k 개수(객관식)", "무리함수의 그래프", "중하", MC, "④ (13)", "선택지", final="④", c=M, chk="독립풀이 일치(3≤k≤15)")
r(84, F1, "FUNC.BIJECTION.PIECEWISE_PARAM", "구간별 함수 일대일대응 a 범위", "일대일대응", "중", S, "−2<a<2", "부등식", c=M, i=M, trap="두 구간 기울기 부호 같아야")
r(85, F2, "COMPOSITE.PIECEWISE.PARITY", "홀짝 구간별 함수 f∘f", "합성함수", "중하", S, "(f∘f)(x)=x", "식", review="REVIEW-조건미추출", chk="f 정의(홀수 x+1, 짝수 x−1)는 해설에서 확인 — 독립풀이 일치")
r(86, F3, "INVERSE.COMPOSITE_LINEAR_ARG", "f(3x−2)의 역함수를 g로(서술형)", "역함수;합성함수", "중", D, "y={g(x)+2}/3", "식", i=M)
r(87, F2, "COMPOSITE.VALUE.PIECEWISE_SUM", "구간별 함수 합성값의 합(서술형)", "합성함수", "하", D, "−5", final="−5", chk="독립풀이 = 해설 결과 일치(f(g(4))=−2, g(f(4))=−3; 빠른 정답 '풀이 참조')")
r(88, F3, "INVERSE.QUADRATIC_IRRATIONAL.COEFFS", "무리함수 역함수로 이차함수 계수(서술형)", "역함수;무리함수", "중하", D, "a=1, b=−2", final="a=1, b=−2", c=M, chk="독립풀이 = 해설 결과 일치(y=(x−1)²+1)")
r(89, R2, "IRRATIONAL_FUNC.SQUARE_BETWEEN_GRAPHS", "두 무리함수 사이 정사각형(서술형)", "무리함수의 그래프", "중", D, "a=4", final="4", fig="그래프", c=M, i=M, chk="독립풀이 = 해설 결과 일치(D(a,2√a), C(2a,2√a), 2√a=a)")
for i in range(9): build(f"Batch{547+i}", ROWS[i*10:(i+1)*10], 13850+i*10)
print(len(ROWS))
