from rows83h import *
NK = dict(review="REVIEW-그림판독", chk="조건/식/보기 본문 미추출(표·그림 객체) — 파일 정답 기준, 독립풀이 불가")
r(1, I1, "INTEGRAL.POLY.PREP", "다항함수 부정적분·정적분(준비)", "부정적분;정적분", "하", S, "(1) x³/3−2x+C (2) 1", "식·값", 2)
r(2, I1, "INTEGRAL.POWER.NEGATIVE_INTUITION", "x⁻¹ 미분으로 ∫x⁻²dx(생각 열기)", "부정적분;xⁿ의 부정적분", "하", ACT, "➊ y′=−x⁻² ➋ −x⁻¹+C", "식", 2)
r(3, I1, "INTEGRAL.POWER.REAL_EXPONENT", "실수 지수 xᵃ 부정적분", "xⁿ의 부정적분(n≠−1)", "하", S, "(1) −x⁻³/3+C (2) (2/5)x²√x+C (3) (√2−1)x^(√2+1)+C", "식(소문항별)", 3)
r(4, I1, "INTEGRAL.POWER.SPLIT_AND_1_OVER_X", "분수식 전개 후 부정적분(예제)", "xⁿ의 부정적분;1/x의 부정적분", "하", S, "(1) x²+1/x+C (2) x+8√x+4ln|x|+C", "식(소문항별)", 2)
r(5, I1, "INTEGRAL.POWER.SPLIT_AND_1_OVER_X", "분수식·무리식 정리 후 부정적분", "xⁿ의 부정적분;유리화", "하", S, "(1) (4x−1)/(2x²)+C (2) (2/3)x√x+x+C", "식(소문항별)", 2, trap="(x−1)/(√x−1)=√x+1")
r(6, I1, "DEFINT.POWER.SPLIT", "분수식·무리식 정적분", "정적분;1/x의 부정적분", "하", S, "(1) 1/2+ln4 (2) 24/5", "값(소문항별)", 2)
r(7, I1, "INTEGRAL.EXP.GENERAL_BASE", "지수함수 부정적분", "지수함수의 부정적분", "하", S, "(1) e^(x−1)+2^(x+1)/ln2+C (2) 3ˣ/ln3−x+C", "식(소문항별)", 2, trap="9ˣ−1=(3ˣ+1)(3ˣ−1)")
r(8, I1, "DEFINT.EXP.FACTOR", "지수함수 정적분(예제)", "지수함수의 정적분", "하", S, "(1) 21/ln2 (2) e²−e−3/2", "값(소문항별)", 2)
r(9, I1, "DEFINT.EXP.FACTOR", "지수함수 정적분", "지수함수의 정적분;인수분해", "중하", S, "(1) 12/ln3 (2) −1+e+1/(8ln2) (3) 1+2/ln2 (4) 9/4", "값(소문항별)", 4, c=M)
r(10, I1, "INTEGRAL.TRIG.TABLE_FROM_DERIVATIVES", "삼각함수 미분 표로 부정적분 표 완성", "삼각함수의 부정적분", "하", "빈칸채우기", "도함수: −sin x, sec²x, −csc²x; 부정적분: −cos x+C, tan x+C, −cot x+C", "식", 2, fig="표")
r(11, I1, "INTEGRAL.TRIG.BASIC", "삼각함수 부정적분", "삼각함수의 부정적분", "하", S, "(1) −cos x+sin x+C (2) −2cos x+cot x+C (3) sec x+tan x+C (4) x+csc x+C", "식(소문항별)", 4)
r(12, I1, "DEFINT.TRIG.SPLIT_SEC2", "삼각함수 분수식 정적분(예제)", "삼각함수의 정적분", "하", S, "√2−3")
r(13, I1, "DEFINT.TRIG.SPLIT_SEC2", "삼각함수 정적분", "삼각함수의 정적분", "중하", S, "(1) 3−π/2 (2) 3−√2−√3", "값(소문항별)", 2, c=M)
r(14, I1, "INTEGRAL.TRIG.IDENTITY_SIMPLIFY", "삼각 항등식 변형 후 부정적분(예제)", "삼각함수의 부정적분;삼각함수 사이의 관계", "하", S, "(1) −cos x+C (2) x+cos x+C", "식(소문항별)", 2)
r(15, I1, "INTEGRAL.TRIG.IDENTITY_SIMPLIFY", "tan², (1+sin²)/sin² 부정적분", "삼각함수의 부정적분;삼각함수 사이의 관계", "하", S, "(1) tan x−x+C (2) −cot x+x+C", "식(소문항별)", 2)
r(16, I1, "DEFINT.TRIG.IDENTITY_SIMPLIFY", "삼각 항등식 변형 정적분", "삼각함수의 정적분", "하", S, "(1) 2 (2) π/2−1", "값(소문항별)", 2)
r(17, I1, "DEFINT.TRIG.ABS_VALUE_SPLIT", "|sin x−cos x| 정적분 단계별(탐구)", "절댓값 함수의 정적분;삼각함수", "중하", "서술형(탐구)", "해 x=π/4; [0,π/4]에서 ≤0, [π/4,π]에서 ≥0; 값 2√2", "값", 3, d=M, i=M, final="2√2", chk="독립풀이 2√2 (파일 '풀이 참조')")
r(18, I2, "DERIV.CHAIN.PREP", "합성함수 미분(준비)", "합성함수의 미분법", "하", S, "(1) y′=3(x−1)² (2) y′=3cos(3x+1)", "식(소문항별)", 2)
r(19, I2, "SUBST.LINEAR.INTUITION", "합성함수 도함수로 ∫(2x−1)⁹dx(생각 열기)", "치환적분법", "하", ACT, "➊ 20(2x−1)⁹ ➋ (1/20)(2x−1)¹⁰+C", "식", 2)
r(20, I2, "SUBST.LINEAR.BASIC", "일차식 치환(예제)", "치환적분법;∫f(ax+b)dx", "하", S, "(1) (1/15)(3x−2)⁵+C (2) −(1/2)cos(2x+1)+C", "식(소문항별)", 2)
r(21, I2, "SUBST.LINEAR.BASIC", "일차식 치환", "치환적분법;∫f(ax+b)dx", "하", S, "(1) (1/12)(2x+3)⁶+C (2) 2sin(x/2−3)+C (3) (1/6)(4x+1)√(4x+1)+C (4) (1/3)e^(3x−1)+C", "식(소문항별)", 4)
r(22, I2, "SUBST.INNER_DERIVATIVE.BASIC", "f(g(x))g′(x) 꼴 치환(예제)", "치환적분법", "하", S, "(1) (1/6)(x²−1)⁶+C (2) −(1/3)cos³x+C", "식(소문항별)", 2)
r(23, I2, "SUBST.INNER_DERIVATIVE.BASIC", "f(g(x))g′(x) 꼴 치환", "치환적분법", "중하", S, "(1) (1/2)e^(x²)+C (2) (1/4)sin⁴x+C (3) (1/3)(x²−1)√(x²−1)+C (4) (2/3)(eˣ+1)√(eˣ+1)+C", "식(소문항별)", 4, c=M)
r(24, I2, "SUBST.LINEAR.FORMULA_PROOF", "∫f(ax+b)dx=(1/a)F(ax+b)+C 증명", "치환적분법", "하", PRF, "t=ax+b 치환으로 성립", "증명", final="풀이 참조")
r(25, I2, "SUBST.LOG_DERIVATIVE.DERIVATION", "∫f′/f dx=ln|f|+C 유도(빈칸)", "치환적분법;f′(x)/f(x) 꼴", "하", "빈칸채우기", "f′(x), 1/t, |f(x)|", "식")
r(26, I2, "SUBST.LOG_DERIVATIVE.BASIC", "f′/f 꼴 부정적분(예제)", "f′(x)/f(x) 꼴의 부정적분", "하", S, "(1) ln|x²−1|+C (2) −ln|cos x|+C", "식(소문항별)", 2)
r(27, I2, "SUBST.LOG_DERIVATIVE.BASIC", "f′/f 꼴 부정적분", "f′(x)/f(x) 꼴의 부정적분", "하", S, "(1) ln|x³−x+1|+C (2) ln|sin x|+C (3) ln(eˣ+e⁻ˣ)+C (4) ln|ln x|+C", "식(소문항별)", 4)
r(28, I2, "INTEGRAL.RATIONAL.DIVIDE_PARTIAL_FRACTION", "유리함수 나눗셈·부분분수(예제)", "유리함수의 부정적분;부분분수", "하", S, "(1) x²/2+4ln|x−3|+C (2) ln|x/(x+1)|+C", "식(소문항별)", 2)
r(29, I2, "INTEGRAL.RATIONAL.DIVIDE_PARTIAL_FRACTION", "유리함수 나눗셈·부분분수", "유리함수의 부정적분;부분분수", "중하", S, "(1) x²−5ln|x+1|+C (2) (3/2)x²−5x+27ln|x+5|+C (3) (1/2)ln|(x−2)/x|+C (4) ln|(x−1)/(x+1)|+C", "식(소문항별)", 4, c=M)
r(30, I2, "SUBST.DEFINITE.LIMITS_CHANGE", "치환 정적분(적분구간 변경, 예제)", "치환적분법;정적분", "하", S, "(1) 1/3 (2) ln((e+1)/2)", "값(소문항별)", 2)
r(31, I2, "SUBST.DEFINITE.LIMITS_CHANGE", "치환 정적분", "치환적분법;정적분", "중하", S, "(1) 6/25 (2) 1/3 (3) √2−1 (4) e(e³−1)", "값(소문항별)", 4, c=M)
r(32, I2, "SUBST.TRIG_SUBSTITUTION.EXPLORE", "삼각치환 정적분(탐구)", "치환적분법;삼각치환", "중", "서술형(탐구)", "π/2, π/4, √3−1", "값(소문항별)", 3, c=M, i=M, review="REVIEW-부분검산", ready="REVIEW", status="부분검산((3) 본문 미추출)", trust="중간((3) 미검산)", chk="(1)(2) 독립풀이 일치; (3) x=secθ 치환 문항 본문 일부 미추출 — 파일 답 기준")
r(33, I2, "SUBST.APPLIED.BIP_POLLUTION", "생물학적 오염 지표와 적분(탐구)", "치환적분법;삼각함수의 적분;실생활", "중", "서술형(탐구)", "풀이 참조", "서술", combo="적분+실생활", final="풀이 참조", review="REVIEW-정답지미연결", ready="REVIEW", status="정답 미확정(풀이 참조)", trust="중간(정답 미연결)", chk="파일 정답 '풀이 참조', 탐구 본문 일부 미추출")
r(34, I3, "DERIV.PRODUCT.PREP", "곱의 미분(준비)", "곱의 미분법", "하", S, "(1) y′=eˣ(1+x) (2) y′=cos²x−sin²x", "식(소문항별)", 2)
r(35, I3, "IBP.INTUITION.X_COS_X", "곱의 미분으로 ∫x cos x dx(생각 열기)", "부분적분법", "하", ACT, "➊ (x sin x)′−sin x ➋ x sin x−∫sin x dx (=x sin x+cos x+C)", "식", 2)
r(36, I3, "IBP.BASIC.POLY_EXP_LOG", "부분적분 기본(예제)", "부분적분법", "하", S, "(1) xeˣ−eˣ+C (2) x ln x−x+C", "식(소문항별)", 2)
r(37, I3, "IBP.BASIC.POLY_EXP_LOG", "부분적분 기본", "부분적분법", "하", S, "(1) −e⁻ˣ(x−1)+C (2) x³(ln x−1/3)+C", "식(소문항별)", 2)
r(38, I3, "IBP.CYCLIC.EXP_TRIG", "eˣcos x 순환 부분적분(예제)", "부분적분법(순환형)", "중하", S, "(1/2)eˣ(sin x+cos x)+C", "식", c=M, i=M)
r(39, I3, "IBP.CYCLIC.EXP_TRIG", "eˣsin x, (ln x)² 부분적분", "부분적분법(순환형·반복)", "중하", S, "(1) (1/2)eˣ(sin x−cos x)+C (2) x{(ln x)²−2ln x+2}+C", "식(소문항별)", 2, c=M, i=M)
r(40, I3, "IBP.APPLIED.SOUND_WAVE", "파동 함수 f′로 f 구하기(실생활)", "부분적분법;부정적분", "중하", S, "f(t)=e⁻ᵗsin t+C", "식", c=M, combo="적분+실생활")
r(41, I3, "IBP.DEFINITE.BASIC", "부분적분 정적분(예제)", "부분적분법;정적분", "하", S, "(1) π/2−1 (2) (e−1)ln2+1", "값(소문항별)", 2)
r(42, I3, "IBP.DEFINITE.BASIC", "부분적분 정적분", "부분적분법;정적분", "중하", S, "(1) 1−2/e (2) 2/e−3/e²", "값(소문항별)", 2, c=M)
r(43, I3, "IBP_SUBST.COMPARE_METHODS", "∫sin x cos x 세 방법 비교(탐구)", "치환적분법;부분적분법;배각공식", "중하", "서술형(탐구)", "결과는 모두 1/4로 같다", "값", i=M, final="1/4")
r(44, I3, "IBP.LIATE_RULE", "LIATE 순서로 부분적분(탐구)", "부분적분법", "중하", "서술형(탐구)", "(1) (1/9)e^(3x)(3x−7)+C (2) (x²−2)sin x+2x cos x+C (3) (1/9)x³(3ln x−1)+C", "식(소문항별)", 3, c=M, chk="독립풀이(미분 역검산) 일치")
r(45, I1, "INTEGRAL.POWER.MIXED_REVIEW", "xⁿ 부정적분·정적분(중단원 마무리)", "xⁿ의 부정적분;정적분", "하", S, "(1) −1/(2x²)+C (2) 2√x−(2/3)x√x+C (3) 96/5 (4) (2/3)e√e−2/3", "식·값(소문항별)", 4)
r(46, I1, "INTEGRAL.EXP_TRIG.MIXED_REVIEW", "지수·삼각 부정적분·정적분(중단원 마무리)", "지수함수의 적분;삼각함수의 적분", "하", S, "(1) 2^(x+2)/ln2+C (2) −cot x−x+C (3) e−2 (4) 2+π/4", "식·값(소문항별)", 4)
r(47, I2, "SUBST.MIXED_REVIEW", "치환적분 부정적분(중단원 마무리)", "치환적분법", "하", S, "(1) −(1/2)e^(1−2x)+C (2) (1/4)(x²−1)⁴+C (3) −2√(1−x²)+C (4) ln(1+sin x)+C", "식(소문항별)", 4)
r(48, I2, "SUBST.DEFINITE.LIMITS_CHANGE", "치환 정적분(중단원 마무리)", "치환적분법;정적분", "중하", S, "(1) (e⁵−e)/2 (2) 26/15", "값(소문항별)", 2, c=M)
r(49, I3, "IBP.MIXED_REVIEW", "부분적분(중단원 마무리)", "부분적분법", "중하", S, "(1) (1/3)xe^(3x)−(1/9)e^(3x)+C (2) (2/3)x√x ln x−(4/9)x√x+C (3) 1 (4) 1", "식·값(소문항별)", 4, c=M)
r(50, I2, "INTEGRAL.RATIONAL.PARTIAL_FRACTION_AND_RADICAL", "부분분수·거듭제곱근 나눗셈 적분", "부분분수;유리화", "중하", S, "(1) ln|x−3|−ln|x+1|+C (2) (3/5)∛(x⁵)−(3/4)∛(x⁴)+x+C", "식(소문항별)", 2, c=M, trap="x+1=(∛x+1)(∛x²−∛x+1)")
r(51, I1, "INTEGRAL.INITIAL_CONDITION.RATIONAL", "부정적분+초기조건 f(2)", "부정적분;적분상수", "하", S, "2+ln2")
r(52, I3, "DEFINT.MIXED.SUBST_IBP", "여러 가지 정적분(중단원 마무리)", "치환적분법;부분적분법;정적분", "중", S, "(1) 2√3+π²/18 (2) 2/3 (3) 1/3 (4) −2π", "값(소문항별)", 4, c=M, d=M)
r(53, I3, "IBP.FUNCTIONAL_EQUATION.INTEGRAL", "∫f dx=xf(x)−x²e⁻ˣ에서 f(4)", "부정적분과 미분의 관계;부분적분법", "중", D, "3e⁻⁴", c=M, d=M, i=M, combo="미분+적분")
r(54, I1, "INTEGRAL.INITIAL_CONDITION.EXP_EQUATION", "f′와 f(0)로 방정식 f(x)=0 해", "지수함수의 부정적분;지수방정식", "중하", S, "ln3", d=M, combo="적분+지수방정식")
r(55, I1, "DEFINT.EXP.ABS_VALUE_SPLIT", "|eˣ−1| 정적분", "절댓값 함수의 정적분", "중하", S, "e³+1/e−4", d=M)
r(56, I1, "DEFINT.FUNCTIONAL_EQUATION.CONSTANT", "f=ln x+∫₁ᵉf(t)dt (정적분=상수)", "정적분으로 정의된 함수;부분적분법", "중", S, "(2e−5)/(e−2)", c=M, d=M, i=M)
r(57, I1, "INTEGRAL.TRIG.IDENTITY_TRIVIAL", "1/((1+tan²x)cos²x) 부정적분", "삼각함수 사이의 관계;부정적분", "하", S, "f(x)=x−π/4", "식", trap="피적분함수=1")
r(58, I1, "INTEGRAL.PIECEWISE.CONTINUITY", "구간별 f′와 연속으로 f(0)+f(−π/6)", "부정적분;함수의 연속;부분적분법", "중", S, "−5/2", c=M, d=M, i=M)
r(59, I3, "INTEGRAL.INVERSE_OF_DERIVATIVE", "f′의 역함수 g로 ∫g(x−1)dx", "역함수;지수함수의 부정적분", "중", S, "e", d=M, i=M)
r(60, I2, "SUBST.DEFINITE.F_TIMES_FPRIME", "조건으로 ∫f(x)g(x)dx (g=f′ 꼴)", "치환적분법", "중", S, "6", c=M, d=M, fig="조건(미추출)", **NK)
r(61, I3, "DEFINT.FUNCTIONAL_EQUATION.CONSTANT", "f=5x cos x+∫f(t)dt로 f(0)", "정적분으로 정의된 함수;부분적분법", "중", D, "−5", c=M, d=M, i=M)
r(62, I3, "INTEGRAL.INVERSE_FUNCTION.LOG", "e^x−1 역함수의 부정적분 g", "역함수;부분적분법", "중", S, "2", c=M, d=M)
r(63, J1, "SERIES.GEOMETRIC.PREP", "등비급수 합(준비)", "등비급수", "하", S, "(1) 3/4 (2) 6", "값(소문항별)", 2)
r(64, J1, "RIEMANN.GRID.INTUITION", "모눈 크기와 넓이 어림(생각 열기)", "구분구적법", "하", ACT, "➊ [그림 3] ➋ 모눈의 크기를 작게 한다", "서술", 2, fig="그림")
r(65, J1, "RIEMANN.UPPER_LOWER_SUM.LINEAR", "y=2x 상합·하합과 정적분(탐구)", "구분구적법;정적분", "하", "서술형(탐구)", "Mₙ=(n+1)/n, mₙ=(n−1)/n, 두 극한=∫₀¹2x dx=1", "식·값", 3, fig="그림", final="풀이 참조(극한 1)", chk="독립풀이 일치")
r(66, J1, "RIEMANN.SUM_TO_INTEGRAL.POLY", "급수의 합으로 ∫₀²x²dx(예제)", "정적분과 급수의 합", "하", S, "8/3")
r(67, J1, "RIEMANN.SUM_TO_INTEGRAL.POLY", "급수의 합으로 정적분", "정적분과 급수의 합;Σ 공식", "중하", S, "(1) −4 (2) 1/4", "값(소문항별)", 2, c=M)
r(68, J1, "RIEMANN.LIMIT_AS_INTEGRAL.POWER", "Σk²/n³ 극한을 정적분으로(예제)", "정적분과 급수의 합", "하", S, "1/3")
r(69, J1, "RIEMANN.LIMIT_AS_INTEGRAL.POWER_TRIG", "급수 극한을 정적분으로", "정적분과 급수의 합", "중하", S, "(1) 1/5 (2) 2", "값(소문항별)", 2, d=M)
r(70, J1, "RIEMANN.LIMIT_AS_INTEGRAL.XK_CHOICE", "xₖ 선택에 따른 정적분 형태(탐구)", "정적분과 급수의 합", "중", "서술형(탐구)", "(가)−ㄷ, (나)−ㄱ, (다)−ㄴ", "대응", 3, fig="보기", i=M, chk="파일 정답 기준(보기 일부 미추출: ∫₁³x²dx 등)", review="REVIEW-그림판독")
r(71, J1, "RIEMANN.CAS_ACTIVITY", "프로그램 상합·하합과 정적분 비교(활동)", "구분구적법;정적분", "하", ACT, "풀이 참조(정적분 값 3)", "서술", final="풀이 참조", chk="정적분 ∫₋₂¹(x+1)²dx=3 독립산출")
r(72, J2, "AREA.CURVE_AXIS.PREP", "곡선과 x축 넓이(준비)", "정적분과 넓이", "하", S, "4/3")
r(73, J2, "AREA.SIGN_CHANGE.INTUITION", "x축 아래 부분 넓이 정적분 표현(생각 열기)", "정적분과 넓이", "하", ACT, "∫₀²(−x+2)dx+∫₂³(x−2)dx", "식", fig="그림")
r(74, J2, "AREA.CURVE_AXIS.SIGN_CHANGE", "cos x와 x축 넓이(예제)", "정적분과 넓이;부호 변화", "하", S, "2")
r(75, J2, "AREA.CURVE_AXIS.EXP_LOG", "곡선과 x축 사이 넓이", "정적분과 넓이", "하", S, "(1) 1 (2) e+1/e−2", "값(소문항별)", 2, d=M)
r(76, J2, "AREA.BETWEEN_CURVES.TRIG", "sin x, sin2x 사이 넓이(예제)", "두 곡선 사이의 넓이", "중하", S, "5/2", c=M, d=M)
r(77, J2, "AREA.BETWEEN_CURVES.EXP_POWER", "두 곡선 사이 넓이", "두 곡선 사이의 넓이", "중하", S, "(1) e²+e+1/e+1/e²−4 (2) 49/12", "값(소문항별)", 2, c=M, d=M, trap="교점 기준 구간 분할")
r(78, J3, "VOLUME.CYLINDER.PREP", "원기둥 부피(준비)", "부피", "하", S, "πx²h", "식")
r(79, J3, "VOLUME.CROSS_SECTION.HEMISPHERE_WATER", "반구 그릇 물의 부피(생각 열기)", "단면적과 부피", "하", ACT, "➊ (2000/3)π cm³ ➋ (2000/3)π로 같다", "값", 2)
r(80, J3, "VOLUME.CROSS_SECTION.PYRAMID", "정적분으로 사각뿔 부피(예제)", "단면적과 부피;닮음", "하", S, "(1/3)Sh", "식")
r(81, J3, "VOLUME.CROSS_SECTION.WATER_TANK_LOG", "수면 넓이 900ln(x+1) 수조 부피", "단면적과 부피;부분적분법", "중하", S, "(18900ln21−18000) cm³", c=M, combo="부피+부분적분")
r(82, J3, "VOLUME.CROSS_SECTION.SQUARE_ON_CURVE", "단면 정사각형 입체(예제)", "단면적과 부피", "하", S, "2")
r(83, J3, "VOLUME.CROSS_SECTION.EQUILATERAL_ON_CURVE", "단면 정삼각형 입체", "단면적과 부피", "중하", S, "4√3/15", c=M)
r(84, J3, "VOLUME.CROSS_SECTION.WEDGE_FROM_CYLINDER", "원기둥 쐐기 부피(탐구)", "단면적과 부피", "중", "서술형(탐구)", "S(x)=(√3/2)(a²−x²), 부피 (2√3/3)a³", "식·값", 2, fig="그림", c=M, i=M)
r(85, J3, "VOLUME.CROSS_SECTION.SPHERE_CONE_EXPLORE", "반구·원뿔 등 부피를 정적분으로(탐구)", "단면적과 부피", "중하", "서술형(탐구)", "반구 ∫₀ʳπ(r²−x²)dx=(2/3)πr³ 등 공식과 같다", "식·값", 3, fig="그림", final="풀이 참조", i=M)
r(86, J4, "DISPLACEMENT.LINE.PREP", "속도로 위치(준비)", "속도와 위치", "하", S, "16", chk="독립풀이 일치(원점 출발 가정 — 본문 '점을 출발' 표기)")
r(87, J4, "DISTANCE.LINE.AREA_INTUITION", "v(t) 그래프 넓이 의미(생각 열기)", "속도와 거리", "하", ACT, "v(t)=2t 그래프; 넓이 4는 t=0~2 이동 거리(위치 변화량)", "서술", 2, fig="그래프(작도)", final="풀이 참조")
r(88, J4, "DISTANCE.LINE.TRIG", "위치·움직인 거리(예제)", "직선 운동의 위치와 거리", "하", S, "(1) −(1/π)cosπt+1/π (2) 2/π", "식·값", 2)
r(89, J4, "DISTANCE.LINE.TRIG", "위치·움직인 거리", "직선 운동의 위치와 거리", "중하", S, "(1) (2/π)sin(πt/2) (2) 6/π", "식·값", 2, d=M, trap="부호 바뀌는 t=1 분할")
r(90, J4, "DISTANCE.PLANE.EXP_TRIG", "평면 운동 거리(예제)", "평면 운동의 거리", "중하", S, "(e−1)√(1+π²)", c=M)
r(91, J4, "DISTANCE.PLANE.POLY", "평면 운동 거리", "평면 운동의 거리", "중하", S, "4/3", c=M, trap="속력 완전제곱 t²+1")
r(92, J4, "ARC_LENGTH.CURVE.POWER", "y=x√x 곡선의 길이(예제)", "곡선의 길이", "중하", S, "(2/27)(11√22−4)", c=M)
r(93, J4, "ARC_LENGTH.CURVE.PERFECT_SQUARE", "y=x²/4−ln√x 곡선의 길이", "곡선의 길이", "중하", S, "(1+e²)/4", c=M, trap="1+y′² 완전제곱")
r(94, J4, "ARC_LENGTH.CYCLOID.SLIDE", "사이클로이드 미끄럼틀 길이(탐구)", "곡선의 길이;매개변수", "중", "서술형(탐구)", "12", fig="그림", c=M, i=M, chk="파일 정답 기준(매개변수식 일부 그림 내 표기)")
r(95, J1, "RIEMANN.SUM_TO_INTEGRAL.BLANK", "급수로 ∫₀¹(−x)dx(빈칸, 중단원 마무리)", "정적분과 급수의 합", "하", "빈칸채우기", "1, k, n², n², −1/2", "식")
r(96, J2, "AREA.CURVE_AXIS.TRIG_RECIPROCAL", "넓이(중단원 마무리)", "정적분과 넓이", "하", S, "(1) 1 (2) ln3", "값(소문항별)", 2)
r(97, J2, "AREA.BETWEEN_CURVES.SIN_COS", "sin, cos 사이 넓이", "두 곡선 사이의 넓이", "하", S, "2√2")
r(98, J3, "VOLUME.CROSS_SECTION.WATER_EXP", "수면 넓이 eˣ+2x−1 그릇 부피", "단면적과 부피", "하", S, "(e⁴+11) cm³")
r(99, J4, "DISTANCE.LINE.EXP_IBP", "v=(t−1)eᵗ 위치·거리", "직선 운동의 위치와 거리;부분적분법", "중", S, "(1) (t−2)eᵗ+2 (2) e³+2e−2", "식·값", 2, c=M, d=M, trap="t=1에서 부호 변화")
r(100, J1, "RIEMANN.LIMIT_AS_INTEGRAL.SCALED", "급수 극한을 정적분으로(중단원 마무리)", "정적분과 급수의 합", "중하", S, "(1) 16/5 (2) 2/3", "값(소문항별)", 2, d=M)
r(101, J2, "AREA.CURVE_AXIS.RATIONAL", "y=2/(1+x) 넓이", "정적분과 넓이", "하", S, "2ln5")
r(102, J2, "AREA.EQUAL_PARTS.PARAM", "색칠한 두 넓이 같을 때 a", "두 곡선 사이의 넓이;정적분=0", "중", S, "√3", fig="그림", d=M, i=M, trap="넓이 같음⇔정적분 0")
r(103, J3, "VOLUME.CROSS_SECTION.CIRCLE_TRIG", "단면 원(반지름 √sin) 부피", "단면적과 부피", "중하", D, "(√3/2)π")
r(104, J3, "VOLUME.CROSS_SECTION.SQUARE_BETWEEN_CURVES", "±√x 사이 단면 정사각형 부피", "단면적과 부피", "중하", S, "32", fig="그림")
r(105, J4, "DISPLACEMENT.LINE.FARTHEST_POSITION", "원점에서 가장 먼 위치", "직선 운동의 위치;극값", "중상", S, "(5√3/3)π+2", c=M, d=M, i=H, trap="v=0 후보 t=5π/3, 2π 비교")
r(106, J4, "DISTANCE.PLANE.LOG_RECIPROCAL", "x=ln t, y=(t+1/t)/2 거리", "평면 운동의 거리", "중하", S, "e−1/e", c=M, trap="속력 완전제곱")
r(107, J1, "RIEMANN.LIMIT_AS_INTEGRAL.TRIG", "Σ(π/n)tan²(kπ/4n) 극한", "정적분과 급수의 합;삼각함수의 적분", "중", S, "4−π", c=M, d=M)
r(108, J2, "AREA.BISECT.PARAM", "y=sin x가 넓이 이등분하는 a", "두 곡선 사이의 넓이", "중상", S, "4/3", c=M, d=M, i=H)
r(109, J3, "VOLUME.CROSS_SECTION.MAX_AREA_THEN_VOLUME", "수면 넓이 최대일 때 물의 부피", "단면적과 부피;최대;치환적분법", "중상", D, "(π/2)ln(8/5)", c=M, d=M, i=H, combo="최대+부피+치환")
r(110, J4, "DISTANCE.PLANE.IMPROPER_LIMIT", "s(a)의 a→∞ 극한", "평면 운동의 거리;극한", "중", S, "√2", c=M, i=M)
r(111, I1, "INTEGRAL.INITIAL_CONDITION.EXP_TRIG", "f′와 f(0)로 f(π)", "부정적분;적분상수", "하", MC, "④", "선택지번호", final="④ (e^π−1)")
r(112, I1, "INTEGRAL.SLOPE_FUNCTION.LOG", "접선 기울기 −1/x 곡선 f(e)", "부정적분;접선", "하", MC, "②", "선택지번호", final="② (−1)")
r(113, I3, "INTEGRAL.ANTIDERIVATIVE_IDENTITY", "F=xf−sin x+x cos x에서 f(π/2)", "부정적분과 미분의 관계", "중", MC, "③", "선택지번호", c=M, i=M, final="③ (1)")
r(114, I1, "INTEGRAL.PIECEWISE.CONTINUITY", "구간별 f′, f(π)+f(−π)", "부정적분;함수의 연속", "중", S, "0", c=M, i=M)
r(115, I2, "INTEGRAL.RATIONAL.PARTIAL_FRACTION_VALUE", "부분분수 부정적분 f(5)−f(3)", "부분분수", "중하", MC, "②", "선택지번호", final="② (−ln3)")
r(116, I2, "SUBST.LOG_INNER.SLOPE_FUNCTION", "기울기 sin(ln x)/x 곡선 f(e^π)", "치환적분법", "중하", MC, "④", "선택지번호", final="④ (3)")
r(117, I2, "SUBST.LINEAR_SCALE.ARCTAN_GIVEN", "∫₀¹1/(1+x²)=π/4 이용 ∫₋₃³1/(9+x²)", "치환적분법;우함수", "중하", S, "π/6", d=M)
r(118, I2, "SUBST.TRIG.TAN_CUBE", "∫tan³x dx", "치환적분법;삼각함수 사이의 관계", "중하", MC, "⑤", "선택지번호", c=M, final="⑤ (ln|cos x|+1/(2cos²x)+C)")
r(119, I3, "IBP.INITIAL_CONDITION.POLY_EXP", "f′=(x²−2)eˣ, f(0)=e일 때 f(1)", "부분적분법;적분상수", "중하", S, "0", c=M)
r(120, I3, "IBP.CYCLIC.DEFINITE_EXP_SIN", "∫₀^π eˣsin x=ae^π+b", "부분적분법(순환형)", "중", S, "1", c=M, i=M)
r(121, J1, "RIEMANN.SERIES_TO_INTEGRAL.IDENTIFY", "급수를 정적분으로 나타낼 때 피적분함수", "정적분과 급수의 합", "중하", MC, "①", "선택지번호", fig="급수식(미추출)", final="① (x³)", **NK)
r(122, J1, "RIEMANN.LIMIT_AS_INTEGRAL.RECIPROCAL", "Σf(1+3k/n)/n 극한(f=1/x)", "정적분과 급수의 합", "중하", MC, "②", "선택지번호", final="② ((2/3)ln2)")
r(123, J2, "AREA.TANGENT_CURVE_AXIS", "ln x·접선·x축 넓이", "정적분과 넓이;접선", "중하", MC, "①", "선택지번호", c=M, final="① (e/2−1)")
r(124, J2, "AREA.FUNCTION_AND_INVERSE", "f=x+sin x와 역함수 사이 넓이", "두 곡선 사이의 넓이;역함수 대칭", "중", S, "4", d=M, i=M)
r(125, J3, "VOLUME.CROSS_SECTION.WATER_TRIG", "수면 넓이 3/2일 때 수조 부피", "단면적과 부피;반각 공식", "중", MC, "③", "선택지번호", c=M, d=M, final="③ (3−6/π)")
r(126, J3, "VOLUME.CROSS_SECTION.SQUARE_TAN", "y=tan x 밑면 단면 정사각형 부피", "단면적과 부피", "하", S, "1−π/4")
r(127, J4, "DISTANCE.LINE.BOGI", "v=sin(πt/2) 보기 판정", "직선 운동의 위치와 거리", "중하", MC, "④", "선택지번호", fig="보기(미추출)", final="④ (ㄱ, ㄷ)", **NK)
r(128, J4, "ARC_LENGTH.INTEGRAL_DEFINED_CURVE", "y=∫√(sec⁴t−1)dt 곡선 길이", "곡선의 길이;정적분으로 정의된 함수", "중", S, "2", c=M, i=M)
r(129, I3, "DEFINT.FUNCTIONAL_EQUATION.CONSTANT", "적분 방정식으로 f(0)", "정적분으로 정의된 함수;부분적분법", "중", S, "−1", c=M, d=M, fig="식(미추출)", **NK)
r(130, J1, "RIEMANN.LIMIT_AS_INTEGRAL.COS", "Σcos(kπ/n)/n 극한", "정적분과 급수의 합", "중하", D, "0")
r(131, J2, "AREA.BETWEEN_CURVES.SIN_SIN3", "sin x, sin³x 사이 넓이", "두 곡선 사이의 넓이;치환적분법", "중하", D, "1/3", c=M)
r(132, J4, "DISTANCE.PLANE.SOLVE_TIME", "움직인 거리 6일 때 시각", "평면 운동의 거리", "중", S, "2", c=M, d=M, trap="속력 t+2")
assert len(ROWS) == 132 and [x['_q'] for x in ROWS] == list(range(1, 133))
for i in range(14): build(f"Batch{370+i}", ROWS[i*10:(i+1)*10], 12166+i*10)
