from cfgy2 import *
import cfgy2, builder, bisect
SQ = hashlib.sha256(open(OUT+'h61/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y61.json'))
setup(QID="A02461", SRC="1wbZyxs4nF7nLqs_KIRpwy63euApEf51Y", SHA=SQ, TAG="YMSS01", N=92, SUBJ="수학(상)", SEC="S01A",
      FNAME="01 다항식(신사고) 92제.hwp", UNIT="Ⅰ. 다항식", BIG="Ⅰ. 다항식", EXAM="1. 다항식 92제", MID="다항식")
cfgy2.P.update(BOOK="신사고 수학(상)", GRADE="고1", MEMO_X="파서: '[tbl] 정답' 형식 정답 줄(51번) 인식 보정 후 92문항=빠른 정답 92개 정렬 일치(파일명 92제); ")
B = [1, 8, 18, 32, 37, 49, 59, 74]
MIDS = ["다항식의 덧셈과 뺄셈", "다항식의 곱셈과 나눗셈", "다항식의 연산(중단원 마무리)", "항등식", "나머지정리", "인수분해", "나머지정리와 인수분해(중단원 마무리)", "다항식 종합(대단원 마무리)"]
SECS = [f"S01{chr(65+j)}" for j in range(len(B))]
for s, mid in zip(SECS, MIDS): builder.SECTIONS[s] = ("1. 다항식 92제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, MC = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "5지선다"
A1, A2, A3, A4, A5 = "다항식의 덧셈과 뺄셈", "다항식의 곱셈과 나눗셈", "항등식", "나머지정리", "인수분해"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = SECS[bisect.bisect_right(B, q) - 1]
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·표 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건식·보기(수식 객체) 본문 미추출 — 해설로 조건 복원, 파일 정답 기준")
r(1, A1, "POLY.MONOMIAL_OPS.PREP", "단항식·다항식 계산(준비)", "다항식의 계산", "하", S, "(1) 6x−5y (2) 5x²−5x−4 (3) 2x³y⁴ (4) −2x²y", "식(소문항별)", 4)
r(2, A2, "POLY.EXPANSION.PREP", "곱셈공식 전개(준비)", "곱셈공식", "하", S, "(1) a²−4ab+4b² (2) 9a²−b² (3) a²−a−12 (4) 10a²−21ab−10b²", "식(소문항별)", 4)
r(3, A1, "POLY.ORDERING.ASC_DESC", "내림차순·오름차순 정리", "다항식의 정리", "하", S, "(1) x³+5x²y−2xy²−1 (2) x³−1+5x²y−2xy²", "식(소문항별)", 2, trap="y 기준 오름차순")
r(4, A1, "POLY.ADD_SUB.BASIC", "A+B, A−B", "다항식의 덧셈과 뺄셈", "하", S, "(1) 7x³−x²+x, x³+x²+3x−2 (2) 3x³+2x²+x−5, −x³+7x−1", "식(소문항별)", 4)
r(5, A1, "POLY.ADD_SUB.SIMPLIFY_FIRST", "식 정리 후 대입(예제)", "다항식의 덧셈과 뺄셈", "하", S, "−3x²+7xy−6y²", "식")
r(6, A1, "POLY.ADD_SUB.SIMPLIFY_FIRST", "세 다항식 연산", "다항식의 덧셈과 뺄셈", "하", S, "(1) −7x³−2x²+6x+14 (2) 14x³−2x²+12x−25", "식(소문항별)", 2)
r(7, A1, "POLY.ADD_SUB.MAGIC_SQUARE", "다항식 마방진(활동)", "다항식의 덧셈과 뺄셈", "중하", ACT, "1) ㈑ 먼저 2) 풀이참조(빈칸 다항식)", "식", 2, fig="표", final="풀이참조", **FK)
r(8, A2, "POLY.MULT.DISTRIBUTE", "다항식 곱 전개", "다항식의 곱셈", "하", S, "(1) x³+3x²+3x+2 (2) 2x³−13x²y+19xy²−20y³", "식(소문항별)", 2)
r(9, A2, "POLY.MULT.CUBIC_FORMULA", "세제곱 곱셈공식(예제)", "곱셈공식", "하", S, "(1) 27x³+54x²+36x+8 (2) 8x³−y³", "식(소문항별)", 2)
r(10, A2, "POLY.MULT.CUBIC_FORMULA", "곱셈공식 전개", "곱셈공식", "하", S, "(1) 4x²+y²+4z²−4xy−4yz+8zx (2) x³−9x²y+27xy²−27y³ (3) x³+8 (4) x³−125y³", "식(소문항별)", 4)
r(11, A2, "POLY.MULT_FORMULA.SYMMETRIC_VALUE", "x³+y³ 값(예제)", "곱셈공식의 변형", "하", S, "45")
r(12, A2, "POLY.MULT_FORMULA.SYMMETRIC_VALUE", "x³−y³ 값", "곱셈공식의 변형", "하", S, "52")
r(13, A2, "POLY.MULT_FORMULA.SYMMETRIC_VALUE", "x²+y²로 x³+y³", "곱셈공식의 변형", "하", S, "14", trap="xy 먼저")
r(14, A2, "POLY.DIVISION.LONG", "다항식 나눗셈 몫·나머지", "다항식의 나눗셈", "하", S, "(1) 몫 3x²+x+4, 나머지 5 (2) 몫 −2x²+x+4, 나머지 −6x−18", "식(소문항별)", 2, c=M)
r(15, A2, "POLY.DIVISION.A_EQ_BQ_R", "A=BQ+R 꼴(예제)", "다항식의 나눗셈", "하", S, "Q=2x²+x+3, R=4; 4x³+5x+1=(2x−1)(2x²+x+3)+4", "식")
r(16, A2, "POLY.DIVISION.A_EQ_BQ_R", "A=BQ+R 꼴", "다항식의 나눗셈", "하", S, "(1) Q=2x²+3x+10, R=21 (2) Q=3x−3, R=12x−10", "식(소문항별)", 2)
r(17, A2, "POLY.DETACHED_COEFFICIENTS", "계수만으로 곱셈·나눗셈(탐구)", "다항식의 곱셈과 나눗셈", "중하", ACT, "풀이참조(활동3: (1) 4x³−18x²−11x+5 (2) 몫 2x+12, 나머지 30)", "식", 3, fig="표", final="풀이참조", **FK)
r(18, A1, "POLY.ADD_SUB.LINEAR_COMBO", "5A+2B, −A−4B", "다항식의 덧셈과 뺄셈", "하", S, "(1) 8x²−xy−21y² (2) 2x²−7xy+15y²", "식(소문항별)", 2)
r(19, A2, "POLY.MULT.DISTRIBUTE", "다항식 곱 전개", "다항식의 곱셈", "하", S, "(1) 2x³+3x²−2x (2) 3a³−8a²b+2ab²+5b³ (3) a²−b²−c²+2bc", "식(소문항별)", 3)
r(20, A2, "POLY.MULT.CUBIC_FORMULA", "곱셈공식 전개", "곱셈공식", "하", S, "(1) a²+4b²+9c²−4ab−12bc+6ca (2) x³+15x²y+75xy²+125y³ (3) 8x³−36x²y+54xy²−27y³ (4) a³+27b³ (5) 64x³−1", "식(소문항별)", 5)
r(21, A2, "POLY.DIVISION.LONG", "나눗셈 몫·나머지", "다항식의 나눗셈", "하", S, "(1) 몫 2x+1, 나머지 15x+14 (2) 몫 3x³+3x²−2x−2, 나머지 4", "식(소문항별)", 2)
r(22, A1, "POLY.SYSTEM.SOLVE_AB", "연립으로 A, B 구하기", "다항식의 덧셈과 뺄셈", "하", S, "A=2x³−x²+3, B=−x³−x²+5x−2", "식", **CK)
r(23, A2, "POLY.COEFF.FIND_PARAM", "x² 계수 조건 a", "다항식의 곱셈", "하", S, "6")
r(24, A2, "POLY.MULT.GROUPING_FILL", "치환 전개 빈칸", "곱셈공식", "하", S, "b+d, b+d, b²+2bd+d² (결과 a²−b²+c²−d²+2ac−2bd)", "빈칸")
r(25, A2, "POLY.MULT_FORMULA.IRRATIONAL_VALUE", "x=√2+1, y=√2−1 값", "곱셈공식의 변형", "하", S, "(1) 10√2 (2) 14", "값(소문항별)", 2)
r(26, A2, "POLY.MULT_FORMULA.SYMMETRIC_VALUE", "대칭식 값", "곱셈공식의 변형", "하", S, "(1) 13 (2) 5", "값(소문항별)", 2)
r(27, A2, "POLY.VOLUME.CUBE_WITH_HOLES", "구멍 뚫린 정육면체 부피", "곱셈공식", "중", S, "27x+27", "식", fig="그림", d=M, i=M, trap="중앙 x³ 중복 제거")
r(28, A2, "POLY.DIVISION.FIND_DIVISOR", "몫·나머지로 나누는 식(서술형)", "다항식의 나눗셈", "중하", D, "x²+x−1", "식")
r(29, A2, "POLY.MULT.SUBSTITUTION", "치환 전개", "곱셈공식", "중하", S, "(1) x⁴+x²+1 (2) x⁴+8x³+14x²−8x−15", "식(소문항별)", 2, c=M)
r(30, A2, "POLY.MULT_FORMULA.CUBOID_DIAGONAL", "직육면체 대각선 길이(서술형)", "곱셈공식의 변형", "중하", D, "5√2", fig="그림")
r(31, A2, "POLY.DIVISION.REDUCE_BY_ROOT_EQ", "x²+x−1=0일 때 식의 값", "다항식의 나눗셈", "중", S, "7", c=M, i=M)
r(32, A3, "IDENTITY.RECOGNIZE", "항등식 찾기", "항등식", "하", S, "(2), (4)", "보기")
r(33, A5, "FACTOR.QUADRATIC.PREP", "이차식 인수분해(준비)", "인수분해", "하", S, "(1) (x−2)² (2) (x−y)(x−2y) (3) (3x+2y)(3x−2y) (4) (x+2y)(3x−5y)", "식(소문항별)", 4)
r(34, A3, "IDENTITY.UNDETERMINED_COEFF", "미정계수법(예제)", "항등식;미정계수법", "하", S, "a=1, b=−2, c=0")
r(35, A3, "IDENTITY.UNDETERMINED_COEFF", "미정계수법", "항등식;미정계수법", "하", S, "(1) a=3, b=2, c=3 (2) a=−3, b=2, c=1", "값(소문항별)", 2)
r(36, A3, "IDENTITY.CALENDAR_EXPLAIN", "달력 대각선 곱의 차 설명(활동)", "항등식", "하", ACT, "(a+1)(a+7)−a(a+8)=7", "서술")
r(37, A4, "REMAINDER_THM.LINEAR", "일차식으로 나눈 나머지", "나머지정리", "하", S, "(1) 11 (2) −55 (3) 5", "값(소문항별)", 3)
r(38, A4, "REMAINDER_THM.GENERAL_LINEAR.PROOF", "ax+b로 나눈 나머지 설명", "나머지정리", "하", PRF, "P(x)=(ax+b)Q(x)+R에 x=−b/a 대입 → R=P(−b/a)", "증명")
r(39, A4, "REMAINDER_THM.GENERAL_LINEAR", "2x+1, 3x−2로 나눈 나머지", "나머지정리", "하", S, "(1) −5/8 (2) 5/27", "값(소문항별)", 2)
r(40, A4, "REMAINDER_THM.QUADRATIC_DIVISOR", "이차식으로 나눈 나머지(예제)", "나머지정리", "중하", S, "x−1", "식")
r(41, A4, "REMAINDER_THM.QUADRATIC_DIVISOR", "이차식으로 나눈 나머지", "나머지정리", "중하", S, "−2x−2", "식")
r(42, A4, "REMAINDER_THM.LARGE_NUMBERS", "큰 수 나머지 설명(탐구)", "나머지정리", "중하", ACT, "1) 1+1=2 2) 1+(−1)=0 → 나누어떨어짐", "서술", 2, i=M)
r(43, A4, "FACTOR_THM.FIND_PARAM", "인수정리로 a(예제)", "인수정리", "하", S, "−2")
r(44, A4, "FACTOR_THM.FIND_PARAM", "인수정리로 a", "인수정리", "하", S, "(1) −8 (2) −12", "값(소문항별)", 2)
r(45, A4, "FACTOR_THM.QUADRATIC_DIVISOR", "(x−1)(x+5)로 나누어떨어질 a, b", "인수정리", "하", S, "a=9, b=−6")
r(46, A4, "SYNTHETIC_DIVISION.BASIC", "조립제법 몫·나머지", "조립제법", "하", S, "(1) 몫 x²−4x−3, 나머지 3 (2) 몫 2x²−6x+8, 나머지 −4", "식(소문항별)", 2)
r(47, A4, "SYNTHETIC_DIVISION.NONMONIC", "2x−1로 조립제법(예제)", "조립제법", "중하", S, "몫 x²+1, 나머지 2", "식", trap="몫을 2로 나눔")
r(48, A4, "SYNTHETIC_DIVISION.NONMONIC", "3x−2, 2x+1로 조립제법", "조립제법", "중하", S, "(1) 몫 x²+2x+3, 나머지 −4 (2) 몫 x²−3x+2, 나머지 −3", "식(소문항별)", 2)
r(49, A5, "FACTOR.FORMULA.SQUARE_CUBE", "공식으로 인수분해(예제)", "인수분해 공식", "하", S, "(1) (x+y+2z)² (2) (x−3)³", "식(소문항별)", 2)
r(50, A5, "FACTOR.FORMULA.SQUARE_CUBE", "공식으로 인수분해", "인수분해 공식", "하", S, "(1) (4x+1)³ (2) (x−2y)³ (3) (x+4y)(x²−4xy+16y²) (4) (x−3)(x²+3x+9)", "식(소문항별)", 4)
r(51, A5, "FACTOR.SUBSTITUTION.COMMON_PART", "공통부분 치환(예제)", "인수분해", "중하", S, "(x−1)(x−2)(x²−3x+5)", "식")
r(52, A5, "FACTOR.SUBSTITUTION.COMMON_PART", "공통부분 치환", "인수분해", "중하", S, "x(x+5)(x²+5x+10)", "식")
r(53, A5, "FACTOR.QUARTIC.BIQUADRATIC", "복이차식(예제)", "인수분해", "중하", S, "(1) (x²+3)(x+1)(x−1) (2) (x²+x+1)(x²−x+1)", "식(소문항별)", 2)
r(54, A5, "FACTOR.QUARTIC.BIQUADRATIC", "복이차식", "인수분해", "중", S, "(1) (x+1)(x−1)(x+2)(x−2) (2) (x²+3x−1)(x²−3x−1)", "식(소문항별)", 2, i=M, trap="A²−B² 꼴 변형")
r(55, A5, "FACTOR.FACTOR_THM.CUBIC", "인수정리 인수분해(예제)", "인수분해;인수정리", "하", S, "(x−1)(2x²+x+6)", "식")
r(56, A5, "FACTOR.FACTOR_THM.CUBIC_QUARTIC", "인수정리 인수분해", "인수분해;인수정리", "중하", S, "(1) (x−1)²(x+4) (2) (x+1)²(x−2)(x+3)", "식(소문항별)", 2, c=M)
r(57, A5, "FACTOR.DIVISIBILITY_DIAGRAM", "그림 다항식 곱 가능 여부(탐구)", "인수분해", "중", ACT, "[그림 1] 가능((x−1)² 인수), [그림 2] 불가능(x² 인수 아님)", "서술", 2, fig="그림", final="풀이참조", **FK)
r(58, A5, "FACTOR.VOLUME_MODEL.CUBE", "입체 부피로 인수분해 공식 확인(탐구)", "인수분해 공식", "하", ACT, "풀이참조((a+b)³=a³+3a²b+3ab²+b³ 등)", "서술", fig="그림", final="풀이참조", **FK)
r(59, A3, "IDENTITY.UNDETERMINED_COEFF.SHIFTED", "(x−1) 꼴 항등식 a, b, c", "항등식", "하", S, "a=1, b=5, c=9")
r(60, A4, "REMAINDER_THM.GENERAL_LINEAR", "나머지 구하기", "나머지정리", "하", S, "(1) −8 (2) 4/3", "값(소문항별)", 2)
r(61, A4, "FACTOR_THM.FIND_PARAM", "x−2로 나누어떨어질 a", "인수정리", "하", S, "−7")
r(62, A5, "FACTOR.FORMULA.SQUARE_CUBE", "공식 인수분해", "인수분해 공식", "하", S, "(1) (x+2y−3z)² (2) (2x−1)³ (3) (3x+4y)(9x²−12xy+16y²)", "식(소문항별)", 3)
r(63, A5, "FACTOR.MIXED", "치환·복이차·인수정리 인수분해", "인수분해", "중하", S, "(1) (x+y−1)(x+y−2) (2) (x²−3)(x+2)(x−2) (3) (x−1)(2x−1)(x+3)", "식(소문항별)", 3)
r(64, A3, "IDENTITY.SHIFTED_BASIS.EVAL", "(x+1) 거듭제곱 항등식 계수 결합", "항등식", "중하", S, "−8", c=M)
r(65, A3, "IDENTITY.SUBSTITUTE_ROOTS", "항등식 대입법 a, b", "항등식", "하", S, "a=5, b=−5", **CK)
r(66, A4, "REMAINDER_THM.FIND_PARAM_THEN_REMAINDER", "나머지 조건으로 a 후 나머지(서술형)", "나머지정리", "하", D, "7")
r(67, A5, "FACTOR.SUBSTITUTION.PAIRED_PRODUCT", "네 일차식 곱·복이차식 인수분해", "인수분해", "중", S, "(1) (x²+2x−2)(x²+2x−9) (2) (x²+xy+2y²)(x²−xy+2y²)", "식(소문항별)", 2, c=M, i=M)
r(68, A4, "FACTOR_THM.DOUBLE_ROOT", "(x−1)²으로 나누어떨어질 a, b", "인수정리;조립제법", "중", S, "a=−2, b=1", i=M)
r(69, A5, "FACTOR.TWO_VARIABLE.FILL", "두 문자 인수분해 빈칸", "인수분해", "중하", S, "y²+3y+2, y+2, x−y−2 (결과 (x−y−1)(x−y−2))", "빈칸")
r(70, A2, "POLY.MULT_FORMULA.SUM_SQUARES_DIFF", "a²+b²+c²−ab−bc−ca 값", "곱셈공식의 변형", "중하", S, "28")
r(71, A4, "REMAINDER_THM.QUOTIENT_TRANSFORM", "xP(x)를 x−a로 나눈 몫·나머지", "나머지정리", "중", S, "몫 xQ(x)+R, 나머지 aR", "식", final="몫 xQ(x)+R, 나머지 aR", i=M, chk="독립풀이 일치(파일 빠른 정답은 나머지 aR만 표기)")
r(72, A5, "FACTOR.VOLUME.WATER_TRANSFER", "물 옮겨 담은 수면 높이(서술형)", "인수분해", "중", D, "h=x+5", fig="그림", **FK)
r(73, A5, "FACTOR.NUMERIC_EVALUATION", "인수분해로 수 계산", "인수분해", "중하", S, "381", trap="20 대입")
r(74, A1, "POLY.SYSTEM.SOLVE_AB", "A+B, A−B로 B−3A", "다항식의 덧셈과 뺄셈", "하", S, "−17x³−5x+21", "식")
r(75, A2, "POLY.MULT_FORMULA.RECIPROCAL", "x+1/x, x³+1/x³", "곱셈공식의 변형", "하", S, "(1) 4 (2) 52", "값(소문항별)", 2)
r(76, A2, "POLY.DIVISION.RECONSTRUCT", "몫·나머지로 A 복원", "다항식의 나눗셈", "하", S, "x³+3x²+6x+3", "식")
r(77, A2, "POLY.DIVISION.FIND_P_Q_INTEGER", "나머지 조건으로 P, Q", "다항식의 나눗셈", "상", S, "P(x)=x³+3, Q(x)=x²+2", "식", final="P(x)=x³+3, Q(x)=x²+2", c=M, i=H, chk="독립풀이 일치(파일 빠른 정답 표기는 Q(x)=x²+2, 해설에 P(x)=x³+3)")
r(78, A3, "IDENTITY.EVEN_COEFF_SUM", "짝수 차수 계수의 합", "항등식", "중하", S, "−14", trap="x=±1 대입")
r(79, A4, "REMAINDER_THM.EQUAL_REMAINDERS", "두 나머지 같을 a", "나머지정리", "하", S, "a=7")
r(80, A4, "REMAINDER_THM.LINEAR_COMBINATION", "3P+2Q 나머지", "나머지정리", "하", S, "18")
r(81, A4, "REMAINDER_THM.SQUARE_DIVISOR", "(x−1)²으로 나눈 나머지 R(10)", "나머지정리", "중", S, "180", c=M, i=M)
r(82, A4, "FACTOR_THM.QUADRATIC_DIVISOR", "x²−3x+2로 나누어떨어질 a, b", "인수정리", "하", S, "a=−7, b=19")
r(83, A5, "FACTOR.MIXED.ADVANCED", "치환·차의 제곱 인수분해", "인수분해", "중", S, "(1) (x+3)(x−1)(x+5)(x−3) (2) (x+y+z)(x+y−z)(x−y+z)(−x+y+z)", "식(소문항별)", 2, c=M, i=M)
r(84, A5, "FACTOR.PERFECT_SQUARE.FIND_CONST", "완전제곱 되게 하는 a", "인수분해", "중하", S, "a=16")
r(85, A5, "FACTOR.TRIANGLE_SHAPE", "인수분해로 삼각형 모양", "인수분해", "중하", MC, "⑤", "선택지번호", final="⑤ (빗변 c인 직각삼각형)", trap="a+c>0")
r(86, A5, "FACTOR.NUMERIC_EVALUATION", "f(102) 값", "인수분해;인수정리", "중하", S, "1100000")
r(87, A5, "FACTOR.INTEGER_PAIRS.COUNT", "(x+m)(x−n) 꼴 개수", "인수분해", "중", S, "9", **CK)
r(88, A2, "POLY.COEFF.PRODUCT_SERIES", "전개식 x² 계수(서술형)", "다항식의 곱셈", "하", D, "10")
r(89, A4, "REMAINDER_THM.QUOTIENT_VALUE", "몫 Q(x)를 x−1로 나눈 나머지(서술형)", "나머지정리", "중", D, "1", final="Q(1)=1", i=M)
r(90, A4, "FACTOR_THM.CUBIC_FROM_VALUES", "P(1)=1, P(2)=2, P(3)=3인 삼차식 나머지(서술형)", "인수정리;나머지정리", "중", D, "29", i=M, trap="P(x)−x 구성")
r(91, A5, "FACTOR.NUMERIC_EVALUATION", "97 대입 완전세제곱(서술형)", "인수분해 공식", "하", D, "1000000")
r(92, A2, "POLY.MULT.GENERATING_FUNCTION", "카드 합 경우의 수를 다항식 곱으로(활동)", "다항식의 곱셈", "중하", ACT, "풀이참조((x+x²+x³)(2x+x²) 등 계수로 경우의 수)", "서술", fig="그림", final="풀이참조", **FK)
for i in range(10): build(f"Batch{496+i}", ROWS[i*10:(i+1)*10], 13368+i*10)
print(len(ROWS))
