from cfgy2 import *
import cfgy2, builder, bisect
SQ = hashlib.sha256(open(OUT+'h43/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y43.json'))
setup(QID="A02443", SRC="1u3ae5sePlk2npohinKFuNLXk4MHXSASJ", SHA=SQ, TAG="YMJH03", N=132, SUBJ="수학(상)", SEC="S03A",
      FNAME="03 도형의 방정식(지학사) 132제.hwp", UNIT="Ⅲ. 도형의 방정식", BIG="Ⅲ. 도형의 방정식", EXAM="3. 도형의 방정식 132제", MID="도형의 방정식")
cfgy2.P.update(BOOK="지학사 수학(상)", GRADE="고1", MEMO_X="34·35번: 편집본에서 지렛대 활동 2)의 본문이 35번(직선 단원 준비 '일차함수 그래프 그리기')에 붙어 추출됨 — 빠른 정답 34번이 활동 1)·2) 전체 정답, 35번 정답(풀이참조)은 그래프 그리기 문항; ")
B = [1, 12, 24, 35, 46, 52, 55, 64, 75, 84, 93, 102, 111, 121]
MIDS = ["두 점 사이의 거리", "선분의 내분점과 외분점", "평면좌표(중단원 마무리)", "직선의 방정식", "두 직선의 평행과 수직", "점과 직선 사이의 거리", "직선의 방정식(중단원 마무리)",
        "원의 방정식", "원과 직선의 위치 관계", "원의 방정식(중단원 마무리)", "평행이동", "대칭이동", "도형의 이동(중단원 마무리)", "도형의 방정식 종합(대단원 마무리)"]
SECS = [f"S03{chr(65+j)}" for j in range(len(B))]
for s, mid in zip(SECS, MIDS): builder.SECTIONS[s] = ("3. 도형의 방정식 132제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, DRW, MC = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "서술형(그래프 그리기)", "객관식(5지선다)"
P1, P2, L1, L2, L3, C1, C2, T1, T2 = "두 점 사이의 거리", "선분의 내분점과 외분점", "직선의 방정식", "두 직선의 평행과 수직", "점과 직선 사이의 거리", "원의 방정식", "원과 직선의 위치 관계", "평행이동", "대칭이동"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = SECS[bisect.bisect_right(B, q) - 1]
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·좌표 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건·보기(수식/표 객체) 본문 미추출 — 파일 정답 기준")
OP = dict(review="REVIEW-개방형", chk="개방형·발표/토론 활동 — 정답 풀이참조")
r(1, P1, "COORD.READ_POINTS", "좌표평면 위 점의 좌표 읽기(준비)", "좌표", "하", S, "A(2,1), B(−3,2), C(4,−3), D(−1,1)", "좌표", fig="그림", **FK)
r(2, P1, "SEGMENT.MIDPOINT_LENGTH", "중점의 중점과 선분 길이(준비)", "선분의 중점", "하", S, "MN=2", fig="그림", chk="독립풀이 일치(MB=4, MN=2)")
r(3, P1, "PYTHAGORAS.RIGHT_TRIANGLE", "직각삼각형 변의 길이(준비)", "피타고라스 정리", "하", S, "(1) 5 (2) 4√3", "값(소문항별)", 2, fig="그림", **FK)
r(4, P1, "DISTANCE.TAXICAB_VS_EUCLID.ACTIVITY", "도로망 최단거리와 직선거리(활동)", "두 점 사이의 거리;피타고라스 정리", "하", ACT, "풀이참조", "서술", 3, fig="그림", final="풀이참조", **OP)
r(5, P1, "DISTANCE.NUMBER_LINE", "수직선 위 두 점 사이 거리", "두 점 사이의 거리", "하", S, "(1) 5 (2) 2", "값(소문항별)", 2)
r(6, P1, "DISTANCE.PLANE.BASIC", "좌표평면 두 점 사이 거리", "두 점 사이의 거리", "하", S, "(1) √13 (2) 5 (3) 13 (4) 2√5", "값(소문항별)", 4)
r(7, P1, "DISTANCE.TRIANGLE_SHAPE.ISOSCELES", "이등변삼각형 판정(예제)", "두 점 사이의 거리;삼각형의 모양", "하", S, "AB=BC=5√2인 이등변삼각형", "서술")
r(8, P1, "DISTANCE.TRIANGLE_SHAPE.RIGHT", "직각삼각형 판정", "두 점 사이의 거리;삼각형의 모양", "하", S, "∠A=90°인 직각삼각형", "서술", chk="독립풀이 일치(AB²=5, AC²=20, BC²=25)")
r(9, P1, "DISTANCE.PROOF.PAPPUS_MEDIAN", "중선정리 좌표 증명(예제)", "두 점 사이의 거리;좌표를 이용한 증명", "중하", PRF, "M을 원점, BC를 x축으로 잡아 전개 → 성립", "증명", final="풀이참조", i=M)
r(10, P1, "DISTANCE.PROOF.RECTANGLE_BRITISH_FLAG", "직사각형 PA²+PC²=PB²+PD² 증명", "두 점 사이의 거리;좌표를 이용한 증명", "중하", PRF, "꼭짓점을 좌표축 위에 두고 전개 → 성립", "증명", final="풀이참조", i=M)
r(11, P1, "DISTANCE.CONTEXT.SIGNATURE", "전자 서명 획 끝점 거리(활동)", "두 점 사이의 거리", "하", ACT, "(1) AB=2, BC=2√2, EG=2√5 (2) 예: AB=6, CD=3√2 (3) 획의 꺾이는 방향 등", "값+서술", 3, fig="그림", **FK)
r(12, P2, "SECTION.RATIO.SEGMENT_POINTS", "6등분 나무토막의 비(탐구)", "선분의 내분점;선분의 외분점", "하", ACT, "1) 1:5 2) E 3) G", "값+점", 3, fig="그림", chk="독립풀이 일치(A=0,…,G=6 단위)", review="REVIEW-그림판독")
r(13, P2, "SECTION.INTERNAL.NUMBER_LINE", "수직선 내분점·중점", "선분의 내분점", "하", S, "(1) 0 (2) 2", "값(소문항별)", 2)
r(14, P2, "SECTION.EXTERNAL.NUMBER_LINE", "수직선 외분점", "선분의 외분점", "하", S, "(1) 10 (2) −5", "값(소문항별)", 2)
r(15, P2, "SECTION.INTERNAL.MEETING_POINT", "마주 걷는 두 사람 만난 점의 내분비(활동)", "선분의 내분점", "하", ACT, "(1) m=1, n=1 (2) m=2, n=1", "값(소문항별)", 2, trap="속력비=내분비")
r(16, P2, "SECTION.INTERNAL.STAIRS_CONTEXT", "책장 계단 내분점(탐구)", "선분의 내분점", "중하", ACT, "1) G 2) I(4, 4) 3) AI:IC=2:1", "점+좌표", 3, fig="그림", **FK)
r(17, P2, "SECTION.MIXED.PLANE", "좌표평면 내분·중점·외분", "선분의 내분점;선분의 외분점", "하", S, "(1) (−2/3, 13/3) (2) (1, 6) (3) (16, 21) (4) (−14, −9)", "좌표(소문항별)", 4)
r(18, P2, "SECTION.EXTERNAL.EXTENSION_RATIO", "연장선 위 2AB=3BC인 점", "선분의 외분점", "중하", S, "(−7, −4)", "좌표", d=M, trap="C는 A를 5:2로 외분(B 너머)")
r(19, P2, "SECTION.CENTROID.DERIVE", "무게중심 좌표 유도(예제)", "삼각형의 무게중심", "하", D, "((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3)", "좌표")
r(20, P2, "SECTION.CENTROID.BASIC", "무게중심 좌표", "삼각형의 무게중심", "하", S, "(3, 2)", "좌표")
r(21, P2, "SECTION.CENTROID.FIND_VERTEX_DISTANCE", "무게중심으로 꼭짓점 구해 거리", "삼각형의 무게중심;두 점 사이의 거리", "하", S, "4√2", chk="독립풀이 일치(B(−3, 6), G(1, 2))")
r(22, P2, "SECTION.CENTROID.MIDPOINT_TRIANGLE", "중점삼각형 무게중심 일치(토론)", "삼각형의 무게중심;선분의 중점", "중하", D, "두 무게중심 모두 ((a+c+e)/3, (b+d+f)/3)로 일치", "서술", i=M)
r(23, P2, "SECTION.CENTROID.CONTEXT_RUNNING", "달리기 자세 삼각형 무게중심(활동)", "삼각형의 무게중심", "하", ACT, "풀이참조", "서술", 2, fig="그림", final="풀이참조", **OP)
r(24, P1, "DISTANCE.NUMBER_LINE", "수직선 두 점 거리", "두 점 사이의 거리", "하", S, "(1) 5 (2) 3", "값(소문항별)", 2)
r(25, P1, "DISTANCE.PLANE.BASIC", "좌표평면 두 점 거리", "두 점 사이의 거리", "하", S, "(1) 3√2 (2) √41 (3) √13 (4) 5", "값(소문항별)", 4)
r(26, P2, "SECTION.MIXED.NUMBER_LINE", "수직선 3:1 내분·외분점", "선분의 내분점;선분의 외분점", "하", S, "P(0), Q(3)", "값")
r(27, P2, "SECTION.MIXED.PLANE", "좌표평면 3:1 내분·1:3 외분점", "선분의 내분점;선분의 외분점", "하", S, "P(7/4, 0), Q(−9/2, 5)", "좌표")
r(28, P2, "SECTION.MIXED.DISTANCE", "내분점·외분점 사이 거리", "선분의 내분점;선분의 외분점;두 점 사이의 거리", "하", S, "8√2", chk="독립풀이 일치(P(1,2), Q(−7,10))")
r(29, P1, "DISTANCE.EQUIDISTANT.ON_AXIS", "x축 위 등거리 점", "두 점 사이의 거리", "하", S, "(2, 0)", "좌표")
r(30, P2, "SECTION.NUMBER_LINE.EQUAL_SPACING", "등간격 점에서 내분·외분점 찾기", "선분의 내분점;선분의 외분점", "하", S, "(가) D (나) H", "점", fig="그림", chk="독립풀이 일치(C=3, G=7 → 4, 8)")
r(31, P2, "SECTION.PARALLELOGRAM.DIAGONAL_MIDPOINT", "평행사변형 대각선 중점으로 a, b", "선분의 중점;평행사변형", "하", S, "a=1, b=2", trap="꼭짓점 순서 ABCD")
r(32, P1, "DISTANCE.CONTEXT.DIRECTIONS", "방위 이동 후 두 지점 직선거리", "두 점 사이의 거리", "하", S, "√37 km", c=M, chk="독립풀이 일치(병원(4,1), 소방서(−2,2))")
r(33, P1, "DISTANCE.TAXICAB.ACTIVITY", "택시캡 거리와 학교 배정(활동)", "두 점 사이의 거리;택시 거리", "중하", ACT, "1) 5, 7 2) 풀이참조", "값+서술", 2, fig="그림", i=M, **FK)
r(34, P2, "SECTION.INTERNAL.LEVER_BALANCE", "지렛대·삼각형 받침점(활동)", "선분의 내분점;삼각형의 무게중심", "중하", ACT, "1) 6 g 쪽 끝에서 5 cm 2) ① I는 AB를 2:1로 내분 ② H는 AC를 3:1로 내분 ③ 풀이참조", "서술+비", 2, fig="그림", final="(1) 풀이참조 (2) ① 2:1 내분점 ② 3:1 내분점 ③ 풀이참조", chk="독립풀이 일치(1) 20 cm를 2:6으로 → 6 g에서 5 cm, (2) 무게 역비) — 활동 2)의 본문은 35번에 붙어 추출", review="REVIEW-문항경계")
r(35, L1, "LINE.GRAPH.LINEAR_FUNCTION", "일차함수 그래프 그리기(준비)", "일차함수의 그래프", "하", DRW, "풀이참조(y절편·기울기 이용)", "그래프", 2, fig="그래프", final="풀이참조", review="REVIEW-문항경계", chk="본문에 직전 활동 2) 텍스트가 붙어 추출 — 실제 문항은 'y=2x+1, y=−x−4 그래프 그리기'")
r(36, L1, "LINE.PARALLEL.SAME_SLOPE", "평행한 일차함수 그래프 찾기(준비)", "일차함수의 그래프;두 직선의 평행", "하", S, "(1), (2)", "번호")
r(37, L1, "LINE.SYSTEM.GRAPH_SOLVE", "연립일차방정식 그래프 풀이(준비)", "일차함수의 그래프;연립방정식", "하", DRW, "x=1, y=1 (두 직선 교점)", "그래프", fig="그래프", final="풀이참조")
r(38, L1, "LINE.SLOPE.CABLE_CAR", "케이블카 기둥 기울기(탐구)", "직선의 기울기", "하", ACT, "1) 100, 150, 250 2) 1/2, 3/2 3) 5/6", "값", 3, fig="그림", **FK)
r(39, L1, "LINE.EQUATION.POINT_SLOPE", "점·기울기 직선", "직선의 방정식", "하", S, "(1) y=2x−4 (2) y=−x/2", "식(소문항별)", 2)
r(40, L1, "LINE.EQUATION.TWO_POINTS", "두 점 지나는 직선", "직선의 방정식", "하", S, "(1) y=x+3 (2) y=−2", "식(소문항별)", 2)
r(41, L1, "LINE.EQUATION.TWO_POINTS", "두 점 지나는 직선(수직선 포함)", "직선의 방정식", "하", S, "(1) x=2 (2) y=−x+1", "식(소문항별)", 2, trap="x좌표 같으면 x=k")
r(42, L1, "LINE.INTERCEPT_FORM.PROOF", "절편형 x/a+y/b=1 설명", "직선의 방정식", "하", PRF, "두 점 (a,0),(0,b) 지나는 직선 정리 → x/a+y/b=1", "증명", final="풀이참조")
r(43, L1, "LINE.GRAPH.DRAW", "일차방정식 직선 그리기", "직선의 방정식", "하", DRW, "생략(절편 이용)", "그래프", 4, fig="그래프", final="생략")
r(44, L1, "LINE.THROUGH_INTERSECTION.SLOPE", "두 직선 교점 지나는 직선", "직선의 방정식;연립방정식", "하", S, "y=x/2−3/2", "식", chk="독립풀이 일치(교점 (1, −1))")
r(45, L1, "LINE.PENCIL.DISCUSSION", "k(…)+(…)=0 꼴 직선과 두 직선 관계(토론)", "직선의 방정식;정점", "중하", D, "두 직선의 교점 (−1, 1)을 지나는 직선(단, 한 직선 제외)", "서술", 2, final="풀이참조", i=M, **OP)
r(46, L2, "LINE.PARALLEL_PERP.RAILWAY", "기찻길 평행·수직 판단(탐구)", "두 직선의 평행과 수직", "하", ACT, "1) 평행 2) 수직 3) 풀이참조", "서술", 3, fig="그림", **FK)
r(47, L2, "LINE.PARALLEL.THROUGH_POINT", "평행한 직선(예제)", "두 직선의 평행", "하", S, "y=2x−3", "식")
r(48, L2, "LINE.PARALLEL.THROUGH_POINT", "평행한 직선", "두 직선의 평행", "하", S, "(1) y=−x (2) y=x/2+3/2 (3) y=1 (4) x=−1", "식(소문항별)", 4)
r(49, L2, "LINE.PERPENDICULAR.THROUGH_POINT", "수직인 직선(예제)", "두 직선의 수직", "하", S, "y=2x", "식")
r(50, L2, "LINE.PERPENDICULAR.THROUGH_POINT", "수직인 직선", "두 직선의 수직", "하", S, "(1) y=−x/4−7/4 (2) y=x/2−5/2 (3) x=1 (4) y=−2", "식(소문항별)", 4)
r(51, L2, "LINE.GENERAL_FORM.PARALLEL_PERP_CONDITIONS", "일반형 평행·수직 조건과 k(탐구)", "두 직선의 평행과 수직", "중하", ACT, "(1) ① a'/a=b'/b≠c'/c ② −2, 2 (2) ① aa'+bb'=0 ② 0, 4", "식+값", 4, i=M, chk="독립풀이 (1)② k=±2 일치; (2)② 직선 식 본문 잘림 — 파일 정답 기준", review="REVIEW-조건미추출")
r(52, L3, "LINE.PERPENDICULAR.PIPE_CONTEXT", "수도관 최단 지점과 직선 관계(탐구)", "점과 직선 사이의 거리;두 직선의 수직", "하", ACT, "1) B 2) 수직", "점+서술", 2, fig="그림", **FK)
r(53, L3, "DIST_POINT_LINE.BASIC", "점과 직선 사이 거리", "점과 직선 사이의 거리", "하", S, "(1) 3 (2) √2", "값(소문항별)", 2)
r(54, L3, "DIST_POINT_LINE.FIND_LINE", "원점 거리 √2, (1,1) 지나는 직선", "점과 직선 사이의 거리", "중하", S, "x+y−2=0", "식", c=M, trap="|OP|=√2이므로 OP에 수직인 직선 하나뿐")
r(55, L1, "LINE.EQUATION.MIXED", "직선의 방정식 종합", "직선의 방정식", "하", S, "(1) y=3x−7 (2) y=4x−5 (3) x=3", "식(소문항별)", 3)
r(56, L2, "LINE.PARALLEL_PERP.JUDGE", "두 직선 평행·수직 판정", "두 직선의 평행과 수직", "하", S, "(1) 평행 (2) 수직", "서술", 2)
r(57, L3, "DIST_POINT_LINE.BASIC", "점과 직선 사이 거리", "점과 직선 사이의 거리", "하", S, "(1) 3√2/2 (2) 1/5", "값(소문항별)", 2)
r(58, L1, "LINE.POINT_ON_LINE.PARAM", "직선 위 점 (a, −a+1)", "직선의 방정식", "하", S, "2", chk="독립풀이 일치(AB: y=x−3)")
r(59, L2, "LINE.PERP_BISECTOR", "선분의 수직이등분선", "두 직선의 수직;선분의 중점", "하", S, "y=x−3", "식")
r(60, L2, "LINE.PERPENDICULAR.FIND_PARAM", "두 직선 수직일 k 모두", "두 직선의 수직", "중하", S, "−1, 1", c=M, chk="독립풀이 일치((k−1)(2k+2)=0)")
r(61, L3, "DIST_POINT_LINE.PARALLEL_LINES", "평행한 두 직선 사이 거리", "점과 직선 사이의 거리", "하", S, "2")
r(62, L1, "LINE.EQUATION.RECTANGLE_FIGURE", "합동 직사각형 꼭짓점 지나는 직선", "직선의 방정식", "중하", S, "y=−x/2+5/2", "식", fig="그림", **FK)
r(63, L3, "DIST_POINT_LINE.FIXED_POINT", "정점과 직선 사이 거리", "점과 직선 사이의 거리;정점", "중하", S, "1", combo="복합(정점+점과 직선 거리)", c=M, i=M, chk="독립풀이 일치(정점 A(−1, 0))")
r(64, C1, "INCIRCLE.TANGENT_LENGTH", "내접원 접선 길이(준비)", "원의 접선의 성질", "하", S, "16", fig="그림", **FK)
r(65, C2, "QUADRATIC_LINE.POSITION", "이차함수 그래프와 직선 위치 관계(준비)", "이차함수와 직선;판별식", "하", S, "(1) a>−1 (2) a=−1 (3) a<−1", "부등식(소문항별)", 3)
r(66, C1, "DISTANCE.PLANE.BASIC", "두 점 사이 거리(준비)", "두 점 사이의 거리", "하", S, "(1) 5 (2) √5 (3) 3√2", "값(소문항별)", 3)
r(67, C1, "CIRCLE.EQUATION.DERIVE_ACTIVITY", "등거리 건물과 원의 방정식(활동)", "원의 방정식", "하", ACT, "x²+y²=25 (풀이참조)", "식", 3, fig="그림", final="풀이참조", **OP)
r(68, C1, "CIRCLE.EQUATION.CENTER_RADIUS", "중심·반지름으로 원의 방정식", "원의 방정식", "하", S, "(1) (x−2)²+(y−1)²=9 (2) x²+y²=4", "식(소문항별)", 2)
r(69, C1, "CIRCLE.READ_CENTER_RADIUS", "표준형에서 중심·반지름", "원의 방정식", "하", S, "(1) (0,0), 3 (2) (1,−2), √5", "좌표+값", 2)
r(70, C1, "CIRCLE.DIAMETER_ENDPOINTS", "지름 양 끝점으로 원(예제)", "원의 방정식;선분의 중점", "하", S, "(x−2)²+(y−3)²=2", "식", chk="독립풀이 일치(본문 '지름의' 누락 표기 — 해설은 지름 양 끝점)")
r(71, C1, "CIRCLE.DIAMETER_ENDPOINTS", "지름 양 끝점으로 원", "원의 방정식;선분의 중점", "하", S, "x²+(y−2)²=5", "식")
r(72, C1, "CIRCLE.GENERAL_FORM.COMPLETE_SQUARE", "일반형 완전제곱 중심·반지름", "원의 방정식", "하", S, "(1) (1,−3), 4 (2) (−1,2), √5", "좌표+값", 2)
r(73, C1, "CIRCLE.GENERAL_FORM.EXISTENCE", "원이 되기 위한 k 범위", "원의 방정식", "하", S, "k<5/4", "부등식", trap="반지름²>0")
r(74, C1, "CIRCLE.APOLLONIUS", "아폴로니오스의 원(PA:PB=2:1)", "원의 방정식;두 점 사이의 거리", "중하", S, "(x−5)²+y²=4", "식", c=M, i=M, final="(x−5)²+y²=4", chk="독립풀이 = 해설 결과 일치(빠른 정답란 공란)")
r(75, C2, "CIRCLE_LINE.HORIZONTAL.COUNT", "원과 y=k 교점 개수(활동)", "원과 직선의 위치 관계", "하", ACT, "1) 2개, 1개, 0개 2) |k|<2: 2개, |k|=2: 1개, |k|>2: 0개", "서술", 2, final="풀이참조")
r(76, C2, "CIRCLE_LINE.INTERSECT.RANGE", "원과 직선 두 점 k 범위(예제)", "원과 직선의 위치 관계", "하", S, "−2√2<k<2√2", "부등식")
r(77, C2, "CIRCLE_LINE.POSITION.THREE_CASES", "원과 직선 위치 관계 세 경우", "원과 직선의 위치 관계", "하", S, "(1) −10<k<10 (2) k=±10 (3) k<−10 또는 k>10", "부등식(소문항별)", 3)
r(78, C2, "TANGENT.GIVEN_SLOPE", "기울기 주어진 접선(평행·수직 포함)", "원의 접선의 방정식;두 직선의 평행과 수직", "하", S, "(1) y=2x±3√5 (2) y=3x±4√10 (3) y=−x±2√2", "식(소문항별)", 3)
r(79, C2, "TANGENT.AT_POINT", "원 위의 점에서 접선", "원의 접선의 방정식", "하", S, "(1) 3x+4y−25=0 (2) 2x−3y−13=0 (3) y=2 (4) x=3", "식(소문항별)", 4)
r(80, C2, "TANGENT.EXTERNAL_POINT", "외부 점에서 접선(예제)", "원의 접선의 방정식", "중하", S, "√2x−y=3√2 또는 √2x+y=3√2", "식", c=M, chk="독립풀이 일치(접점 (2, ±√2))")
r(81, C2, "TANGENT.EXTERNAL_POINT", "외부 점에서 접선", "원의 접선의 방정식", "중하", S, "(1) √3x−y+2=0 또는 √3x+y−2=0 (2) x=2 또는 y=2", "식(소문항별)", 2, c=M, trap="(2) 기울기 없는 접선 x=2")
r(82, C2, "TANGENT.CHORD_OF_CONTACT", "두 접점을 지나는 직선(극선)", "원의 접선의 방정식", "중", S, "y=3x+5", "식", i=M, chk="독립풀이 일치(접점 (x₁,y₁)에서 −3x₁+y₁=5)")
r(83, C2, "CIRCLE_LINE.DISTANCE_CRITERION.ACTIVITY", "중심-직선 거리로 위치 관계 판정(활동)", "원과 직선의 위치 관계;점과 직선 사이의 거리", "하", ACT, "풀이참조", "서술", final="풀이참조", **CK)
r(84, C1, "CIRCLE.GENERAL_FORM.COMPLETE_SQUARE", "일반형 중심·반지름", "원의 방정식", "하", S, "(1, −2), 1", "좌표+값")
r(85, C2, "TANGENT.GIVEN_SLOPE", "기울기 √3인 접선", "원의 접선의 방정식", "하", S, "y=√3x±8", "식")
r(86, C2, "TANGENT.AT_POINT", "원 위의 점에서 접선", "원의 접선의 방정식", "하", S, "x+3y−10=0", "식")
r(87, C1, "CIRCLE.GENERAL_FORM.RADIUS_PARAM", "반지름 √7일 k 모두", "원의 방정식", "하", S, "−3, 2", chk="독립풀이 일치(k²+k+1=7)")
r(88, C1, "CIRCLE.DIAMETER_ENDPOINTS", "원의 중심과 점을 지름 끝점으로", "원의 방정식", "하", S, "(x+2)²+(y+1)²=25", "식")
r(89, C1, "CIRCLE.AREA.MIN_PARAM", "원 넓이 최솟값(a 매개변수)", "원의 방정식;이차함수 최솟값", "중하", S, "5π", c=M, chk="독립풀이 일치(r²=5(a−1)²+5)")
r(90, C2, "CIRCLE_LINE.POSITION.THREE_CASES", "원과 직선 위치 관계 세 경우", "원과 직선의 위치 관계", "하", S, "(1) −2<k<2 (2) k=±2 (3) k<−2 또는 k>2", "부등식(소문항별)", 3)
r(91, C2, "TANGENT.EXTERNAL_POINT.AREA", "두 접선과 y축 사이 넓이", "원의 접선의 방정식", "중", S, "4√3/3", c=M, chk="독립풀이 일치(기울기 ±1/√3, y절편 ±2/√3)")
r(92, C2, "CIRCLE.MAX_TRIANGLE_AREA.POINT", "원 위 점과 삼각형 넓이 최대", "점과 직선 사이의 거리;원의 방정식", "중", S, "(−2√5/5, √5/5)", "좌표", fig="그림", i=M, chk="독립풀이 일치(AB: 2x−y−5=0, 법선 반대 방향 단위점)")
r(93, T2, "SYMMETRY.FIGURE_COMPLETE", "선대칭·점대칭 도형 완성(준비)", "선대칭도형;점대칭도형", "하", DRW, "풀이참조", "그림", 2, fig="그림", final="풀이참조", review="REVIEW-그림판독")
r(94, T1, "TRANSLATION.LINEAR_FUNCTION.Y_SHIFT", "일차함수 y축 방향 평행이동(준비)", "일차함수의 평행이동", "하", S, "(1) 2 (2) −2", "값(소문항별)", 2)
r(95, T1, "TRANSLATION.QUADRATIC.VERTEX", "이차함수 평행이동(준비)", "이차함수의 평행이동", "하", S, "2, 1")
r(96, T1, "TRANSLATION.CONTEXT.LONGITUDE_LATITUDE", "경도·위도로 도시 이동 표현(활동)", "점의 평행이동", "하", ACT, "예: 베이징→런던 서쪽 116도, 북쪽 11도", "서술", fig="그림", **FK)
r(97, T1, "TRANSLATION.POINT", "점의 평행이동", "점의 평행이동", "하", S, "(1) (2,0) (2) (5,−5) (3) (3,2) (4) (1,−6)", "좌표(소문항별)", 4)
r(98, T1, "TRANSLATION.POINT.REVERSE", "평행이동 전 점 찾기", "점의 평행이동", "하", S, "(2, 1)", "좌표")
r(99, T1, "TRANSLATION.CIRCLE", "원의 평행이동(예제)", "도형의 평행이동", "하", S, "(x−3)²+(y−4)²=1", "식")
r(100, T1, "TRANSLATION.LINE_PARABOLA", "직선·포물선 평행이동", "도형의 평행이동", "하", S, "(1) 2x−3y+12=0 (2) y=x²−2x−1", "식(소문항별)", 2, trap="x 대신 x+1, y 대신 y−2")
r(101, T1, "TRANSLATION.CIRCLE.TO_ORIGIN", "원을 원점 중심으로 옮기는 a, b, r", "도형의 평행이동;원의 방정식", "하", S, "a=2, b=−4, r=3")
r(102, T2, "SYMMETRY.FLAGS.ACTIVITY", "국기의 선대칭·점대칭(활동)", "대칭이동", "하", ACT, "풀이참조", "서술", fig="그림", final="풀이참조", **OP)
r(103, T2, "REFLECTION.POINT.AXES", "점의 x축·y축 대칭", "점의 대칭이동", "하", S, "(1) (−3,−4), (3,4) (2) (−4,3), (4,−3)", "좌표(소문항별)", 2)
r(104, T2, "REFLECTION.POINT.ORIGIN_PARAM", "원점 대칭으로 a, b", "점의 대칭이동", "하", S, "a=3, b=−4")
r(105, T2, "REFLECTION.FIGURE.AXES_ORIGIN", "직선·원의 x축·y축·원점 대칭(예제)", "도형의 대칭이동", "하", S, "(1) x+2y+3=0, x+2y−3=0, x−2y−3=0 (2) (x−1)²+(y−2)²=4, (x+1)²+(y+2)²=4, (x+1)²+(y−2)²=4", "식(소문항별)", 2)
r(106, T2, "REFLECTION.FIGURE.AXES_ORIGIN", "직선·포물선의 x축·y축·원점 대칭", "도형의 대칭이동", "하", S, "(1) y=2x−4, y=2x+4, y=−2x−4 (2) y=−x²+2x−3, y=x²+2x+3, y=−x²−2x−3", "식(소문항별)", 2)
r(107, T2, "REFLECTION.POINT.Y_EQ_X", "점의 y=x 대칭", "점의 대칭이동", "하", S, "(1) (2,1) (2) (−3,2) (3) (4,−2) (4) (−5,−3)", "좌표(소문항별)", 4)
r(108, T2, "REFLECTION.FIGURE.Y_EQ_X", "도형의 y=x 대칭(예제)", "도형의 대칭이동", "하", S, "(1) x−2y+4=0 (2) (x−3)²+(y+2)²=1", "식(소문항별)", 2)
r(109, T2, "REFLECTION.FIGURE.Y_EQ_X", "도형의 y=x 대칭", "도형의 대칭이동", "하", S, "(1) x−3y+2=0 (2) (x−2)²+y²=4", "식(소문항별)", 2)
r(110, T2, "REFLECTION.MIN_PATH.LIBRARY", "도서관 위치(거리 합 최소)", "대칭이동;두 점 사이의 거리", "중하", D, "A에서 B 방향으로 1 km 떨어진 곳", "서술", fig="그림", i=M, chk="독립풀이 일치(C 대칭 후 직선, 1:2 내분)")
r(111, T1, "TRANSLATION.LINE_CIRCLE", "직선·원 평행이동", "도형의 평행이동", "하", S, "(1) x−2y−7=0 (2) (x−2)²+(y+1)²=4", "식(소문항별)", 2)
r(112, T1, "TRANSLATION.POINT.RULE_FROM_PAIR", "평행이동 규칙 찾아 적용", "점의 평행이동", "하", S, "(−6, 9)", "좌표")
r(113, T2, "REFLECTION.POINT.FOUR_TYPES", "점의 네 가지 대칭이동", "점의 대칭이동", "하", S, "(1,2), (−1,−2), (−1,2), (−2,1)", "좌표")
r(114, T2, "REFLECTION.LINE.FOUR_TYPES", "직선의 네 가지 대칭이동", "도형의 대칭이동", "하", S, "y=−x−1, y=−x+1, y=x−1, y=x−1", "식")
r(115, T1, "TRANSLATION.LINE.TANGENT_CIRCLE", "평행이동한 직선이 원에 접할 a의 합", "도형의 평행이동;원의 접선", "중하", S, "3", c=M, chk="독립풀이 일치(|3−2a|=5 → a=−1, 4)")
r(116, T1, "TRANSLATION.CIRCLE.TANGENT_BOTH_AXES", "두 축에 접하는 원으로 이동 b−a 최대·최소", "도형의 평행이동;원과 직선의 위치 관계", "중", S, "2", c=M, i=M, chk="독립풀이 일치(r=3, b−a=c_y−c_x+1 ∈ {−5,…,7})")
r(117, T2, "REFLECTION_TRANSLATION.LINE.THROUGH_POINT", "평행이동 후 원점 대칭 직선이 점 통과", "도형의 평행이동;도형의 대칭이동", "하", S, "5/3", chk="독립풀이 일치(y=3x+3k+1)")
r(118, T2, "REFLECTION.LINE.Y_EQ_X.INTERSECTION", "직선과 y=x 대칭 직선의 교점", "도형의 대칭이동", "하", S, "−3", trap="교점은 y=x 위")
r(119, T2, "REFLECTION.MIN_PERIMETER.RECTANGLE_QUAD", "직사각형 내접 사각형 둘레 최솟값", "대칭이동;두 점 사이의 거리", "중상", S, "2√5+6√2", fig="그림", c=M, i=H, chk="독립풀이 일치(B 원점: P(2,5)·S(4,1) 대칭 → 6√2, SP=2√5)")
r(120, T2, "REFLECTION.MIRRORS.LASER", "직교 두 거울 반사 경로 길이(활동)", "대칭이동;두 점 사이의 거리", "중", ACT, "1) (1) 풀이참조 (2) 풀이참조 (3) √61", "값+서술", 3, fig="그림", i=M, chk="독립풀이 (3) √61 일치(A'(5,−2), B'(−1,3))")
r(121, P2, "SECTION.INTERNAL.PLANE", "내분점 좌표 합(객관식)", "선분의 내분점", "하", MC, "③ (6)", "선택지", final="③")
r(122, L1, "LINE.TRIANGLE_AREA.AXES", "직선과 두 축으로 둘러싸인 넓이(객관식)", "직선의 방정식", "하", MC, "④ (9)", "선택지", final="④")
r(123, L3, "DIST_POINT_LINE.FIND_PARAM", "거리 1인 양수 a(객관식)", "점과 직선 사이의 거리", "하", MC, "① (1)", "선택지", final="①", trap="절댓값 두 경우 중 양수")
r(124, C2, "TANGENT.EXTERNAL_POINT.SLOPE_RANGE", "외부 점과 원 위 점 잇는 기울기 최대·최소(객관식)", "원과 직선의 위치 관계;원의 접선", "중하", MC, "① (−1)", "선택지", final="①", c=M, chk="독립풀이 일치(접선 기울기 ±1)")
r(125, L3, "DIST_POINT_LINE.REFLECTED_POINTS_RATIO", "대칭점들의 직선까지 거리 비(객관식)", "점과 직선 사이의 거리;점의 대칭이동", "하", MC, "⑤ (3)", "선택지", final="⑤")
r(126, T2, "REFLECTION.MIN_PATH.TRIANGLE_AREA", "거리 합 최소점에서 삼각형 넓이(객관식)", "대칭이동;직선의 방정식", "중", MC, "④ (9/4)", "선택지", final="④", c=M, i=M, chk="독립풀이 일치(P(11/4, 0))")
r(127, L2, "LINE.PERP_BISECTOR.INTERSECT_LINE", "수직이등분선과 직선 교점(객관식)", "두 직선의 수직;두 점 사이의 거리", "하", MC, "① (−5)", "선택지", final="①", chk="독립풀이 일치(P(−2, 10))")
r(128, T2, "REFLECTION.LINE.PARALLEL_DISTANCE", "대칭 직선 사이 거리", "도형의 대칭이동;점과 직선 사이의 거리", "하", S, "√2")
r(129, L2, "LINE.THREE_LINES.NO_TRIANGLE", "세 직선이 삼각형 못 이루는 m의 합", "두 직선의 평행;연립방정식", "중", S, "1/6", c=M, i=M, trap="평행 2경우+한 점에서 만남(m=5/2)", chk="독립풀이 일치(−3+2/3+5/2)")
r(130, L2, "LINE.PERPENDICULAR.THROUGH_POINT", "두 점 직선에 수직인 직선(서술형)", "두 직선의 수직", "하", D, "y=−3x/2+3", "식", final="y=−(3/2)x+3", chk="독립풀이 = 해설 결과 일치(빠른 정답 '풀이참조')")
r(131, T2, "REFLECTION_TRANSLATION.CIRCLE.COEFFS", "원 평행이동 후 y=x 대칭 계수(서술형)", "도형의 평행이동;도형의 대칭이동", "중하", D, "a=−12, b=4, c=36", final="a=−12, b=4, c=36", chk="독립풀이 = 해설 결과 일치(빠른 정답 '풀이참조')")
r(132, T2, "REFLECTION.MIN_PATH.POINT_TO_CIRCLE", "x축 경유 점-원 최단거리(서술형)", "대칭이동;원의 방정식;두 점 사이의 거리", "중", D, "ab=−8 (최솟값 4√2−2)", final="−8", c=M, i=M, chk="독립풀이 = 해설 결과 일치(빠른 정답 '풀이참조')")
for i in range(14): build(f"Batch{527+i}", ROWS[i*10:(i+1)*10], 13663+i*10)
print(len(ROWS))
