from rows84h import *
r(1, E1, "LIMFN.POLY_RATIONAL.PREP", "다항·유리함수 극한값(준비)", "함수의 극한", "하", S, "(1) 5 (2) 2", "값(소문항별)", 2)
r(2, E1, "LIMEXP.GRAPH.INTUITION", "지수함수 그래프로 x→∞ 극한 직관(생각 열기)", "지수함수의 극한;그래프", "하", ACT, "3ˣ은 한없이 커지고, (1/3)ˣ은 0에 가까워진다", "서술", fig="그래프")
r(3, E1, "LIMEXP.BASIC.DIRECTION", "지수함수의 극한 조사", "지수함수의 극한", "하", S, "(1) ∞ (2) 0 (3) 0", "값(소문항별)", 3)
r(4, E1, "LIMEXP.RATIONAL_FORM.DIVIDE", "지수식 분수꼴 극한(예제)", "지수함수의 극한;∞/∞ 꼴", "하", S, "(1) 1 (2) 0", "값(소문항별)", 2)
r(5, E1, "LIMEXP.RATIONAL_FORM.DIVIDE", "지수식 분수꼴 극한", "지수함수의 극한;∞/∞ 꼴", "하", S, "(1) −1 (2) 1/2", "값(소문항별)", 2)
r(6, E1, "LIMLOG.BASIC.DIRECTION", "로그함수의 극한 조사(밑에 따른 방향)", "로그함수의 극한", "하", S, "(1) ∞ (2) ∞ (3) −∞", "값(소문항별)", 3, trap="밑이 1보다 작을 때 방향")
r(7, E1, "LIMLOG.CONTINUITY_AND_INSIDE_LIMIT", "로그 포함 극한값(예제)", "로그함수의 극한;로그함수의 연속", "하", S, "(1) 1 (2) 2", "값(소문항별)", 2)
r(8, E1, "LIMLOG.CONTINUITY_AND_INSIDE_LIMIT", "로그 포함 극한값", "로그함수의 극한;로그의 성질", "하", S, "(1) 2 (2) 0 (3) −1 (4) 1", "값(소문항별)", 4, d=M)
r(9, E1, "LIME.DEFINITION.NUMERIC_TABLE", "(1+x)^(1/x) 수치표로 e 직관(생각 열기)", "무리수 e;극한", "하", ACT, "x→0+, x→0− 모두 2.71828…에 한없이 가까워진다", "서술", fig="수치표 그림")
r(10, E1, "LIME.DEFINITION.TRANSFORM", "e의 정의 꼴 변형 극한(예제)", "무리수 e의 정의", "하", S, "(1) e² (2) e^(1/3)", "값(소문항별)", 2)
r(11, E1, "LIME.DEFINITION.TRANSFORM", "e의 정의 꼴 변형 극한", "무리수 e의 정의", "하", S, "(1) e⁴ (2) e^(1/4) (3) e⁵", "값(소문항별)", 3)
r(12, E1, "LN.VALUE.BASIC", "자연로그 값 계산", "자연로그", "하", S, "(1) 0 (2) 7 (3) −1/2 (4) √3", "값(소문항별)", 4)
r(13, E1, "LIME.LN_EXP.BASIC_LIMITS", "ln(1+x)/x, (eˣ−1)/x 극한(예제)", "지수·로그함수의 극한 공식", "하", S, "(1) 1 (2) 1", "값(소문항별)", 2)
r(14, E1, "LIME.LN_EXP.SCALED_AND_GENERAL_BASE", "지수·로그 기본극한 변형·일반 밑", "지수·로그함수의 극한 공식", "하", S, "(1) 3 (2) 2 (3) 1/ln a (4) ln a", "값(소문항별)", 4, d=M)
r(15, E1, "LIMEXP.APPLIED.NEWTON_COOLING", "뉴턴 냉각 법칙 극한(실생활)", "지수함수의 극한;실생활", "하", "서술형(단답+해석)", "20, 시간이 많이 흐르면 물의 온도가 실내 온도(20℃)에 가까워진다", "값+서술", combo="극한+실생활", final="20")
r(16, E2, "DERIV.DEFINITION.POWER_PREP", "도함수 정의로 x² 미분(준비)", "도함수의 정의", "하", S, "f′(x)=2x", "식")
r(17, E2, "DERIV.EXP.DERIVATIVE_AT_POINT_INTUITION", "eˣ의 x=1 미분계수(생각 열기)", "도함수의 정의;지수함수의 미분", "하", ACT, "e", fig="그래프")
r(18, E2, "DERIV.EXP.BASIC_AND_PRODUCT", "지수함수 미분·곱의 미분(예제)", "지수함수의 도함수;곱의 미분법", "하", S, "(1) y′=3^(x+2)·ln3 (2) y′=x(2+x)eˣ", "식(소문항별)", 2)
r(19, E2, "DERIV.EXP.BASIC_AND_PRODUCT", "지수함수 미분·곱의 미분", "지수함수의 도함수;곱의 미분법", "하", S, "(1) y′=2^(x−4)·ln2 (2) y′=(3x+8)eˣ", "식(소문항별)", 2)
r(20, E2, "DERIV.LOG.CHANGE_OF_BASE_DERIVATION", "밑 변환으로 logₐx 도함수 유도(빈칸)", "로그함수의 도함수;밑의 변환", "하", "빈칸채우기", "ln x, 1/x, 1/(x ln a)", "식")
r(21, E2, "DERIV.LOG.BASIC_AND_PRODUCT", "로그함수 미분(예제)", "로그함수의 도함수;곱의 미분법", "하", S, "(1) y′=1/x (2) y′=log₅x+1/ln5", "식(소문항별)", 2)
r(22, E2, "DERIV.LOG.BASIC_AND_PRODUCT", "지수·로그 곱 미분", "로그함수의 도함수;곱의 미분법", "하", S, "(1) y′=(x ln x+1)eˣ/x (2) y′=2x log₆x+x/ln6", "식(소문항별)", 2)
r(23, T1, "TRIG.VALUE.FROM_ONE_RATIO_PREP", "한 삼각비로 나머지 값(준비)", "삼각함수 사이의 관계", "하", S, "cosθ=12/13, tanθ=5/12", "값")
r(24, T1, "TRIG.RECIPROCAL.INTRO_RIGHT_TRIANGLE", "직각삼각형 삼각비와 역수(생각 열기)", "삼각비;csc·sec·cot", "하", ACT, "sinθ=4/5, cosθ=3/5, tanθ=4/3; 1/sinθ=5/4, 1/cosθ=5/3, 1/tanθ=3/4", "값", 2, fig="그림")
r(25, T1, "TRIG.RECIPROCAL.VALUE", "csc·sec·cot 값", "csc·sec·cot", "하", S, "(1) 2√3/3 (2) 2 (3) 1", "값(소문항별)", 3, trap="음의 각 sec")
r(26, T1, "TRIG.RECIPROCAL.UNIT_CIRCLE_SIMILAR_TRIANGLES", "단위 사분원 닮음으로 sec·csc·cot 길이 설명", "csc·sec·cot;닮음", "중하", PRF, "OC=secθ, OF=cscθ, EF=cotθ (닮음비로 설명)", "증명", 3, fig="그림", i=M, final="풀이 참조(닮음비)")
r(27, T1, "TRIG.RECIPROCAL.PYTHAGOREAN_IDENTITY", "1+tan²θ=sec²θ 증명(예제)", "삼각함수 사이의 관계", "하", PRF, "양변을 cos²θ로 나누어 성립", "증명", final="풀이 참조")
r(28, T1, "TRIG.RECIPROCAL.PYTHAGOREAN_IDENTITY", "1+cot²θ=csc²θ 등 항등식 증명", "삼각함수 사이의 관계", "하", PRF, "sin²θ+cos²θ=1을 이용해 성립", "증명", 2, final="풀이 참조")
r(29, T1, "TRIG.ADDITION.DERIVE_COS_DISTANCE", "합동 삼각형·거리공식으로 코사인 덧셈정리 유도(생각 열기)", "삼각함수의 덧셈정리;두 점 사이의 거리", "중하", ACT, "AB²=2−2cos65°, CD²=2−2(cos40°cos25°−sin40°sin25°), cos65°=cos40°cos25°−sin40°sin25°", "식", 2, fig="그림", i=M)
r(30, T1, "TRIG.ADDITION.SPECIAL_ANGLE_VALUES", "덧셈정리로 특수각 합·차 값(예제)", "삼각함수의 덧셈정리", "하", S, "(1) (√2+√6)/4 (2) (√2+√6)/4 (3) 2−√3", "값(소문항별)", 3)
r(31, T1, "TRIG.ADDITION.SPECIAL_ANGLE_VALUES", "덧셈정리로 특수각 합·차 값", "삼각함수의 덧셈정리;sec", "하", S, "(1) (√6−√2)/4 (2) (√2−√6)/4 (3) 2+√3 (4) √2+√6", "값(소문항별)", 4, d=M)
r(32, T1, "TRIG.ADDITION.QUADRANT_GIVEN_SINES", "사분면 조건과 덧셈정리(예제)", "삼각함수의 덧셈정리;삼각함수 부호", "하", S, "(2√2−√3)/6", d=M, trap="cosβ 부호")
r(33, T1, "TRIG.ADDITION.QUADRANT_GIVEN_SINES", "사분면 조건과 sin·cos·tan 덧셈정리", "삼각함수의 덧셈정리;삼각함수 부호", "중하", S, "(1) (3+4√3)/10 (2) −(4+3√3)/10 (3) (48−25√3)/11", "값(소문항별)", 3, c=M, d=M, trap="cosα<0")
r(34, T1, "TRIG.DOUBLE_ANGLE.COS_PROOF", "cos2α=2cos²α−1 증명(예제)", "배각의 공식", "하", PRF, "cos²α−sin²α=2cos²α−1", "증명", final="풀이 참조")
r(35, T1, "TRIG.DOUBLE_ANGLE.SIN_TAN_PROOF", "sin2α, tan2α 배각공식 증명", "배각의 공식", "하", PRF, "덧셈정리에 β=α 대입", "증명", 2, final="풀이 참조")
r(36, T1, "TRIG.ADDITION.ANGLE_BETWEEN_LINES", "두 직선이 이루는 예각(예제)", "삼각함수의 덧셈정리;직선의 기울기", "하", S, "π/4", combo="덧셈정리+직선")
r(37, T1, "TRIG.ADDITION.ANGLE_BETWEEN_LINES", "두 직선이 이루는 예각", "삼각함수의 덧셈정리;직선의 기울기", "하", S, "π/4", combo="덧셈정리+직선")
r(38, T1, "TRIG.ADDITION.APPLIED_HEIGHT", "올려본각·내려본각과 탑 높이", "삼각함수의 덧셈정리;실생활", "중하", S, "13.6 m", fig="그림", combo="덧셈정리+실생활", d=M)
r(39, T1, "TRIG.HALF_ANGLE.DERIVE", "반각 공식 유도", "반각의 공식;배각의 공식", "하", PRF, "cos²(α/2)=(1+cosα)/2, sin²(α/2)=(1−cosα)/2", "증명", final="풀이 참조")
r(40, T1, "TRIG.HALF_ANGLE.DERIVE_AND_APPLY", "반각 공식 설명과 값(생각 넓히기)", "반각의 공식", "중하", "서술형(탐구)", "(1) cos²(α/2)=(1+cosα)/2 (2) sin²(α/2)=(1−cosα)/2; sin(α/2)=√6/3, cos(α/2)=√3/3", "식·값", 3, d=M, chk="독립풀이(cosα=−1/3)로 값 산출, 파일 답은 공식부분만 표기")
r(41, T1, "TRIG.ADDITION.AREA_PROOF", "삼각형 넓이로 덧셈정리 확인(탐구)", "삼각함수의 덧셈정리;삼각형의 넓이", "중", "서술형(탐구)", "넓이 분할로 sin(α+β)=sinαcosβ+cosαsinβ 확인", "증명", fig="그림", i=M, final="풀이 참조")
r(42, T2, "LIMFN.FACTOR.PREP", "0/0 꼴 인수분해 극한(준비)", "함수의 극한", "하", S, "4")
r(43, T2, "LIMTRIG.CONTINUITY.GRAPH_INTUITION", "그래프로 sin·cos x→0 극한(생각 열기)", "삼각함수의 극한;그래프", "하", ACT, "lim sin x=0, lim cos x=1", "값", fig="그래프")
r(44, T2, "LIMTRIG.CONTINUITY.DIRECT", "삼각함수 극한 조사", "삼각함수의 극한", "하", S, "(1) 1/2 (2) √2/2 (3) −∞", "값(소문항별)", 3, trap="tan 우극한")
r(45, T2, "LIMTRIG.ALGEBRAIC.FACTOR_PYTHAGOREAN", "삼각함수 0/0 꼴 인수분해(예제)", "삼각함수의 극한;삼각함수 사이의 관계", "하", S, "2")
r(46, T2, "LIMTRIG.ALGEBRAIC.FACTOR_PYTHAGOREAN", "삼각함수 0/0 꼴 인수분해", "삼각함수의 극한;삼각함수 사이의 관계", "중하", S, "(1) 1/2 (2) −√2/4", "값(소문항별)", 2, d=M)
r(47, T2, "LIMTRIG.SINX_OVER_X.SCALED", "sin3x/x(예제)", "lim sinx/x=1", "하", S, "3")
r(48, T2, "LIMTRIG.SINX_OVER_X.SCALED", "sin4x/sinx, tanx/x", "lim sinx/x=1", "하", S, "(1) 4 (2) 1", "값(소문항별)", 2)
r(49, T2, "LIMTRIG.SINX_OVER_X.CONJUGATE_SUBST", "1−cos 유리화·치환 극한(예제)", "lim sinx/x=1;치환", "하", S, "(1) 0 (2) 2", "값(소문항별)", 2, d=M)
r(50, T2, "LIMTRIG.SINX_OVER_X.CONJUGATE_SUBST", "(1−cosx)/x², tanx/(π−x)", "lim sinx/x=1;치환", "중하", S, "(1) 1/2 (2) −1", "값(소문항별)", 2, d=M, trap="x=π−t 치환 부호")
r(51, T2, "LIMTRIG.SQUEEZE.X_SIN_1_OVER_X", "x·sin(1/x) 조임정리(탐구)", "함수의 극한의 대소 관계", "중하", "서술형(탐구)", "0", fig="그래프", i=M)
r(52, T3, "TRIG.ADDITION.VALUE_PREP", "cos75° 값(준비)", "삼각함수의 덧셈정리", "하", S, "(√6−√2)/4")
r(53, T3, "DERIV.TRIG.SLOPE_AT_ORIGIN_INTUITION", "sin x 원점 접선 기울기(생각 열기)", "도함수의 정의;삼각함수의 극한", "하", ACT, "1", fig="그래프")
r(54, T3, "DERIV.TRIG.COS_DERIVATION", "도함수 정의로 (cos x)′=−sin x 유도", "삼각함수의 도함수;도함수의 정의", "중하", PRF, "(cos x)′=−sin x", "증명", i=M, final="풀이 참조")
r(55, T3, "DERIV.TRIG.BASIC_AND_PRODUCT", "sin·cos 미분과 곱(예제)", "삼각함수의 도함수;곱의 미분법", "하", S, "(1) y′=cos x+sin x (2) y′=eˣ(sin x+cos x)", "식(소문항별)", 2)
r(56, T3, "DERIV.TRIG.BASIC_AND_PRODUCT", "sin·cos 미분과 곱", "삼각함수의 도함수;곱의 미분법", "하", S, "(1) y′=3cos x−sin x (2) y′=x(2cos x−x sin x) (3) y′=cos²x−sin²x (4) y′=2sin x cos x", "식(소문항별)", 4)
r(57, E1, "LIMEXP_LOG.MIXED_CONVERGENCE", "지수·로그 극한 수렴·발산(중단원 마무리)", "지수함수의 극한;로그함수의 극한;e의 정의", "하", S, "(1) 1로 수렴 (2) 발산(−∞) (3) −2로 수렴 (4) 1로 수렴", "서술(소문항별)", 4, d=M)
r(58, E2, "DERIV.EXP_LOG.CHAIN_LINEAR", "지수·로그 함수 미분(중단원 마무리)", "지수함수의 도함수;로그함수의 도함수", "하", S, "(1) y′=2e^(2x) (2) y′=3·2^(3x+1)·ln2 (3) y′=3/x (4) y′=1/(x ln5)", "식(소문항별)", 4)
r(59, T1, "TRIG.RECIPROCAL.TERMINAL_SIDE_POINT", "동경 위 점으로 csc·sec·cot", "csc·sec·cot;일반각", "하", S, "cscθ=5/4, secθ=−5/3, cotθ=−3/4", "값", trap="제2사분면 부호")
r(60, T1, "TRIG.ADDITION.QUADRANT_GIVEN_SINES", "사분면 조건과 덧셈정리(중단원 마무리)", "삼각함수의 덧셈정리;삼각함수 부호", "중하", S, "(1) −(3+√6)/6 (2) −(3√2+√3)/6", "값(소문항별)", 2, c=M, d=M)
r(61, T3, "DERIV.TRIG.BASIC_AND_PRODUCT", "삼각함수 미분(중단원 마무리)", "삼각함수의 도함수;곱의 미분법", "하", S, "(1) y′=2+3cos x (2) y′=2x cos x−(x²−1)sin x", "식(소문항별)", 2)
r(62, E1, "LIMEXP_LOG.RATIONAL_AND_BASIC_LIMIT", "지수 분수꼴·로그 기본극한", "지수함수의 극한;로그함수의 극한 공식", "하", S, "(1) −1 (2) 1/(2 ln3)", "값(소문항별)", 2)
r(63, E1, "LIMEXP.UNDETERMINED_COEFF.RADICAL", "(√(ax+b)−3)/(eˣ−1)=1 미정계수", "지수함수의 극한;미정계수;유리화", "중", D, "54", c=M, d=M, i=M, combo="극한+미정계수", trap="분모→0이면 분자→0")
r(64, E1, "LIMLOG.UNDETERMINED_COEFF", "ln(a+7x)/(x²+x)=b 미정계수", "로그함수의 극한;미정계수", "중하", S, "8", d=M, i=M, combo="극한+미정계수")
r(65, E2, "DERIV.LOG.MVT_AVERAGE_RATE", "평균변화율=미분계수(x ln x)", "로그함수의 도함수;평균변화율", "중하", S, "e^(1/(e−1))", c=M, d=M, combo="미분+평균변화율")
r(66, T1, "TRIG.RECIPROCAL.SYMMETRIC_EXPRESSIONS", "sinθcosθ=1/2일 때 tan+cot, csc+sec", "csc·sec·cot;삼각함수 사이의 관계", "중하", S, "(1) 2 (2) 2√2", "값(소문항별)", 2, d=M)
r(67, T1, "TRIG.ADDITION.VIETA_TAN_ROOTS", "tan 두 근(근과 계수)과 cos(α+β)", "삼각함수의 덧셈정리;근과 계수의 관계", "중", S, "−√5/5", c=M, d=M, i=M, combo="덧셈정리+이차방정식", trap="α+β의 사분면 판단")
r(68, T2, "LIMTRIG.SINX_OVER_X.MIXED", "삼각·지수 기본극한 혼합", "lim sinx/x=1;지수함수의 극한 공식", "중하", S, "(1) 2 (2) 1 (3) 2", "값(소문항별)", 3, d=M)
r(69, T3, "DERIV.TRIG.DIFFERENCE_QUOTIENT_SCALED", "미분계수 정의 변형(x sin x)", "미분계수의 정의;삼각함수의 도함수", "중하", S, "7", d=M)
r(70, E1, "LIMEXP.CONTINUITY_DETERMINE_VALUE", "연속 조건으로 f(2) 결정", "함수의 연속;지수함수의 극한 공식", "중하", S, "3", d=M, i=M, combo="극한+연속")
r(71, T1, "TRIG.ADDITION.SUM_SQUARES_COS_DIFF", "sin합·cos합 제곱으로 cos(α−β)", "삼각함수의 덧셈정리", "중", S, "−5/8", c=M, i=M)
r(72, T1, "TRIG.DOUBLE_ANGLE.CIRCLE_CHORD", "지름 위 원주각과 배각으로 현 길이", "배각의 공식;원주각", "중", D, "23/7", fig="그림", c=M, d=M, i=M, combo="배각+원")
r(73, T2, "LIMTRIG.GEOMETRY.SECTOR_SEGMENT", "사분원 BH/θ² 극한", "삼각함수의 극한;도형", "중", S, "3", fig="그림", d=M, i=M, combo="극한+도형")
r(74, T3, "DERIV.PIECEWISE.DEFINITION_AT_ZERO", "구간별 함수 f′(0) 정의로 계산", "미분계수의 정의;삼각함수의 극한;조임정리", "중", S, "12", c=M, d=M, i=M, trap="h·cos(1/h)→0")
r(75, Q1, "DERIV.PRODUCT.POLY_PREP", "곱의 미분(준비)", "곱의 미분법", "하", S, "y′=6x²−10x−3", "식")
r(76, Q1, "DERIV.RECIPROCAL.BOYLE_INTUITION", "보일 법칙 y=1/x 증분(생각 열기)", "평균변화율;1/x의 도함수", "하", ACT, "(1) Δy=−Δx/(a(a+Δx)) (2) −1/a²", "식(소문항별)", 2, combo="미분+실생활")
r(77, Q1, "DERIV.QUOTIENT.DERIVATION_BLANK", "몫의 미분법 유도(빈칸)", "몫의 미분법", "하", "빈칸채우기", "g(x), g(x), g(x), −g′(x)/{g(x)}²", "식")
r(78, Q1, "DERIV.QUOTIENT.BASIC", "몫의 미분(예제)", "몫의 미분법", "하", S, "(1) y′=−eˣ/(eˣ−2)² (2) y′=−(x²−4x−1)/(x²+1)²", "식(소문항별)", 2)
r(79, Q1, "DERIV.QUOTIENT.BASIC", "몫의 미분", "몫의 미분법", "하", S, "(1) y′=−3x²/(x³+2)² (2) y′=(1−ln x)/x²", "식(소문항별)", 2)
r(80, Q1, "DERIV.TRIG.TAN_SEC_PROOF", "(tan x)′, (sec x)′ 유도(예제)", "몫의 미분법;삼각함수의 도함수", "하", PRF, "(tan x)′=sec²x, (sec x)′=sec x tan x", "증명", 2, final="풀이 참조")
r(81, Q1, "DERIV.TRIG.COT_CSC_PROOF", "(cot x)′, (csc x)′ 유도", "몫의 미분법;삼각함수의 도함수", "하", PRF, "(cot x)′=−csc²x, (csc x)′=−csc x cot x", "증명", 2, final="풀이 참조")
r(82, Q1, "DERIV.TRIG.RECIPROCAL_FUNCS", "tan·cot·sec 포함 미분", "삼각함수의 도함수;몫의 미분법", "중하", S, "(1) y′=2sec²x−csc²x (2) y′=2sin x/(1+cos x)² (3) y′=(2x cos x+x² sin x)/cos²x (4) y′=sec x(tan²x+sec²x)", "식(소문항별)", 4, c=M)
r(83, Q1, "DERIV.POWER.NEGATIVE_INTEGER", "음의 정수 지수 미분", "xⁿ(n은 정수)의 도함수", "하", S, "(1) y′=−6/x⁷ (2) y′=12/x⁵ (3) y′=1−2/x³ (4) y′=3/x⁴−5/x⁶", "식(소문항별)", 4)
r(84, Q2, "COMPOSITE.FUNCTION.PREP", "합성함수 구하기(준비)", "합성함수", "하", S, "(1) f(g(x))=3x+2 (2) g(f(x))=3x+6", "식(소문항별)", 2)
r(85, Q2, "DERIV.CHAIN.INTUITION_COMPARE", "dy/du·du/dx 비교(생각 열기)", "합성함수의 미분법", "하", ACT, "(1) y=(2x−1)², dy/dx=8x−4 (2) 8x−4, 같다", "식(소문항별)", 2)
r(86, Q2, "DERIV.CHAIN.BASIC", "합성함수 미분(예제)", "합성함수의 미분법", "하", S, "(1) y′=10x(x²−2)⁴ (2) y′=4cos(4x+3)", "식(소문항별)", 2)
r(87, Q2, "DERIV.CHAIN.BASIC", "합성함수 미분", "합성함수의 미분법", "하", S, "(1) y′=6(2x+3)(x²+3x)⁵ (2) y′=3(1+1/x²)(x−1/x)² (3) y′=2e^(2x+1) (4) y′=−3sin x cos²x", "식(소문항별)", 4)
r(88, Q2, "DERIV.LOG_ABS.DERIVATION", "ln|x|의 도함수 유도", "합성함수의 미분법;로그함수의 도함수", "하", PRF, "x>0, x<0 모두 y′=1/x", "증명", 2, final="풀이 참조")
r(89, Q2, "DERIV.LOG_ABS.CHAIN", "ln|f(x)| 꼴 미분", "로그함수의 도함수;합성함수의 미분법", "하", S, "(1) y′=−tan x (2) y′=2x/((x²−1)ln3)", "식(소문항별)", 2)
r(90, Q2, "DERIV.POWER.REAL_EXPONENT", "실수 지수·거듭제곱근 미분", "xᵃ(a는 실수)의 도함수;합성함수의 미분법", "하", S, "(1) y′=πx^(π−1) (2) y′=5/(2√(5x+2)) (3) y′=2/(3∛x)", "식(소문항별)", 3)
r(91, Q2, "DERIV.LOG_DIFFERENTIATION.POWER", "로그미분법으로 {f(x)}ⁿ 미분(탐구)", "로그미분법;합성함수의 미분법", "중하", "서술형(탐구)", "y′=n{f(x)}^(n−1)·f′(x)", "증명", i=M, final="풀이 참조")
r(92, Q3, "DERIV.CHAIN.PREP", "합성함수 미분(준비)", "합성함수의 미분법", "하", S, "(1) y′=8(2x+7)³ (2) y′=−2sin(2x+1)", "식(소문항별)", 2)
r(93, Q3, "PARAM.ELIMINATE.INTUITION", "매개변수 소거(생각 열기)", "매개변수로 나타낸 함수", "하", ACT, "y=x²−5x+6 (x≥2)", "식", trap="정의역 x≥2")
r(94, Q3, "PARAM.ELIMINATE.TRIG_CIRCLE", "x=cos t, y=sin t 관계식(예제)", "매개변수로 나타낸 함수", "하", S, "x²+y²=1 (y≥0)", "식", trap="y≥0")
r(95, Q3, "PARAM.ELIMINATE.BASIC", "매개변수 소거", "매개변수로 나타낸 함수", "하", S, "(1) y=2x+5 (2) y=x² (3) y=−x²/5 (4) y=e^(2x+6)", "식(소문항별)", 4)
r(96, Q3, "PARAM.DERIV.BASIC", "매개변수 함수 dy/dx(예제)", "매개변수로 나타낸 함수의 미분법", "하", S, "dy/dx=(2/5)t+1", "식")
r(97, Q3, "PARAM.DERIV.BASIC", "매개변수 함수 dy/dx", "매개변수로 나타낸 함수의 미분법", "중하", S, "(1) t² (2) 3t²/(2t−5) (3) cot t (4) (1+t)²/(2(2+t)²)", "식(소문항별)", 4, c=M)
r(98, Q3, "PARAM.CYCLOID.REPRESENT", "사이클로이드 매개변수 표현(탐구)", "매개변수로 나타낸 함수;사이클로이드", "중", "서술형(탐구)", "x=r(θ−sinθ), y=r(1−cosθ); dy/dx=sinθ/(1−cosθ)", "식", 2, fig="그림", i=M)
r(99, Q3, "PARAM.DERIV.ASTROID_LIKE_TANGENT", "자연 곡선 매개변수 미분과 접선 기울기(탐구)", "매개변수로 나타낸 함수의 미분법", "중", "서술형(탐구)", "풀이 참조(dy/dθ=(3/4)(cosθ−cos3θ) 등, θ=π/3에서 값과 기울기)", "식·값", 3, fig="그림", i=M, final="풀이 참조", chk="파일 해설 '풀이 참조' — dx/dθ 식이 그림/표에 있어 독립검산 불가")
r(100, Q4, "INVERSE.FUNCTION.SQRT_PREP", "√x의 역함수와 도함수(준비)", "역함수;무리함수의 도함수", "하", S, "(1) y=x² (x≥0) (2) dy/dx=1/(2√x) (x>0)", "식(소문항별)", 2)
r(101, Q4, "IMPLICIT.FUNCTION.CIRCLE_GRAPH_INTUITION", "원·반원이 함수 그래프인지(생각 열기)", "음함수;함수의 정의", "하", ACT, "(1) 함수의 그래프가 아니다 (2) 둘 다 함수의 그래프이다", "서술(소문항별)", 2, fig="그림")
r(102, Q4, "IMPLICIT.FORM.CONVERT", "음함수 꼴로 나타내기(예제)", "음함수", "하", S, "(1) 2x−y+5=0 (2) √(x²−1)−y=0", "식(소문항별)", 2)
r(103, Q4, "IMPLICIT.DERIV.CONIC", "음함수 미분(예제)", "음함수의 미분법", "하", S, "dy/dx=2x/(3y) (y≠0)", "식")
r(104, Q4, "IMPLICIT.DERIV.GENERAL", "음함수 미분", "음함수의 미분법", "중하", S, "(1) −(2x+y)/(x+2y) (2) (2x−y)/(x+2) (3) x/(2y³−y) (4) −(y+1)/(x+sin y)", "식(소문항별)", 4, c=M)
r(105, Q4, "INVERSE.DERIV.RADICAL", "역함수 미분법으로 ∛(x−2) 도함수(예제)", "역함수의 미분법", "하", S, "1/(3∛((x−2)²))", "식")
r(106, Q4, "INVERSE.DERIV.RADICAL", "역함수 미분법으로 거듭제곱근 도함수", "역함수의 미분법", "하", S, "(1) 1/(4∜((x+1)³)) (2) 4/(3∛((4x−8)²))", "식(소문항별)", 2)
r(107, Q4, "INVERSE.DERIV.VALUE_AT_POINT", "(f⁻¹)′(2) 값(예제)", "역함수의 미분법", "하", S, "1/4", d=M, trap="f(a)=2인 a 먼저")
r(108, Q4, "INVERSE.DERIV.VALUE_AT_POINT", "(f⁻¹)′(√2) 값", "역함수의 미분법", "하", S, "√2", d=M)
r(109, Q4, "INVERSE.DERIV.GEOMETRIC_SLOPE", "접선 직각삼각형으로 역함수 미분 설명(탐구)", "역함수의 미분법;대칭", "중하", "서술형(탐구)", "QR=f′(1)=5, 역함수 접선 기울기 1/5", "증명", fig="그래프", i=M, final="풀이 참조")
r(110, Q5, "DERIV.POWER_EXP.PREP", "x^(3/2), e^(2x) 도함수(준비)", "도함수", "하", S, "(1) y′=(3/2)√x (2) y′=2e^(2x)", "식(소문항별)", 2)
r(111, Q5, "SECOND_DERIV.FREE_FALL_INTUITION", "화성 자유낙하 속도·가속도(생각 열기)", "이계도함수;속도와 가속도", "하", ACT, "(1) 7.4t m/s (2) 7.4 m/s²", "식(소문항별)", 2, combo="미분+실생활")
r(112, Q5, "SECOND_DERIV.BASIC", "이계도함수(예제)", "이계도함수", "하", S, "(1) y″=6x−8 (2) y″=−1/x²", "식(소문항별)", 2)
r(113, Q5, "SECOND_DERIV.BASIC", "이계도함수", "이계도함수;합성함수의 미분법", "하", S, "(1) y″=48(−2x+1)² (2) y″=−1/(4x√x) (3) y″=−9cos3x (4) y″=25e^(5x+1)", "식(소문항별)", 4)
r(114, Q5, "SECOND_DERIV.PRODUCT_QUOTIENT", "곱·몫 이계도함수(예제)", "이계도함수;몫의 미분법", "중하", S, "(1) y″=2ln x+3 (2) y″=(6x²−2)/(x²+1)³", "식(소문항별)", 2, c=M)
r(115, Q5, "SECOND_DERIV.PRODUCT_QUOTIENT", "곱·몫 이계도함수", "이계도함수;곱의 미분법", "중하", S, "(1) y″=−2/(x+2)³ (2) y″=−2sin x−x cos x (3) y″=eˣ(ln x+2/x−1/x²) (4) y″=2cos²x−2sin²x", "식(소문항별)", 4, c=M)
r(116, Q5, "SECOND_DERIV.DIFF_EQUATION_VERIFY", "y″+2y′+2y=0 성립 확인", "이계도함수", "중하", PRF, "y″+2y′+2y=0 성립", "증명", c=M, final="0 (성립)")
r(117, Q5, "SECOND_DERIV.FIND_FUNCTIONS_OPEN", "f″=f, g″=−g 만족 함수 찾기(탐구)", "이계도함수", "중하", "서술형(탐구)", "예: f(x)=e^(−x) (또는 eˣ, eˣ+e^(−x)), g(x)=sin x (또는 cos x)", "서술(개방형)", i=M, final="f(x)=e^(−x), g(x)=sin x (예시)", chk="개방형 — 파일 예시 답 검산")
r(118, Q5, "SECOND_DERIV.CAS_ACTIVITY", "프로그램으로 도함수·이계도함수(활동)", "이계도함수", "하", ACT, "f′(x)=3e^(3x)+2x sec²x², f″(x)=9e^(3x)+2sec²x²+8x²sec²x² tan x²", "식", 2, final="풀이 참조", chk="독립풀이(tan x²로 해석); 파일 '풀이참조'")
