from cfgy2 import *
import cfgy2, builder
SQ = hashlib.sha256(open(OUT+'h65/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y65.json'))
setup(QID="A02465", SRC="14-ZwzTI50Ndra3z0V3WRDQSVQqaCc5RZ", SHA=SQ, TAG="YMSS05", N=92, SUBJ="수학(하)", SEC="S05A",
      FNAME="05 함수(신사고) 92제.hwp", UNIT="Ⅴ. 함수", BIG="Ⅴ. 함수", EXAM="5. 함수 92제", MID="함수")
cfgy2.P.update(BOOK="신사고 수학(하)", GRADE="고1", MEMO_X="파서: 열0 '[gso]'+본문 붙은 문항 머리 2개(68·71번) 인식 보정 후 92문항=빠른 정답 92개 정렬 일치; ")
for s, mid in (("S05A", "함수"), ("S05B", "합성함수"), ("S05C", "역함수"), ("S05D", "함수(중단원 마무리)"), ("S05E", "유리함수"), ("S05F", "무리함수"), ("S05G", "유리함수와 무리함수(중단원 마무리)"), ("S05H", "함수 종합(대단원 마무리)")):
    builder.SECTIONS[s] = ("5. 함수 92제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, MC, DRW = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "5지선다", "서술형(그래프 그리기)"
F1, F2, F3, R1, R2 = "함수", "합성함수", "역함수", "유리식과 유리함수", "무리식과 무리함수"
def secof(q): return "S05A" if q <= 9 else "S05B" if q <= 14 else "S05C" if q <= 22 else "S05D" if q <= 37 else "S05E" if q <= 48 else "S05F" if q <= 61 else "S05G" if q <= 75 else "S05H"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = secof(q)
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·그래프 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건식(수식 객체) 본문 미추출 — 해설로 조건 복원, 파일 정답 기준")
r(1, F1, "FUNC.DEFINITION.FORMULA_CHECK", "관계식 세우고 함수 판정", "함수의 뜻", "하", S, "(1) y=5000x, 함수 (2) y=πx², 함수", "식+판정", 2)
r(2, F1, "FUNC.VALUE.LINEAR", "함숫값 구하기", "함숫값", "하", S, "(1) 5 (2) 2", "값(소문항별)", 2)
r(3, F1, "FUNC.DEFINITION.ARROW_DIAGRAM", "대응도로 함수 판정·정의역·치역", "함수의 뜻;정의역과 치역", "하", S, "(1) 함수 아님(3의 대응 없음) (2) 정의역 {1,2,3,4}, 공역 {a,b,c}, 치역 {b,c} (3) 함수 아님(4가 2개에 대응)", "서술(소문항별)", 3, fig="그림", **FK)
r(4, F1, "FUNC.DOMAIN_RANGE.BASIC", "정의역과 치역", "정의역과 치역", "하", S, "(1) 실수 전체/실수 전체 (2) 실수 전체/{y|y≥1} (3) {x|x≠0}/{y|y≠0}", "집합(소문항별)", 3)
r(5, F1, "FUNC.EQUALITY.FINITE_DOMAIN", "서로 같은 함수 보이기", "서로 같은 함수", "하", PRF, "f(−1)=g(−1)=1, f(0)=g(0)=0, f(1)=g(1)=1 → f=g", "증명")
r(6, F1, "FUNC.GRAPH.DOMAIN_DEPENDENT", "정의역에 따른 그래프 그리기", "함수의 그래프", "하", DRW, "(1) 네 점 (−1,3),(0,1),(1,−1),(2,−3) (2) 직선 y=−2x+1", "그래프", 2, fig="그래프")
r(7, F1, "FUNC.GRAPH.VERTICAL_LINE_TEST", "함수의 그래프 판정", "함수의 그래프", "하", S, "(1), (3) 함수의 그래프; (2) 한 x에 y 2개", "서술", fig="그래프", **FK)
r(8, F1, "FUNC.BIJECTION.IDENTIFY", "일대일대응 찾기", "일대일대응", "하", S, "(1), (4)", "보기")
r(9, F1, "FUNC.BIJECTION.HORIZONTAL_LINE", "수평선 판정 이유 설명(활동)", "일대일대응", "하", ACT, "y=a와 두 점에서 만나면 x₁≠x₂인데 f(x₁)=f(x₂) → 일대일 아님", "서술", fig="그림")
r(10, F2, "COMPOSITE.VALUE.POLY", "합성함수의 함숫값", "합성함수", "하", S, "(1) −5 (2) −11 (3) −2 (4) 40", "값(소문항별)", 4)
r(11, F2, "COMPOSITE.FORMULA.LINEAR", "일차함수 합성(예제)", "합성함수", "하", S, "(1) −4x+11 (2) −4x+1", "식(소문항별)", 2)
r(12, F2, "COMPOSITE.FORMULA.POLY", "합성함수 식", "합성함수", "하", S, "(1) 4x²+4x+6 (2) 2x²+11 (3) 4x+3 (4) x⁴+10x²+30", "식(소문항별)", 4)
r(13, F2, "COMPOSITE.ASSOCIATIVE.VERIFY", "결합법칙 확인", "합성함수의 성질", "하", PRF, "양변 모두 (2x+9)²=4x²+36x+81", "증명")
r(14, F2, "COMPOSITE.ITERATE.PERIOD", "f(x)=1−x 반복 합성(탐구)", "합성함수", "중하", ACT, "(1) f∘f=x, f∘f∘f=1−x (2) n 짝수 x, n 홀수 1−x", "식", 2, i=M)
r(15, F3, "INVERSE.ARROW_DIAGRAM.VALUES", "대응도 완성·역함수 값", "역함수", "하", S, "(1) 3 (2) 1", "값(소문항별)", 2, fig="그림", **FK)
r(16, F3, "INVERSE.ARROW_DIAGRAM.VALUES", "대응도 역함수 값", "역함수", "하", S, "(1) 4 (2) 3 (3) 4", "값(소문항별)", 3, fig="그림", **FK)
r(17, F3, "INVERSE.LINEAR.FIND", "일차함수 역함수(예제)", "역함수 구하기", "하", S, "y=x/2−3/2", "식")
r(18, F3, "INVERSE.LINEAR.FIND", "일차함수 역함수", "역함수 구하기", "하", S, "(1) y=2x+10 (2) y=−x/3−4", "식(소문항별)", 2)
r(19, F3, "INVERSE.PROPERTIES.VERIFY", "(f∘g)⁻¹=g⁻¹∘f⁻¹, (f⁻¹)⁻¹=f 확인", "역함수의 성질", "중하", PRF, "(f∘g)⁻¹(x)=−x/8−7/8=(g⁻¹∘f⁻¹)(x); (f⁻¹)⁻¹(x)=4x+1", "증명", i=M)
r(20, F3, "INVERSE.GRAPH.SYMMETRY", "함수와 역함수 그래프", "역함수의 그래프", "하", DRW, "y=x 대칭 그래프: (1) y=(x+1)/3 (2) y=−2x+4", "그래프", 2, fig="그래프")
r(21, F2, "COMPOSITE.DISCOUNT.COMPARE", "할인 순서에 따른 가격 비교(활동)", "합성함수", "하", ACT, "매장 B", "서술", fig="표", **FK)
r(22, F2, "COMPOSITE.DISCOUNT.NONCOMMUTATIVE", "할인 합성함수 비교(활동)", "합성함수", "하", ACT, "g∘f=0.9x−3600, f∘g=0.9x−4000 → g∘f≠f∘g", "식+서술")
r(23, F1, "FUNC.DEFINITION.FINITE_SETS", "X→Y 함수인 것 고르기", "함수의 뜻", "하", S, "ㄱ, ㄴ, ㄹ", "보기", trap="치역 ⊂ 공역")
r(24, F1, "FUNC.TYPES.CLASSIFY", "일대일대응·항등·상수함수", "일대일대응;항등함수;상수함수", "하", S, "(1) ㄱ, ㄴ (2) ㄱ (3) ㄷ", "보기(소문항별)", 3)
r(25, F2, "COMPOSITE.FORMULA.LINEAR", "합성함수 식", "합성함수", "하", S, "(1) −3x−8 (2) −3x−16", "식(소문항별)", 2)
r(26, F3, "INVERSE.VALUE.LINEAR", "f⁻¹(5)", "역함수", "하", S, "2")
r(27, F3, "INVERSE.COMPOSITE.SIMPLIFY", "역함수 포함 합성 간단히", "역함수의 성질;합성함수", "중하", S, "1", c=M, i=M, trap="(g⁻¹∘f)⁻¹=f⁻¹∘g")
r(28, F1, "FUNC.BIJECTION.INTERVAL_ENDPOINTS", "구간 일대일대응 a, b", "일대일대응", "하", S, "a=3/2, b=−1/2", "값")
r(29, F2, "COMPOSITE.FIND_COEFFS", "합성 조건으로 a, b, c", "합성함수", "하", S, "a=2, b=3, c=−6", "값")
r(30, F2, "COMPOSITE.COMMUTE.FIND_K", "f∘g=g∘f인 k(서술형)", "합성함수", "하", D, "−1", "값")
r(31, F2, "COMPOSITE.SOLVE_FOR_H", "f∘h=g, h∘f=g인 h", "합성함수", "중하", S, "(1) h(x)=3x/2−1 (2) h(x)=3x/2−7/2", "식(소문항별)", 2, c=M)
r(32, F3, "INVERSE.SELF_INVERSE.LINEAR", "f=f⁻¹인 a", "역함수", "하", S, "−1", "값", trap="a=1이면 상수항 모순")
r(33, F3, "INVERSE.PIECEWISE.VALUE", "구간별 함수 합성·역함수 값", "역함수;합성함수", "중하", S, "7", c=M, d=M)
r(34, F3, "INVERSE.ARROW_DIAGRAM.COMPOSITE", "대응도 역함수 합성(서술형)", "역함수;합성함수", "중하", D, "3", fig="그림", **FK)
r(35, F2, "COMPOSITE.ITERATE.HALVING", "f^n(99)=1인 최소 n", "합성함수", "중", S, "7", c=M, i=M, **CK)
r(36, F2, "COMPOSITE.PIECEWISE_GRAPH", "그래프 합성 f∘g 그리기", "합성함수", "중", DRW, "풀이참조(구간별 f∘g 그래프)", "그래프", fig="그래프", final="풀이참조", d=M, i=M, **FK)
r(37, F3, "INVERSE.CONDITIONS.FINITE", "조건 만족 함수의 값", "역함수;일대일대응", "중", S, "5", d=M, i=M, **CK)
r(38, R1, "RATIONAL.INVERSE_PROPORTION.TABLE", "반비례 표 완성", "반비례", "하", S, "y=12/x (표 완성)", "식", fig="표")
r(39, R1, "TRANSLATION.GRAPH_EQUATION", "평행이동한 그래프 식(준비)", "평행이동", "하", S, "(1) y=−2x+1 (2) y=(x−1)²−2", "식(소문항별)", 2)
r(40, R1, "RATIONAL_EXPR.CLASSIFY", "다항식 아닌 유리식 찾기", "유리식", "하", S, "(x²+2x+3)/x, 2/(x−1), 1/2−1/x", "보기")
r(41, R1, "RATIONAL_EXPR.OPERATIONS", "유리식 계산(예제)", "유리식의 계산", "하", S, "(1) (2x−1)/((x+1)(x−2)) (2) (x+1)²", "식(소문항별)", 2)
r(42, R1, "RATIONAL_EXPR.OPERATIONS", "유리식 계산", "유리식의 계산", "하", S, "(1) 3/((x−1)(x−2)) (2) 1/(x(x−3))", "식(소문항별)", 2)
r(43, R1, "RATIONAL_FUNC.DOMAIN", "유리함수 정의역", "유리함수", "하", S, "(1) {x|x≠−3} (2) {x|x≠2}", "집합(소문항별)", 2)
r(44, R1, "RATIONAL_FUNC.GRAPH.BASIC", "y=k/x 그래프", "유리함수의 그래프", "하", DRW, "풀이참조(k>0: 1·3사분면, k<0: 2·4사분면)", "그래프", 4, fig="그래프", final="풀이참조")
r(45, R1, "RATIONAL_FUNC.GRAPH.ASYMPTOTES", "평행이동 꼴 그래프·점근선", "유리함수의 그래프;점근선", "하", DRW, "(1) x=−2, y=−1 (2) x=3, y=2", "그래프+식(소문항별)", 2, fig="그래프")
r(46, R1, "RATIONAL_FUNC.GRAPH.STANDARD_FORM", "(3x+1)/(x−1) 그래프·점근선(예제)", "유리함수의 그래프;점근선", "하", DRW, "y=4/(x−1)+3; 점근선 x=1, y=3", "그래프+식", fig="그래프")
r(47, R1, "RATIONAL_FUNC.GRAPH.STANDARD_FORM", "표준형 변형 그래프·점근선", "유리함수의 그래프;점근선", "중하", DRW, "(1) x=−2, y=−4 (2) x=1/2, y=3", "그래프+식(소문항별)", 2, fig="그래프", c=M)
r(48, R1, "RATIONAL_FUNC.CLASSIFY.COEFF_CONDITIONS", "(ax+b)/(cx+d) 종류 판정(탐구)", "유리함수", "중하", ACT, "1) 다항함수 2) 상수함수 3) c≠0, ad−bc≠0", "서술(소문항별)", 3, i=M)
r(49, R2, "IRRATIONAL_EXPR.REAL_CONDITION", "무리식이 실수일 x 범위", "무리식", "하", S, "(1) −3≤x≤2 (2) 0≤x<5", "부등식(소문항별)", 2, trap="분모 근호 >0")
r(50, R2, "IRRATIONAL_EXPR.RATIONALIZE", "무리식 간단히(예제)", "무리식의 계산", "하", S, "(1) x+1 (2) √(x+1)+√x", "식(소문항별)", 2)
r(51, R2, "IRRATIONAL_EXPR.RATIONALIZE", "무리식 간단히", "무리식의 계산", "중하", S, "(1) 2x (2) 2x²−1−2x√(x²−1)", "식(소문항별)", 2, c=M)
r(52, R2, "IRRATIONAL_FUNC.DOMAIN", "무리함수 정의역", "무리함수", "하", S, "(1) {x|x≤3} (2) {x|x≥−8/3}", "집합(소문항별)", 2)
r(53, R2, "IRRATIONAL_FUNC.GRAPH.REFLECTION", "y=√x 대칭이동 그래프", "무리함수의 그래프", "하", DRW, "풀이참조(x축·y축·원점 대칭)", "그래프", 3, fig="그래프", final="풀이참조")
r(54, R2, "IRRATIONAL_FUNC.GRAPH.BASIC", "y=±√(ax) 그래프", "무리함수의 그래프", "하", DRW, "풀이참조", "그래프", 4, fig="그래프", final="풀이참조")
r(55, R2, "IRRATIONAL_FUNC.GRAPH.TRANSLATED", "평행이동 무리함수 그래프", "무리함수의 그래프", "하", DRW, "풀이참조(시작점 (3,4), (−2,−2), (1,5), (−4,−1))", "그래프", 4, fig="그래프", final="풀이참조")
r(56, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "√(2x−6)+2 그래프·정의역·치역(예제)", "무리함수의 그래프", "하", DRW, "정의역 {x|x≥3}, 치역 {y|y≥2}", "그래프+집합", fig="그래프")
r(57, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "무리함수 그래프·정의역·치역", "무리함수의 그래프", "하", DRW, "(1) {x|x≤1}, {y|y≥−4} (2) {x|x≤3}, {y|y≤1}", "그래프+집합(소문항별)", 2, fig="그래프")
r(58, R2, "IRRATIONAL_FUNC.SIGNS_FROM_QUADRANTS", "지나는 사분면으로 부호 결정(탐구)", "무리함수의 그래프", "중", ACT, "1) (1) b>0, c>0 (2) b>0, c<0  2) a<0, b>0, c<0", "부호(소문항별)", 3, d=M, i=M)
r(59, R1, "RATIONAL_FUNC.CIPHER.ENCODE", "유리함수 암호 만들기(활동)", "일대일대응;유리함수", "하", ACT, "남: 7/3, 5/3, 19/9 / 여: 31/15, 17/9", "값", fig="표", **FK)
r(60, R1, "RATIONAL_FUNC.CIPHER.DECODE", "유리함수 암호 풀기(활동)", "일대일대응;유리함수", "하", ACT, "별과 바람", "서술", fig="표", **FK)
r(61, R1, "FUNC.CIPHER.CREATE", "새 암호 만들기(활동)", "일대일대응", "하", ACT, "풀이참조(예: f(x)=x√(x²+1) 대응)", "서술(개방형)", final="풀이참조", review="REVIEW-개방형")
r(62, R1, "RATIONAL_EXPR.OPERATIONS", "유리식 사칙 계산", "유리식의 계산", "중하", S, "(1) (x−2)/(x−1) (2) (x+1)/(x(x−1)) (3) (x+4)/((x+1)(x+2)) (4) (x−3)/((x+1)(x+3))", "식(소문항별)", 4, c=M)
r(63, R1, "RATIONAL_FUNC.GRAPH.DOMAIN_RANGE_ASYM", "유리함수 그래프·정의역·치역·점근선", "유리함수의 그래프;점근선", "하", DRW, "(1) {x|x≠−2}, {y|y≠1}, x=−2, y=1 (2) {x|x≠3}, {y|y≠2}, x=3, y=2", "그래프+집합(소문항별)", 2, fig="그래프")
r(64, R2, "IRRATIONAL_EXPR.RATIONALIZE_SUM", "무리식 합 간단히", "무리식의 계산", "하", S, "(a+b)/(a−b)")
r(65, R2, "IRRATIONAL_FUNC.GRAPH.DOMAIN_RANGE", "무리함수 그래프·정의역·치역", "무리함수의 그래프", "하", DRW, "(1) {x|x≤3}, {y|y≥2} (2) {x|x≥−2/3}, {y|y≤−1}", "그래프+집합(소문항별)", 2, fig="그래프")
r(66, R1, "RATIONAL_EXPR.PARTIAL_FRACTION_COEFF", "항등식 부분분수 계수", "유리식;항등식", "하", S, "a=4, b=4")
r(67, R1, "RATIONAL_FUNC.TRANSLATION.MATCH", "평행이동해 y=1/x와 겹치는 a, b, c", "유리함수의 그래프;평행이동", "중하", S, "a=3, b=1, c=−2", c=M)
r(68, R1, "RATIONAL_FUNC.GRAPH.READ_COEFFS", "그래프로 a, b, c", "유리함수의 그래프;점근선", "중하", S, "a=1, b=−4, c=−2", fig="그래프", **FK)
r(69, R1, "RATIONAL_FUNC.SELF_INVERSE", "f=f⁻¹·점 통과로 a, b", "유리함수;역함수", "중", S, "a=−3, b=−10", d=M, i=M, trap="f=f⁻¹ ⇔ 점근선 교점이 y=x 위(a=−3)")
r(70, R2, "IRRATIONAL_EXPR.SUBSTITUTE_VALUE", "x=(√2+1)/(√2−1) 대입 값", "무리식의 계산", "중하", S, "2√2", c=M)
r(71, R2, "IRRATIONAL_FUNC.GRAPH.READ_COEFFS", "그래프로 a, b, c", "무리함수의 그래프", "중하", S, "a=4, b=4, c=−2", fig="그래프", **FK)
r(72, R2, "IRRATIONAL_FUNC.INVERSE_CONDITIONS", "f(3)=5, g(3)=5인 a, b(서술형)", "무리함수;역함수", "중하", D, "a=−8, b=49")
r(73, R1, "RATIONAL_FUNC.MIN_DISTANCE_CENTER", "점근선 교점 중심 원 넓이 최소", "유리함수의 그래프;산술기하평균", "중상", S, "6π", c=M, d=M, i=H, trap="X²+9/X²≥6")
r(74, R1, "RATIONAL_FUNC.BOUNDING_LINES", "직선 사이 끼임 조건 a−b 최댓값(서술형)", "유리함수의 그래프", "상", D, "−5/12", c=M, d=H, i=H, fig="그래프")
r(75, R2, "IRRATIONAL_FUNC.LINE_NO_INTERSECT", "그래프와 직선이 만나지 않는 최소 m", "무리함수의 그래프", "중", S, "4", d=M, i=M, trap="끝점 (2,5) 통과 m=3 제외")
r(76, F1, "FUNC.DEFINITION.FINITE_SETS", "X→Y 함수 고르기", "함수의 뜻", "하", MC, "③", "선택지번호", final="③")
r(77, F1, "FUNC.EQUALITY.FINITE_DOMAIN", "f=g인 a, b", "서로 같은 함수", "하", S, "a=2, b=−4")
r(78, F1, "FUNC.BIJECTION.PIECEWISE_SLOPE", "구간별 함수 일대일대응 조건", "일대일대응", "중하", S, "a>3", d=M)
r(79, F1, "FUNC.BIJECTION.GRAPH_CHOICE", "일대일대응 그래프 고르기", "일대일대응", "하", MC, "①", "선택지번호", fig="그래프", final="①", **FK)
r(80, R1, "RATIONAL_FUNC.TRANSLATION.MATCH", "평행이동 p, q", "유리함수의 그래프;평행이동", "하", S, "p=−2, q=1")
r(81, R1, "RATIONAL_FUNC.PROPERTIES.STATEMENTS", "유리함수 그래프 보기 판정", "유리함수의 그래프", "중하", MC, "⑤", "선택지번호", final="⑤", d=M, trap="x∈(−1/4,0)에서 제2사분면 통과")
r(82, R1, "RATIONAL_FUNC.ITERATE.PERIOD3", "f^1001(2)", "합성함수;유리함수", "중", S, "1/2", i=M)
r(83, R1, "RATIONAL_FUNC.INVERSE.VALUE", "역함수 g(−3)", "유리함수;역함수", "하", S, "12")
r(84, R2, "IRRATIONAL_FUNC.PROPERTIES.FALSE_STATEMENT", "무리함수 설명 중 옳지 않은 것", "무리함수의 그래프;역함수", "중하", MC, "③", "선택지번호", final="③", d=M)
r(85, R2, "IRRATIONAL_FUNC.MAX_MIN.INTERVAL", "최댓값으로 a 구해 최솟값", "무리함수", "하", S, "5")
r(86, R1, "INVERSE.COMPOSITE.RATIONAL_IRRATIONAL", "역함수 합성 값 합", "역함수;유리함수;무리함수", "중하", S, "8", c=M)
r(87, F1, "FUNC.BIJECTION.ABS_SLOPE_SIGNS", "|x−1|+ax+1 일대일대응 조건(서술형)", "일대일대응", "중", D, "a<−1 또는 a>1", d=M, i=M)
r(88, F2, "COMPOSITE.COMMUTE.FIXED_POINT", "f∘g=g∘f일 때 지나는 정점(서술형)", "합성함수", "중", D, "(1, 1)", i=M)
r(89, R1, "RATIONAL_FUNC.SYMMETRY_LINES", "두 직선 대칭 조건으로 a, b(서술형)", "유리함수의 그래프", "중", D, "a=1, b=3", i=M)
r(90, R2, "IRRATIONAL_FUNC.INVERSE_INTERSECTION", "함수·역함수 교점 거리(서술형)", "무리함수;역함수", "중", D, "√2", d=M)
r(91, F1, "FUNC.CORRESPONDENCE.REAL_LIFE", "대응 사례 조사(활동)", "함수의 뜻", "하", ACT, "예시참조(자판기 등)", "서술(개방형)", final="예시참조", review="REVIEW-개방형")
r(92, F1, "FUNC.CORRESPONDENCE.QR_CODE", "QR코드 만들기(활동)", "함수의 뜻", "하", ACT, "예시참조", "서술(개방형)", final="예시참조", review="REVIEW-개방형")
for i in range(10): build(f"Batch{467+i}", ROWS[i*10:(i+1)*10], 13095+i*10)
print(len(ROWS))
