from cfgy2 import *
import cfgy2, builder
SQ = hashlib.sha256(open(OUT+'h66/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y66.json'))
setup(QID="A02466", SRC="1mb_OXUU0Np3Daetg_ZD-z3qdsyq5KABd", SHA=SQ, TAG="YMSS06", N=60, SUBJ="수학(하)", SEC="S06A",
      FNAME="06 경우의 수(신사고) 60제.hwp", UNIT="Ⅵ. 경우의 수", BIG="Ⅵ. 경우의 수", EXAM="6. 경우의 수 60제", MID="경우의 수")
cfgy2.P.update(BOOK="신사고 수학(하)", GRADE="고1")
for s, mid in (("S06A", "경우의 수(합·곱의 법칙)"), ("S06B", "순열"), ("S06C", "조합"), ("S06D", "경우의 수 종합(중단원 마무리)"), ("S06E", "경우의 수 종합(대단원 마무리)")):
    builder.SECTIONS[s] = ("6. 경우의 수 60제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)"
K1, K2, K3 = "합의 법칙과 곱의 법칙", "순열", "조합"
def secof(q): return "S06A" if q <= 12 else "S06B" if q <= 21 else "S06C" if q <= 31 else "S06D" if q <= 45 else "S06E"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = secof(q)
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·자료 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
r(1, K1, "COUNT.BASIC.DIE_ODD", "주사위 홀수 눈(준비)", "경우의 수", "하", S, "3")
r(2, K1, "COUNT.SUM_RULE.MULTIPLES", "3 또는 4의 배수(준비)", "합의 법칙", "하", S, "5")
r(3, K1, "COUNT.PRODUCT_RULE.COIN_DIE", "동전과 주사위(준비)", "곱의 법칙", "하", S, "12")
r(4, K1, "COUNT.SUM_RULE.DICE_SUM", "두 주사위 합 6 또는 10", "합의 법칙", "하", S, "8")
r(5, K1, "COUNT.SUM_RULE.MENU", "메뉴 한 가지 택하기", "합의 법칙", "하", S, "9", fig="그림")
r(6, K1, "COUNT.PRODUCT_RULE.DIGIT_CONDITIONS", "자릿수 조건 두 자리 수", "곱의 법칙", "하", S, "(1) 25 (2) 12", "값(소문항별)", 2)
r(7, K1, "COUNT.PRODUCT_RULE.CHOOSE_EACH", "오름·휴양림 한 곳씩", "곱의 법칙", "하", S, "20")
r(8, K1, "COUNT.DIVISORS.PRIME_FACTOR", "108의 약수 개수(예제)", "곱의 법칙;약수의 개수", "하", S, "12")
r(9, K1, "COUNT.DIVISORS.PRIME_FACTOR", "144, 360 약수 개수", "곱의 법칙;약수의 개수", "하", S, "(1) 15 (2) 24", "값(소문항별)", 2)
r(10, K1, "COUNT.SUM_PRODUCT.PATHS_ACTIVITY", "산책로 경로 합·곱의 법칙(활동)", "합의 법칙;곱의 법칙", "하", ACT, "(1) 9, 8 (2) 17 (3) 동시에 일어나지 않으면 합의 법칙, 동시에/잇달아 일어나면 곱의 법칙", "값+서술", 3, fig="그림", **FK)
r(11, K1, "COUNT.COLORING.MAP_ORDER", "지도 5영역 색칠(활동)", "곱의 법칙;색칠 문제", "중", ACT, "(1) (마) (2) 420", "값+서술", 2, fig="그림", d=M, i=M, **FK)
r(12, K1, "COUNT.COLORING.REGIONS", "인접 영역 다른 색 칠하기", "곱의 법칙;색칠 문제", "중", S, "(1) 180 (2) 540", "값(소문항별)", 2, fig="그림", d=M, **FK)
r(13, K2, "PERM.NPR.EVALUATE", "nPr 값", "순열", "하", S, "(1) 42 (2) 120 (3) 720 (4) 9", "값(소문항별)", 4)
r(14, K2, "PERM.NPR.CONTEXT", "놀이 기구 3개 순서 고려", "순열", "하", S, "990")
r(15, K2, "PERM.IDENTITY.NPR_RECURSION", "nPr=n·n−1Pr−1 증명", "순열", "하", PRF, "증명(계승 정리)", "증명", final="풀이참조")
r(16, K2, "PERM.IDENTITY.NPR_PASCAL", "nPr=n−1Pr+r·n−1Pr−1 증명", "순열", "중하", PRF, "증명(통분 후 n(n−1)!/(n−r)!)", "증명", final="풀이참조", i=M)
r(17, K2, "PERM.DIGITS.NO_LEADING_ZERO", "0 포함 세 자리 수(예제)", "순열", "하", S, "18", trap="맨 앞 0")
r(18, K2, "PERM.DIGITS.EVEN_GREATER", "짝수·30000보다 큰 수", "순열", "하", S, "(1) 48 (2) 72", "값(소문항별)", 2)
r(19, K2, "PERM.ARRANGE.VOWELS", "friend 모음 양 끝·이웃(예제)", "순열", "하", S, "(1) 48 (2) 240", "값(소문항별)", 2)
r(20, K2, "PERM.ARRANGE.ENDS_ALTERNATE", "화분 양 끝·번갈아", "순열", "하", S, "(1) 720 (2) 144", "값(소문항별)", 2, trap="라벤더가 양 끝")
r(21, K2, "PERM.ARRANGE.BLOCKS", "같은 종류끼리 이웃", "순열", "하", S, "144", c=M)
r(22, K3, "COMB.NCR.EVALUATE", "nCr 값", "조합", "하", S, "(1) 120 (2) 21 (3) 1 (4) 1", "값(소문항별)", 4)
r(23, K3, "COMB.NCR.CONTEXT", "아이스크림 3가지 맛", "조합", "하", S, "84")
r(24, K3, "COMB.IDENTITY.SYMMETRY", "nCr=nCn−r 증명", "조합", "하", PRF, "증명", "증명", final="풀이참조")
r(25, K3, "COMB.SYMMETRY.SOLVE", "nCr 등식 만족 n, r", "조합", "하", S, "(1) n=7 (2) r=6", "값(소문항별)", 2, trap="r=r−3 불가")
r(26, K3, "COMB.IDENTITY.SUBSET_OF_SUBSET", "nCr·rCk=nCk·n−kCr−k 증명", "조합", "중하", PRF, "증명", "증명", final="풀이참조", i=M)
r(27, K3, "COMB.PRODUCT.GROUPS", "학년별 선발(예제)", "조합;곱의 법칙", "하", S, "350")
r(28, K3, "COMB.PRODUCT.GROUPS", "파트별 선발", "조합;곱의 법칙", "하", S, "360")
r(29, K3, "COMB.GEOMETRY.PARALLELOGRAMS", "평행선 평행사변형 개수", "조합", "하", S, "60", fig="그림", review="REVIEW-그림판독")
r(30, K3, "COMB.TOURNAMENT.FIVE_TEAMS", "5팀 토너먼트 대진표(활동)", "조합", "중하", ACT, "(1) 10 (2) 3 (3) 30", "값(소문항별)", 3, fig="그림", d=M)
r(31, K3, "COMB.TOURNAMENT.SIX_TEAMS", "6팀 토너먼트 대진표(활동)", "조합", "중", ACT, "(1) 15 (2) 3 (3) 45", "값(소문항별)", 3, fig="그림", d=M, trap="같은 크기 조 나눔 ÷2!")
r(32, K1, "COUNT.SUM_RULE.DIGIT_SUM", "자리 숫자 합 4 또는 7", "합의 법칙", "하", S, "11")
r(33, K1, "COUNT.PAYMENT.AMOUNTS", "지불 금액의 수", "곱의 법칙", "중하", S, "29", trap="0원 제외, 금액 중복 여부", d=M)
r(34, K2, "PERM.NPR.WORD", "STORY 3개 나열", "순열", "하", S, "60")
r(35, K3, "COMB.HANDSHAKE", "악수 횟수", "조합", "하", S, "45")
r(36, K3, "PERM_COMB.SOLVE_N", "nPr·nCr 방정식", "순열;조합", "하", S, "(1) 10 (2) 5 (3) 5 (4) 6", "값(소문항별)", 4)
r(37, K1, "COUNT.ORDERED_PAIRS.ABS_DIFF", "|a−b|≤1 순서쌍(서술형)", "합의 법칙", "하", D, "10")
r(38, K1, "COUNT.PRODUCT_RULE.EXPANSION_TERMS", "전개식 항의 개수", "곱의 법칙", "하", S, "(1) 12 (2) 12", "값(소문항별)", 2)
r(39, K2, "PERM.ARRANGE.FAMILY_PHOTO", "가족사진 배열", "순열", "중하", S, "(1) 144 (2) 1440 (3) 720", "값(소문항별)", 3, c=M)
r(40, K3, "COMB.SUBSET.MUST_INCLUDE_ATLEAST", "부분집합 조건 개수", "조합;여사건", "하", S, "(1) 56 (2) 74", "값(소문항별)", 2)
r(41, K3, "COMB.GEOMETRY.TRIANGLE_POINTS", "삼각형 위 7개 점 직선·삼각형", "조합", "중", S, "(1) 12 (2) 29", "값(소문항별)", 2, fig="그림", d=M, **FK)
r(42, K2, "PERM_COMB.LOCK_PASSWORDS", "순서 무관/유관 비밀번호", "순열;조합", "하", S, "A: ₆C₃=20, B: ₆P₃=120", "값(소문항별)", 2)
r(43, K2, "PERM.DICTIONARY_ORDER", "사전식 배열 순위", "순열", "중", S, "(1) 42번째 (2) ebdca", "값(소문항별)", 2, c=M, i=M)
r(44, K3, "PERM_COMB.FUNCTIONS.INJECTIVE_INCREASING", "일대일·증가함수 개수", "순열;조합;함수", "중하", S, "(1) 360 (2) 15", "값(소문항별)", 2)
r(45, K3, "COMB.SHOES.EXACTLY_ONE_PAIR", "구두 한 켤레만 짝(서술형)", "조합", "중", D, "240", d=M, i=M)
r(46, K1, "COUNT.ORDERED_PAIRS.LINEAR_INEQ", "3x+y≤10 자연수 순서쌍", "합의 법칙", "하", S, "12")
r(47, K1, "COUNT.SUM_RULE.DICE_EVEN_SUM", "두 주사위 합 짝수", "합의 법칙;곱의 법칙", "하", S, "18")
r(48, K2, "PERM.COLORING.ALL_DIFFERENT", "네 영역 모두 다른 색", "순열", "하", S, "24", fig="그림")
r(49, K2, "PERM.DIGITS.GREATER_THAN", "23000보다 큰 수", "순열", "중하", S, "60", d=M)
r(50, K2, "PERM.ARRANGE.COUPLES_ADJ", "부부끼리 이웃", "순열", "하", S, "48")
r(51, K3, "PERM_COMB.SOLVE_N_R", "nPr·nCr 조건으로 n, r", "순열;조합", "하", S, "n=6, r=3", "값", final="n=6, r=3", review="REVIEW-조건미추출", chk="조건식(수식 객체) 본문 미추출 — 해설(nPr=120, nCr=20)로 복원; 파일 정답 'n=6'(r=3은 해설)")
r(52, K3, "COMB.ERROR_ANALYSIS.ORDERED_BY_HEIGHT", "키 순서 세우기 오류 찾기", "조합", "하", D, "₅P₃가 아니라 ₅C₃=10 (순서가 키로 정해짐)", "값+서술", final="10")
r(53, K3, "COMB.PRODUCT.BADMINTON_TEAMS", "배드민턴 종목별 출전", "조합;곱의 법칙", "중", S, "900", d=M)
r(54, K2, "PERM.DIGITS.MULTIPLE_OF_5", "5의 배수 네 자리(서술형)", "순열", "중하", D, "42", trap="0 끝/5 끝 분리")
r(55, K2, "PERM.ARRANGE.ALTERNATE", "남녀 교대 서기(서술형)", "순열", "하", D, "72")
r(56, K3, "COMB.GEOMETRY.SEMICIRCLE_QUADS", "반원 위 9점 사각형(서술형)", "조합", "중", D, "81", fig="그림", d=M, **FK)
r(57, K3, "COMB.PARTITION.DISTINCT_SIZES", "문제별 학생 수 모두 다름(서술형)", "조합;순열", "중", D, "360", d=M, i=M)
r(58, K1, "COUNT.PRODUCT_RULE.LICENSE_PLATES", "번호판 개수(자료 활용)", "곱의 법칙", "중하", ACT, "(1) 22080000 (2) 100000", "값(소문항별)", 2, fig="표", **FK)
r(59, K1, "COUNT.PRODUCT_RULE.RENTAL_PLATES", "렌터카 승용차 최대 대수(자료 활용)", "곱의 법칙", "중하", ACT, "2070000", fig="표", **FK)
r(60, K1, "COUNT.CODES.INVESTIGATION", "고유 번호 부여 방식 탐구", "곱의 법칙", "하", ACT, "예시참조(주민 등록 번호 검증 번호 원리 등)", "서술(개방형)", final="예시참조", review="REVIEW-개방형")
for i in range(6): build(f"Batch{461+i}", ROWS[i*10:(i+1)*10], 13035+i*10)
print(len(ROWS))
