from rows84a import *
r(119, Q1, "DERIV.QUOTIENT_CHAIN.MIXED", "몫·합성 미분 종합(중단원 마무리)", "몫의 미분법;합성함수의 미분법", "중하", S, "(1) y′=−(2x²+4x−1)/(2x²+1)² (2) y′=(1−x ln x+2x)/(xeˣ) (3) y′=8(3x²−2)(2x³−4x+1)³ (4) y′=sin x/(2√(1−cos x))", "식(소문항별)", 4, c=M)
r(120, Q3, "PARAM.DERIV.BASIC", "매개변수 함수 dy/dx(중단원 마무리)", "매개변수로 나타낸 함수의 미분법", "하", S, "(1) 2t (2) −32(t+1)³", "식(소문항별)", 2)
r(121, Q4, "IMPLICIT.DERIV.GENERAL", "음함수 미분(중단원 마무리)", "음함수의 미분법", "하", S, "(1) 4x/(3y) (y≠0) (2) (y−2xy²)/x", "식(소문항별)", 2, c=M)
r(122, Q4, "INVERSE.DERIV.RADICAL", "역함수 미분법으로 거듭제곱근 도함수(중단원 마무리)", "역함수의 미분법", "하", S, "(1) 1/(6⁶√((x+3)⁵)) (2) 2/(3∛((2x−5)²))", "식(소문항별)", 2)
r(123, Q5, "SECOND_DERIV.PRODUCT_QUOTIENT", "이계도함수(중단원 마무리)", "이계도함수", "중하", S, "(1) y″=−1/(2x√(2x)) (2) y″=6cos3x−9x sin3x (3) y″=(x²−4x+2)e^(−x) (4) y″=−1/x", "식(소문항별)", 4, c=M)
r(124, Q1, "DERIV.QUOTIENT.SYMMETRIC_DIFFERENCE_LIMIT", "대칭 차분 극한=2f′(1)", "미분계수의 정의;몫의 미분법", "중하", S, "−30", c=M, d=M, trap="계수 2")
r(125, Q1, "DERIV.QUOTIENT.SIGN_INEQUALITY", "f′(x)>0 범위(유리함수)", "몫의 미분법;이차부등식", "중하", S, "x<−1 또는 x>4", "범위", c=M, combo="미분+부등식")
r(126, Q2, "DERIV.CHAIN.PARAM_FROM_VALUE", "합성 미분계수 조건으로 a", "합성함수의 미분법", "하", S, "3")
r(127, Q2, "DERIV.CHAIN.COMPOSITE_VALUE", "h=f∘g의 h′(−1)", "합성함수의 미분법;몫의 미분법", "중하", D, "3/25", c=M, d=M)
r(128, Q3, "PARAM.DERIV.VALUE_AT_T", "t=1에서 dy/dx 값", "매개변수로 나타낸 함수의 미분법", "하", S, "2")
r(129, Q4, "IMPLICIT.DERIV.APPLIED_PENDULUM", "진자 주기 dT/dL(실생활)", "음함수의 미분법;실생활", "중하", S, "π/9.8", c=M, combo="미분+실생활")
r(130, Q4, "IMPLICIT.DERIV.UNDETERMINED_COEFF", "곡선 위 점·기울기 조건으로 a+b", "음함수의 미분법;미정계수", "중하", S, "−10", c=M, d=M)
r(131, Q4, "INVERSE.DERIV.VALUE_PRODUCT", "7f′(0)g′(6) 값", "역함수의 미분법", "중하", S, "1", d=M, trap="g(6)=1 먼저")
r(132, Q5, "SECOND_DERIV.UNDETERMINED_COEFF_IDENTITY", "f″+f=x sin x 항등식 계수", "이계도함수;항등식", "중", S, "a=−1/4, b=0, c=0, d=1/4", "값(4개)", c=H, d=M, i=M, combo="미분+항등식")
r(133, Q2, "DERIV.CHAIN.POLY_REMAINDER", "f∘g 조건과 (x−e)² 나눈 나머지", "합성함수의 미분법;나머지정리", "중", S, "−e", c=M, d=M, i=H, combo="합성미분+다항식 나눗셈", trap="R(x)=f(e)+f′(e)(x−e)")
r(134, Q3, "PARAM.DERIV.SERIES_SUM_AT_T1", "다항 매개변수 함수 t=1 dy/dx(합 계산)", "매개변수로 나타낸 함수의 미분법;등차수열의 합", "중", S, "101/100", c=M, i=M, combo="매개변수미분+수열")
r(135, Q4, "INVERSE.DERIV.FROM_LIMIT", "극한 조건으로 g′(2)", "역함수의 미분법;미분계수의 정의", "중하", S, "3", d=M, i=M)
r(136, Q5, "SECOND_DERIV.UNDETERMINED_COEFF_EXP", "f′(0)=1, f″(0)=2로 a, b", "이계도함수;지수함수의 도함수", "중하", S, "a=1, b=0", "값(2개)", c=M, d=M)
r(137, U1, "DERIV.TRIG.VALUE_PREP", "sin x 미분계수(준비)", "미분계수", "하", S, "√3/2")
r(138, U1, "TANGENT.AT_POINT.INTUITION", "cos x 위 점 접선(생각 열기)", "접선의 방정식", "하", ACT, "(1) −1 (2) y=−x+π/2", "값·식", 2, fig="그래프")
r(139, U1, "TANGENT.AT_POINT.BASIC", "곡선 위 점 접선(예제)", "접선의 방정식", "하", S, "y=(1/4)x+1", "식")
r(140, U1, "TANGENT.AT_POINT.BASIC", "곡선 위 점 접선", "접선의 방정식;여러 가지 함수의 미분", "하", S, "(1) y=−3x+4 (2) y=(1/e)x+1/e (3) y=(1/e)x (4) y=(1/2)x+(3√3−π)/6", "식(소문항별)", 4)
r(141, U1, "TANGENT.GIVEN_SLOPE.BASIC", "기울기 e인 ln x 접선(예제)", "접선의 방정식", "하", S, "y=ex−2", "식")
r(142, U1, "TANGENT.GIVEN_SLOPE.BASIC", "기울기 1인 접선", "접선의 방정식", "하", S, "(1) y=x (2) y=x+1 (3) y=x−1+ln3 (4) y=x+(3√3−π)/6", "식(소문항별)", 4, c=M)
r(143, U1, "TANGENT.GIVEN_SLOPE.PARAM", "직선이 y=x+cos x에 접할 a", "접선의 방정식", "중하", S, "(6√3+π)/12", d=M)
r(144, U1, "TANGENT.FROM_EXTERNAL_POINT.BASIC", "원점에서 eˣ에 그은 접선(예제)", "접선의 방정식;곡선 밖의 점", "하", S, "y=ex", "식", d=M)
r(145, U1, "TANGENT.FROM_EXTERNAL_POINT.BASIC", "곡선 밖 점에서 그은 접선", "접선의 방정식;곡선 밖의 점", "중하", S, "(1) y=−x+2 (2) y=(1/2)x (3) y=−e²x−e² (4) y=(1/e³)x+2", "식(소문항별)", 4, c=M, d=M)
r(146, U1, "TANGENT.CIRCLE.PARAM_VS_IMPLICIT", "원의 접선(매개변수·음함수, 탐구)", "접선의 방정식;매개변수 미분;음함수 미분", "중하", "서술형(탐구)", "두 방법 모두 x₁x+y₁y=r², 결과가 같다", "식", 3, i=M, combo="매개변수+음함수")
r(147, U1, "TANGENT.NEWTON_METHOD", "뉴턴 방법으로 실근 어림값(탐구)", "접선의 방정식;뉴턴 방법", "중", "서술형(탐구)", "∛2≈1.26", "값", i=M, chk="독립풀이(x³−2=0 뉴턴 반복) 일치")
r(148, U2, "EXTREMA.CUBIC.PREP", "삼차함수 극값 x(준비)", "함수의 극대와 극소", "하", S, "x=1, x=3")
r(149, U2, "MONOTONIC.DERIV_GRAPH.READ", "f′ 그래프로 증감·극값(생각 열기)", "함수의 증가와 감소;극값", "하", ACT, "(1) 증가 (0,2), 감소 (−∞,0), (2,∞) (2) x=0, x=2", "구간·값", 2, fig="그래프")
r(150, U2, "MONOTONIC.EXP_LOG.INTERVALS", "지수·로그 함수 증감 조사", "함수의 증가와 감소", "하", S, "(1) (0,1]에서 증가, [1,∞)에서 감소 (2) (−∞,1]에서 증가, [1,∞)에서 감소", "구간(소문항별)", 2)
r(151, U2, "EXTREMA.FIRST_DERIV.IRRATIONAL", "x√(x+3) 극값(예제)", "함수의 극대와 극소;무리함수의 미분", "하", S, "극솟값 −2", d=M)
r(152, U2, "EXTREMA.FIRST_DERIV.EXP_LOG", "x ln x, x²e^(−x) 극값", "함수의 극대와 극소", "중하", S, "(1) 극솟값 −1/e (2) 극댓값 4/e², 극솟값 0", "값(소문항별)", 2, c=M)
r(153, U2, "EXTREMA.SECOND_DERIV_TEST.DERIVE", "이계도함수 판정법 설명(빈칸)", "이계도함수를 이용한 극값 판정", "하", "빈칸채우기", "(1) 음, 양, 극소 (2) 양, 음, 극대", "서술")
r(154, U2, "EXTREMA.SECOND_DERIV_TEST.BASIC", "이계도함수로 x+1/x 극값(예제)", "이계도함수를 이용한 극값 판정", "하", S, "극댓값 −2, 극솟값 2", trap="극댓값<극솟값")
r(155, U2, "EXTREMA.SECOND_DERIV_TEST.BASIC", "이계도함수로 극값", "이계도함수를 이용한 극값 판정", "중하", S, "(1) 극댓값 1, 극솟값 −1 (2) 극솟값 2 (3) 극솟값 −1/(2e) (4) 극댓값 7π/6+√3, 극솟값 11π/6−√3", "값(소문항별)", 4, c=M, d=M)
r(156, U2, "CONCAVITY.SECOND_DERIV.BASIC", "오목·볼록 조사(예제)", "곡선의 오목과 볼록", "하", S, "x³−3x²+1: (−∞,1) 위로 볼록, (1,∞) 아래로 볼록; tan x: (−π/2,0) 위로 볼록, (0,π/2) 아래로 볼록", "구간", 2, final="풀이 참조", chk="독립풀이(f″ 부호) 일치")
r(157, U2, "CONCAVITY.SECOND_DERIV.BASIC", "오목·볼록 조사", "곡선의 오목과 볼록", "중하", S, "(1) (−1,1) 아래로 볼록, (−∞,−1)·(1,∞) 위로 볼록 (2) (0,π) 아래로 볼록, (π,2π) 위로 볼록", "구간(소문항별)", 2, c=M)
r(158, U2, "INFLECTION.POLY.BASIC", "사차함수 변곡점(예제)", "변곡점", "하", S, "(−1,−6), (1,−6)", "좌표")
r(159, U2, "INFLECTION.POLY_EXP.BASIC", "변곡점 좌표", "변곡점", "하", S, "(1) (0,−1), (2,−17) (2) (−2,−2/e²)", "좌표(소문항별)", 2)
r(160, U2, "GRAPH_SKETCH.POLY", "사차함수 그래프 개형(예제)", "함수의 그래프;증감표", "중하", "서술형(그래프)", "그래프(극솟값 f(−1)=0, 변곡점 x=0, −2/3)", "그래프", fig="그래프(답)", final="풀이 참조(그래프)", i=M)
r(161, U2, "GRAPH_SKETCH.POLY", "다항함수 그래프 개형", "함수의 그래프;증감표", "중하", "서술형(그래프)", "그래프(풀이 참조)", "그래프", 2, fig="그래프(답)", final="풀이 참조(그래프)", i=M)
r(162, U2, "GRAPH_SKETCH.RATIONAL", "x/(x²+1) 그래프 개형(예제)", "함수의 그래프;점근선", "중", "서술형(그래프)", "극댓값 1/2(x=1), 극솟값 −1/2(x=−1), 점근선 y=0", "그래프", fig="그래프(답)", final="풀이 참조(그래프)", i=M)
r(163, U2, "GRAPH_SKETCH.RATIONAL_EXP_LOG_TRIG", "여러 가지 함수 그래프 개형", "함수의 그래프;점근선;변곡점", "중", "서술형(그래프)", "그래프(풀이 참조)", "그래프", 4, fig="그래프(답)", final="풀이 참조(그래프)", c=M, i=M)
r(164, U2, "MAXMIN.CLOSED_INTERVAL.EXP", "xe^(−x) 최대·최소(예제)", "함수의 최대와 최소", "하", S, "최댓값 1/e, 최솟값 0")
r(165, U2, "MAXMIN.CLOSED_INTERVAL.EXP_TRIG", "닫힌구간 최대·최소", "함수의 최대와 최소", "중하", S, "(1) 최댓값 e²−2, 최솟값 1 (2) 최댓값 √2, 최솟값 −1", "값(소문항별)", 2, d=M, trap="끝값 비교")
r(166, U2, "MAXMIN.GEOMETRY.TRAPEZOID_IN_SEMICIRCLE", "반원 내접 사다리꼴 넓이 최대(탐구)", "함수의 최대와 최소;삼각함수의 미분", "중", "서술형(탐구)", "S(θ)=(1+cosθ)sinθ (0<θ<π/2), 최댓값 3√3/4", "식·값", 2, fig="그림", c=M, i=M, combo="최대최소+도형")
r(167, U2, "MAXMIN.APPLIED.DRUG_CONCENTRATION", "주사약 농도 최대 시각(실생활)", "함수의 최대와 최소;실생활", "하", ACT, "2시간", combo="최대최소+실생활")
r(168, U2, "MAXMIN.APPLIED.PH", "입안 pH 최저 시각(실생활)", "함수의 최대와 최소;실생활", "하", ACT, "5분", fig="표", combo="최대최소+실생활")
r(169, U3, "EQUATION.ROOT_COUNT.CUBIC_PREP", "삼차방정식 실근 개수(준비)", "방정식의 실근의 개수", "하", S, "1")
r(170, U3, "EQUATION.ROOT_COUNT.GRAPH_INTUITION", "그래프로 실근 개수(생각 열기)", "방정식의 실근의 개수;그래프", "하", ACT, "(1) 1 (2) 2", "값(소문항별)", 2, fig="그래프")
r(171, U3, "EQUATION.ROOT_COUNT.LOG", "ln x−3x=−3 실근 개수(예제)", "방정식의 실근의 개수", "하", S, "2", d=M)
r(172, U3, "EQUATION.ROOT_COUNT.EXP_TRIG", "실근 개수", "방정식의 실근의 개수", "중하", S, "(1) 1 (2) 1", "값(소문항별)", 2, d=M)
r(173, U3, "EQUATION.ROOT_COUNT.PARAM_K", "k에 따른 실근 개수", "방정식의 실근의 개수;그래프와 직선", "중", S, "(1) k<−5/4: 0, k=−5/4: 1, −5/4<k≤−1: 2, k>−1: 1 (2) k<0 또는 k=e: 1, 0≤k<e: 0, k>e: 2", "범위별 개수", 2, c=M, d=H, i=M, trap="끝점 x=−1 포함 여부", chk="독립풀이 일치(파일 답은 일부만 추출됨)")
r(174, U3, "INEQUALITY.PROOF.EXP_LINEAR", "eˣ≥x+1 증명(예제)", "부등식의 증명;최솟값", "하", PRF, "f(x)=eˣ−x−1의 최솟값 f(0)=0 ≥ 0", "증명", final="풀이 참조")
r(175, U3, "INEQUALITY.PROOF.MONOTONIC", "x>sin x, x>ln(1+x) 증명", "부등식의 증명;증가함수", "중하", PRF, "f(x)=x−sin x, x−ln(1+x)가 증가, f(0)=0", "증명", 2, i=M, final="풀이 참조")
r(176, U3, "INEQUALITY.PARAM_K.MIN_VALUE", "x ln x≥x+k 성립 k 범위", "부등식의 활용;최솟값", "중하", S, "k≤−1", "범위", d=M)
r(177, U4, "SECOND_DERIV.TRIG_PREP", "cos2t 도함수·이계도함수(준비)", "이계도함수", "하", S, "(1) −2sin2t (2) −4cos2t", "식(소문항별)", 2)
r(178, U4, "VELOCITY.LINE.INTUITION_FIREWORK", "폭죽 속도·가속도(생각 열기)", "속도와 가속도", "하", ACT, "속도 20 m/s, 가속도 −10 m/s²", "값", combo="미분+실생활")
r(179, U4, "VELOCITY.LINE.TRIG", "수직선 위 점 속도·가속도(예제)", "직선 운동의 속도와 가속도", "하", S, "속도 −√2, 가속도 0", "값")
r(180, U4, "VELOCITY.LINE.EXP_TRIG", "수직선 위 점 속도·가속도", "직선 운동의 속도와 가속도", "하", S, "속도 e^(π/2), 가속도 0", "값")
r(181, U4, "VELOCITY.PLANE.INTUITION_BALL", "타구 위치·(dx/dt, dy/dt)(생각 열기)", "평면 운동의 속도", "하", ACT, "(1) (200,230) (2) (100,80)", "좌표(소문항별)", 2, fig="그림", combo="미분+실생활")
r(182, U4, "VELOCITY.PLANE.BASIC", "평면 위 점 속도·가속도(예제)", "평면 운동의 속도와 가속도", "하", S, "속도 (2, 2t+1), 가속도 (0, 2)", "벡터")
r(183, U4, "VELOCITY.PLANE.TRIG_EXP", "평면 위 점 속도·가속도", "평면 운동의 속도와 가속도", "중하", S, "(1) 속도 (−(4π/3)sin(πt/3), (4π/3)cos(πt/3)), 가속도 (−(4π²/9)cos(πt/3), −(4π²/9)sin(πt/3)) (2) 속도 (eᵗ(cos t−sin t), eᵗ(sin t+cos t)), 가속도 (−2eᵗsin t, 2eᵗcos t)", "벡터(소문항별)", 2, c=M, chk="독립풀이(가속도 포함) 산출; 파일 답 속도부분 일치")
r(184, U4, "VELOCITY.PLANE.CIRCULAR_SATELLITE", "등속 원운동 인공위성 속도·가속도(탐구)", "평면 운동의 속도와 가속도", "중하", "서술형(탐구)", "(1) x=Rcosωt, y=Rsinωt (2) 속도 (−Rωsinωt, Rωcosωt), 가속도 (−Rω²cosωt, −Rω²sinωt) (3) 속력 Rω, 가속도 크기 Rω²", "식·값", 3, fig="그림", c=M, i=M)
r(185, U1, "TANGENT.AT_POINT.BASIC", "접선의 방정식(중단원 마무리)", "접선의 방정식", "하", S, "(1) y=(1/2)x+1/2 (2) y=(2/e)x", "식(소문항별)", 2)
r(186, U2, "INFLECTION.CONCAVITY.BASIC", "오목·볼록과 변곡점(중단원 마무리)", "곡선의 오목과 볼록;변곡점", "하", S, "(1) (−∞,1) 위로 볼록, (1,∞) 아래로 볼록, 변곡점 (1,−1) (2) (−∞,2) 위로 볼록, (2,∞) 아래로 볼록, 변곡점 (2,2/e²)", "구간·좌표", 2)
r(187, U3, "EQUATION.ROOT_COUNT.EXP_LINEAR", "eˣ=3x 실근 개수", "방정식의 실근의 개수", "하", S, "2", d=M)
r(188, U3, "INEQUALITY.PROOF.TRIG", "sin x≥x cos x (0≤x≤π) 증명", "부등식의 증명;증가함수", "중하", PRF, "f(x)=sin x−x cos x, f′=x sin x≥0, f(0)=0", "증명", i=M, final="풀이 참조")
r(189, U4, "VELOCITY.LINE.TRIG", "수직선 위 점 속도·가속도(중단원 마무리)", "직선 운동의 속도와 가속도", "하", S, "속도 1−(2π/3)sin(πt/3), 가속도 −(2π²/9)cos(πt/3)", "식")
r(190, U1, "NORMAL.LINE.AT_POINT", "접선에 수직인 직선", "접선의 방정식;수직 조건", "하", S, "y=−x+2", "식")
r(191, U1, "TANGENT.COMMON.TWO_CURVES", "eˣ의 접선이 2√x−k에 접할 k", "접선의 방정식;공통접선", "중", D, "k=1/e", c=M, d=M, i=M, combo="접선+접선")
r(192, U2, "EXTREMA.TRIG_PARAM.THEN_LOG_MIN", "극값 조건으로 a, b → g 극솟값", "함수의 극대와 극소;삼각함수의 미분", "중", S, "1+√3", c=M, d=M, i=M)
r(193, U2, "EXTREMA_INFLECTION.PARAM_LOG", "극대·변곡점 조건으로 극솟값", "함수의 극대와 극소;변곡점", "중", S, "9/8+ln4", c=M, d=M, i=M)
r(194, U2, "INFLECTION.LOG_SQUARE.ON_LINE", "(ln ax)² 변곡점이 직선 위", "변곡점;로그함수의 미분", "중", S, "7e", c=M, d=M)
r(195, U2, "MONOTONIC.ALWAYS_INCREASING.PARAM", "실수 전체 증가 조건 a 범위", "함수의 증가와 감소;판별식", "중", S, "0≤a≤1", "범위", d=M, i=M, trap="a=0 포함, a<0 제외")
r(196, U3, "EQUATION.NO_ROOT.EXP_LOG_BOTH", "eˣ=kx, ln x=kx 모두 실근 없는 k", "방정식의 실근의 개수;접선", "중", S, "1/e<k<e", "범위", d=M, i=M, combo="접선+실근")
r(197, U3, "INEQUALITY.PARAM_K.CLOSED_INTERVAL_MAX", "[e,e²]에서 부등식 성립 k 범위", "부등식의 활용;최댓값", "중", S, "k≤2e−2", "범위", c=M, d=M, trap="최댓값은 끝값 비교")
r(198, U4, "RELATED_RATES.DISTANCE_CAR_OBSERVER", "관찰자와 자동차 거리 변화율", "속도;변화율", "중", S, "90√109/109 m/s", fig="그림", c=M, d=M, combo="미분+실생활")
r(199, U1, "TANGENT.FROM_EXTERNAL_POINT.SLOPE_PRODUCT", "점에서 그은 두 접선 기울기 곱", "접선의 방정식;근과 계수의 관계", "중", S, "e", c=M, d=M, i=M, combo="접선+이차방정식")
r(200, U2, "MAXMIN.TANGENT_TRIANGLE_AREA", "eˣ 접선과 축이 만드는 넓이 최대", "함수의 최대와 최소;접선의 방정식", "중", D, "2/e", fig="그림", c=M, d=M, i=M, combo="접선+최대최소")
r(201, U3, "EQUATION.ROOT_COUNT.CONDITIONS_TABLE", "조건(표)으로 f=g 실근 최대·최소 개수", "방정식의 실근의 개수;그래프 개형", "중상", S, "2", fig="표·그래프", c=M, d=H, i=H, review="REVIEW-그림판독", chk="조건표(tbl) 미추출 — 파일 정답 기준, 독립풀이 불가")
r(202, U4, "VELOCITY.PLANE.PROJECTILE", "포물선 운동 최고점 시각·착지 속력", "평면 운동의 속도;속력", "중", "서술형(탐구)", "(1) t=(v₀/g)sinα (2) v₀", "식(소문항별)", 2, c=M, i=M, combo="미분+물리")
r(203, E1, "LIMEXP.RATIONAL_FORM.DIVIDE", "지수 분수꼴 극한(대단원 평가)", "지수함수의 극한", "하", MC, "④", "선택지번호", final="④ (1/2)")
r(204, E1, "LIMLOG.CONTINUITY_PARAMS", "연속 조건으로 a, b (로그 극한)", "함수의 연속;로그함수의 극한 공식", "중하", S, "a=2, b=1", "값(2개)", d=M, i=M, combo="연속+극한")
r(205, E2, "DERIV.CHAIN.EXP_INNER_LIMIT", "f(2ˣ) 미분계수 극한", "미분계수의 정의;합성함수의 미분법", "중하", MC, "④", "선택지번호", d=M, final="④ (2ln2)")
r(206, T1, "TRIG.ADDITION.VIETA_TAN_ROOTS", "tan 두 근으로 tan(α+β)", "삼각함수의 덧셈정리;근과 계수의 관계", "하", MC, "③", "선택지번호", final="③ (3)")
r(207, T2, "LIMTRIG.TAN_MINUS_SIN.CUBIC", "(tan x−sin x)/x³ 극한", "삼각함수의 극한", "중하", S, "1", c=M, d=M)
r(208, T3, "DERIV.CHAIN.LIMIT_COMPOSITE_SIN", "f(sin x) 극한=f′(0)", "미분계수의 정의;삼각함수의 극한", "중하", S, "1", d=M, i=M)
r(209, Q2, "DERIV.CHAIN.RADICAL_DIFFERENCE_QUOTIENT", "√(x²+x+1) 미분계수", "합성함수의 미분법;미분계수의 정의", "하", MC, "③", "선택지번호", final="③ (√3/2)")
r(210, Q2, "DERIV.CHAIN.LIMIT_F_OF_G", "f(g(x)) 극한=f′(2)g′(1)", "합성함수의 미분법;미분계수의 정의", "하", MC, "⑤", "선택지번호", final="⑤ (5)")
r(211, Q3, "PARAM.DERIV.BASIC", "매개변수 함수 dy/dx", "매개변수로 나타낸 함수의 미분법", "하", MC, "②", "선택지번호", final="② (−9t²/4)")
r(212, Q4, "IMPLICIT.DERIV.CONIC", "타원 음함수 미분", "음함수의 미분법", "하", MC, "③", "선택지번호", final="③ (−3x/(4y))")
r(213, Q4, "INVERSE.DERIV.FORMULA", "역함수 미분계수 공식", "역함수의 미분법", "하", MC, "④", "선택지번호", final="④ (1/c)")
r(214, Q5, "SECOND_DERIV.EXP_TRIG", "eˣsin(x−π) 이계도함수", "이계도함수", "하", S, "y″=2eˣcos(x−π)", "식")
r(215, Q5, "SECOND_DERIV.PARAM_FROM_VALUE", "f″(0)=8 되는 a", "이계도함수", "하", MC, "④", "선택지번호", final="④ (4)")
r(216, U1, "TANGENT.SLOPE.CHAIN_TRIG", "tan(cos x) 접선 기울기", "접선의 기울기;합성함수의 미분법", "하", MC, "④", "선택지번호", final="④ (−1)")
r(217, U2, "EXTREMA.RATIONAL.PARAM", "극댓값 조건으로 a, b (유리함수)", "함수의 극대와 극소;몫의 미분법", "중", S, "a=12, b=−12", "값(2개)", c=M, d=M)
r(218, U2, "GRAPH.PROPERTIES.XEX_BOGI", "−xeˣ 그래프 보기 판정", "함수의 그래프;극값;변곡점;점근선", "중하", MC, "⑤", "선택지번호", fig="보기(미추출)", review="REVIEW-그림판독", final="⑤ (ㄱ,ㄴ,ㄷ)", chk="보기 본문 미추출 — 파일 정답 기준(극대 x=−1, 변곡점 x=−2 등 독립 확인)")
r(219, U3, "INEQUALITY.PARAM_K.MIN_VALUE_TRIG", "cos x≥k−x² 성립 k 범위", "부등식의 활용;최솟값", "중하", S, "k≤1", "범위", d=M)
r(220, U4, "VELOCITY.LINE.TRIG_PARAMS", "속도·가속도 조건으로 a+b", "직선 운동의 속도와 가속도", "중하", MC, "③", "선택지번호", c=M, d=M, final="③ (0)")
r(221, Q1, "DERIV.PRODUCT.LIMIT_CONDITION", "극한 조건으로 f(1)+f′(1)", "미분계수의 정의;곱의 미분법", "중", D, "2/e", c=M, d=M, i=M)
r(222, Q2, "DERIV.CHAIN.LINEAR_INNER_IDENTITY", "f(3x−2) 항등식으로 f′(7)", "합성함수의 미분법", "하", S, "4")
r(223, U1, "TANGENT.FROM_EXTERNAL_POINT.COUNT_CONDITION", "두 접선 그을 조건, 불가능한 정수 a 개수", "접선의 방정식;판별식", "중", S, "5개", c=M, d=M, i=M, combo="접선+판별식", trap="경계 a=1, −3 포함")
r(224, U2, "MAXMIN.APPLIED.CHANNEL_TRAPEZOID", "수로 단면 사다리꼴 넓이 최대", "함수의 최대와 최소;삼각함수의 미분", "중", S, "3√3/4 m²", fig="그림", c=M, d=M, combo="최대최소+실생활")
assert len(ROWS) == 224 and [x['_q'] for x in ROWS] == list(range(1, 225))
for i in range(23): build(f"Batch{347+i}", ROWS[i*10:(i+1)*10], 11942+i*10)
