from cfgex import *
MC, S_, D = "객관식(5지선다)", "단답형", "서술형"
M, H = "보통", "높음"
def a(q, big, mid, small, tid, tname, tags, diff, ans, summ, chk, pts, fmt=MC, **kw):
    kw.setdefault("atype", "선택지" if fmt == MC else "값")
    R(q, 1, big, mid, small, tid, tname, tags, diff, fmt, ans, summ, chk, pts=pts, **kw)
    r = ROWS[-1]; r.update({"출처대분류": "EBS 연계 수능대비 모의고사(학원 편집본)", "학교명": "", "주관기관": "JYJ수학교실 편집(EBS 버티컬 모의고사 시즌2)",
        "학교/시험명": "2026학년도 수능대비 EBS 버티컬 모의고사 시즌2 (확률과 통계 선택)", "원본페이지": "HWP 단일문서", "메모": r["메모"].replace("P1 학교기출", "P1 수능대비 모의고사")})
EL, TR, SQ, LC, DF, IG, PB, ST = "지수함수와 로그함수", "삼각함수", "수열", "함수의 극한과 연속", "미분", "적분", "경우의 수·확률", "통계"
K = dict(enumerate("④④⑤⑤②①④③②③①①②③③", 1))
K.update({16: "2", 17: "19", 18: "7", 19: "113", 20: "11", 21: "23", 22: "320", 23: "③", 24: "③", 25: "④", 26: "④", 27: "⑤", 28: "①", 29: "236", 30: "9"})
setup("A00839", "1zp5I6r3jWadAfIs7hMqkS799sO5AZXZ5", "2026학년도 수능대비 EBS 버티컬 모의고사[확률과 통계][시즌2].hwp", "p2/A00839.hwp", "JYJ수학교실", "2026학년도", "수능대비 모의고사", "고3", "수학Ⅰ·수학Ⅱ·확률과 통계",
      KEY=K, KEYPAGE="동일 HWP 문항별 인라인 정답+해설, 말미 정답표", KEYSRC="", VIS="HWP5 BodyText+EQEDIT 전문 판독(그림 개체 3문항 미렌더)", TEXT="HWP5 olefile BodyText 전문(수식 EQEDIT 포함)")
F = dict(fig="그래프")
a(1, EL, "지수", "지수법칙", "EXP.IRRATIONAL_EXPONENT", "4^{2+√2}×1/2^{3+2√2}", "지수법칙", "하", "④ (2)", "", "2^{1}", "2")
a(2, LC, "함수의 극한", "0/0 꼴", "LIMIT.SQRT.RATIONALIZE", "(x−2)/(√(3x−2)−2) x→2", "함수의 극한", "하", "④ (4/3)", "", "유리화", "2")
a(3, TR, "삼각함수", "삼각함수의 성질", "TRIG.REDUCTION.SIN_GIVEN", "sin(π−θ)=3/5, tanθ<0, sin(3π/2+θ)", "삼각함수의 성질", "하", "⑤ (4/5)", "", "−cosθ=4/5", "3")
a(4, DF, "도함수", "다항함수 미분", "DERIV.QUADRATIC.MIN_VALUE", "f'(1)=4, f(−1)=2 이차함수 최솟값", "도함수", "하", "⑤ (2)", "", "x²+2x+3", "3")
a(5, IG, "정적분", "절댓값 정적분", "INTEG.ABS.PRODUCT", "∫₋₁²(x+1)|x−1|dx", "정적분", "하", "② (8/3)", "", "4/3+4/3", "3")
a(6, SQ, "등비수열", "등비수열의 일반항", "GEOM.DIFF_CONDITIONS.TERM", "a₃−a₁=4, a₇−a₅=36 a₉", "등비수열", "하", "① (162)", "", "r²=3, a₁=2", "3")
a(7, DF, "도함수의 활용", "접선", "TANGENT.PARALLEL_SLOPE.DISTANCE", "x³−3x²−8x+5 기울기 1 두 접선 사이 거리", "접선의 방정식;점과 직선 거리", "중하", "④ (16√2)", "", "접점 −1, 3", "3", c=M)
a(8, IG, "정적분", "적분 방정식", "INTEG.EQUATION.DIFFERENTIATE", "∫₁ˣf=(x+1)f+x³−3x, f(2)", "정적분으로 정의된 함수", "중하", "③ (−1/2)", "", "f'=−3x+3, f(1)=1", "3", c=M)
a(9, SQ, "수열의 합", "합과 일반항", "SUM_TO_TERM.SHIFT_DIFF_SUM", "Sₙ=n²+2n−1, ∑(a_{k+3}−aₖ)", "합과 일반항의 관계", "중하", "② (61)", "", "a₁=2, aₙ=2n+1 (n≥2)", "4", c=M, trap=M)
a(10, IG, "정적분의 활용", "속도와 위치", "MOTION.NO_DIRECTION_CHANGE.MAX_POSITION", "v=t³/3−at²+3a 방향 불변, t=2 위치 최대", "속도와 위치;최솟값", "중", "③ (19/3)", "", "0<a≤3/2", "4", c=M, i=M)
a(11, EL, "로그", "로그의 성질", "LOG.VIETA.SOLVE_BASES", "x²−(log_a(a³/4))x−2=0 두 근 log₂a, log_ab, ab", "로그의 성질;근과 계수", "중", "① (2)", "", "b=1/4, a=8", "4", c=M)
a(12, IG, "정적분의 활용", "넓이", "AREA.PARABOLA_LINES.EQUAL", "2x²+2와 y=ax+4, y=4 넓이 A=B, a", "정적분의 활용", "중", "① (−6)", "", "A+C=4/3=B+C=−8/a", "4", c=M, **F)
a(13, TR, "삼각함수의 활용", "사인·코사인법칙", "CIRCUMCENTER_INCENTER.COINCIDE.QUAD", "AB=3, BC=√5, cosB=−√5/5, 외심 O=△ACD 내심, DE", "사인법칙;코사인법칙;내심", "상", "② (5√2/3)", "", "AC=2√5, R=5/2, AD=5√5/3", "4", c=H, i=H, fig="도형")
a(14, DF, "도함수의 활용", "그래프와 실근", "QUARTIC.ABS_NONDIFF.COMPOSITE_ROOT_COUNT", "|f−f(1)| x=α만 미분불가, 극소 0, f(f(x))=t 개수 불연속 β", "극대·극소;방정식의 실근", "상", "③ (−5/16)", "", "f=(x−1)³(x+1)+27/16, β=11/16", "4", c=H, i=H)
a(15, SQ, "수열의 귀납적 정의", "역추적", "RECUR.MOD3_RULE.BACKTRACK_SUM", "a₈=2, ≤30, 3의 배수 조건 점화 a₁ 합", "귀납적 정의", "중", "③ (72)", "", "a₁∈{6,14,22,30} (전수 확인)", "4", c=M, i=M)
a(16, EL, "로그함수", "로그부등식", "LOGINEQ.DOMAIN.INTEGER_COUNT", "log₃(x²−1)<1+log₃(x+1) 정수 개수", "로그부등식", "하", "2", "", "1<x<4", "3", fmt=S_)
a(17, DF, "도함수", "곱의 미분", "DERIV.PRODUCT.VALUE", "(2x³+3)(x²−3x+6) h'(1)", "도함수", "하", "19", "", "6·4+5·(−1)", "3", fmt=S_)
a(18, SQ, "등차수열", "등차수열의 합", "ARITH.SUM_SYMMETRY.PAIR_COUNT", "S_{n+2}−Sₙ=112−16n, Sₚ=S_q 쌍 개수", "등차수열의 합", "중하", "7", "", "Sₙ=−4n(n−16), p+q=16", "3", fmt=S_, c=M)
a(19, TR, "삼각함수의 활용", "삼각방정식", "TRIGEQ.FACTOR.SYMMETRY_ROOTS", "sin² 꼴 인수분해 방정식 두 근 α²+β²", "삼각방정식", "중하", "113", "0<x<10", "x=7, 8", "3", fmt=S_, c=M)
a(20, LC, "함수의 연속", "구간별 함수 연속", "CONTINUITY.RECIPROCAL_QUADRATIC.PARAM", "g=1/2, 1/f, 1/6 연속, f(0)=k 자연수 최대", "함수의 연속", "중", "11", "", "0<a<2+√3, k=3a", "4", fmt=S_, c=M, i=M)
a(21, EL, "로그함수", "최대·최소", "EXPLOG.PIECEWISE.WINDOW_MAXMIN", "log₃(9x−9)/(√3)^{6−x} 구간 최대 3 t 개수 a, 최소 1 s 곱 b, a+3b", "지수·로그함수의 그래프", "중", "23", "", "a=3, b=4/3·5", "4", fmt=S_, c=M, i=M)
a(22, DF, "도함수의 활용", "그래프와 실근", "CUBIC_PRODUCT.PIECEWISE_SIGN.ROOT_COUNT", "g=±f·f' (x<1/x≥1), h(t) 조건, g(−1)=20, g(0)g(3)", "극대·극소;연속", "상", "320", "", "f 대칭축 x=1, f=x²−2x−8", "4", fmt=S_, c=H, i=H)
a(23, PB, "순열", "같은 것이 있는 순열", "PERM.REPEATED.BASIC", "a,a,b,b,b,c 나열", "같은 것이 있는 순열", "하", "③ (60)", "", "6!/(2!3!)", "2")
a(24, PB, "확률", "독립사건", "PROB.INDEPENDENT.UNION", "P(Aᶜ)=5/6, P(B|A)=2/3 독립 P(A∪B)", "사건의 독립", "하", "③ (13/18)", "", "1/6+2/3−1/9", "3")
a(25, PB, "확률", "여사건", "PROB.COMPLEMENT.SEATS_ENDS", "6명 일렬, 양 끝 중 적어도 한 자리 A,B,C", "여사건의 확률", "하", "④ (4/5)", "", "1−144/720", "3")
a(26, ST, "통계적 추정", "모평균의 추정", "CI.MEAN.LENGTH", "n=36, s=12, 95% 신뢰구간 길이", "모평균의 추정", "하", "④ (7.84)", "", "2·1.96·2", "3")
a(27, ST, "확률분포", "이항분포", "BINOM.TAIL_RATIO.SECOND_MOMENT", "P(X=n−1)=100P(X=n), E(X)=5, E(X²)", "이항분포", "중하", "⑤ (29)", "", "p=1/5, n=25", "3", c=M)
a(28, PB, "중복조합", "중복조합의 활용", "COMB.FACTOR_DISTRIBUTION.PARITY", "abcd=192, a+b+c+d 홀수 순서쌍", "중복조합", "중", "① (176)", "", "홀수 1개 160 + 3개 16 (전수 확인)", "4", c=M, i=M)
a(29, PB, "확률", "조건부확률", "PROB.CONDITIONAL.FUNCTION_COUNT", "X→X 함수 조건 (가)(나) 하 f(1)=4 확률 p+q", "조건부확률;중복조합", "상", "236", "", "364/580=91/145 (전수 확인)", "4", fmt=S_, c=H, i=H)
a(30, ST, "확률분포", "연속확률변수", "CONT.PIECEWISE_PDF.CDF_DIFF_MAX", "두 확률밀도함수 그래프, |P(X≤k)−P(Y≤k)| 최대 5/14, a", "연속확률변수", "상", "9", "0<a<2", "최댓값 1/(a+2) → a=4/5 (그래프 미렌더, 해설 기반 조건 복원)", "4", fmt=S_, c=H, i=H, fig="그래프")
n = len(ROWS); print(n)
for i in range((n + 9) // 10): build(f"Batch{718+i}", ROWS[i*10:(i+1)*10], 15449+i*10)
