from cfgy2 import *
import cfgy2, builder, bisect
SQ = hashlib.sha256(open(OUT+'h60/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y60.json'))
setup(QID="A02460", SRC="1fTNk7lRJJnGpmrid0v7u-ZYQV1kI0rut", SHA=SQ, TAG="YMSS04", N=118, SUBJ="수학(하)", SEC="S04A",
      FNAME="04 집합과 명제(신사고) 118제.hwp", UNIT="Ⅳ. 집합과 명제", BIG="Ⅳ. 집합과 명제", EXAM="4. 집합과 명제 118제", MID="집합과 명제")
cfgy2.P.update(BOOK="신사고 수학(하)", GRADE="고1", MEMO_X="파서가 '(출처: …)', '(단, 등호는 …)' 줄을 정답 줄로 오인한 거짓 항목 2개를 다음 문항 본문에 병합 → 118문항=빠른 정답 118개 정렬 일치(파일명 118제); ")
B = [1, 10, 17, 37, 51, 68, 74, 80, 87, 101]
MIDS = ["집합", "집합 사이의 포함 관계", "집합의 연산", "집합(중단원 마무리)", "명제와 조건", "명제 사이의 관계", "여러 가지 증명법", "절대부등식", "명제(중단원 마무리)", "집합과 명제 종합(대단원 마무리)"]
SECS = [f"S04{chr(65+j)}" for j in range(len(B))]
for s, mid in zip(SECS, MIDS): builder.SECTIONS[s] = ("4. 집합과 명제 118제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, MC = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "5지선다"
J1, J2, J3, P1, P2, P3, P4 = "집합", "집합 사이의 포함 관계", "집합의 연산", "명제와 조건", "명제 사이의 관계", "여러 가지 증명법", "절대부등식"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = SECS[bisect.bisect_right(B, q) - 1]
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·벤다이어그램 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건·보기(수식/그림 객체) 본문 미추출 — 해설로 조건 복원, 파일 정답 기준")
OK_ = dict(review="REVIEW-개방형")
r(1, J1, "SET.ELEMENTS.DIVISORS_MULTIPLES", "약수·배수 나열(준비)", "약수와 배수", "하", S, "(1) 1,2,3,5,6,10,15,30 (2) 12,24,…,96", "나열(소문항별)", 2)
r(2, J1, "SET.ELEMENTS.COMMON_DIV_MULT", "공약수·공배수(준비)", "약수와 배수", "하", S, "(1) 1,2,3,6 (2) 6,12,18,…", "나열(소문항별)", 2)
r(3, J1, "SET.DEFINITION.WELL_DEFINED", "집합인 것 찾고 원소 구하기", "집합의 뜻", "하", S, "(1) {1,3,5,7,9} (4) {0,1}", "집합")
r(4, J1, "SET.MEMBERSHIP.SYMBOL", "∈, ∉ 써넣기", "원소와 집합의 관계", "하", S, "(1) ∈ (2) ∉ (3) ∈ (4) ∉", "기호(소문항별)", 4)
r(5, J1, "SET.NOTATION.ROSTER_BUILDER", "원소나열법↔조건제시법", "집합의 표현", "하", S, "(1) A={x|x는 12의 약수} (2) B={6,12,18,24,30}", "집합(소문항별)", 2)
r(6, J1, "SET.NOTATION.VENN", "벤다이어그램으로 나타내기", "집합의 표현", "하", "서술형(그림)", "(1) A={2,3,5,7,11} (2) B={−1,4} 벤다이어그램", "그림", 2, fig="그림", final="그림 답")
r(7, J1, "SET.CARDINALITY.BASIC", "n(A) 구하기", "유한집합의 원소의 개수", "하", S, "(1) 4 (2) 10 (3) 0", "값(소문항별)", 3, trap="공집합 n=0")
r(8, J1, "SET.DEFINITION.MAKE_WELL_DEFINED", "집합 되도록 기준 바꾸기(활동)", "집합의 뜻", "하", ACT, "예시: 키 170cm 이하인, 인구 100만 명 이상인, 가장 높은", "서술(개방형)", 3, **OK_)
r(9, J1, "SET.CARDINALITY.CONSTRUCT", "n(A)=2, n(B)=10 집합 만들기(활동)", "유한집합의 원소의 개수", "하", ACT, "예: A={x|x는 6과 10의 공약수}, B={x|x는 20 이하의 홀수}", "서술(개방형)", **OK_)
r(10, J2, "SET.SUBSET.SYMBOL", "⊂, ⊄ 써넣기", "부분집합", "하", S, "(1) ⊄ (2) ⊂", "기호(소문항별)", 2)
r(11, J2, "SET.SUBSET.LIST_ALL", "부분집합 모두 구하기(예제)", "부분집합", "하", S, "∅, {a}, {b}, {c}, {a,b}, {a,c}, {b,c}, {a,b,c}", "나열")
r(12, J2, "SET.SUBSET.LIST_ALL", "부분집합 모두 구하기", "부분집합", "하", S, "∅ 포함 16개({1},{3},…,{1,3,5,7})", "나열")
r(13, J2, "SET.EQUALITY.CHECK", "두 집합이 같은지 확인", "서로 같은 집합", "하", S, "(1) A=B (2) A≠B", "판정(소문항별)", 2)
r(14, J2, "SET.PROPER_SUBSET.LIST", "진부분집합 모두 구하기", "진부분집합", "하", S, "∅, {−1}, {0}, {1}, {−1,0}, {−1,1}, {0,1}", "나열")
r(15, J2, "SET.SUBSET.COUNT_FORMULA", "부분집합 개수 2ⁿ(탐구)", "부분집합의 개수", "하", ACT, "2ⁿ", "식", fig="그림")
r(16, J2, "SET.SUBSET.COUNT_CONSTRAINED", "특정 원소 포함/제외 부분집합 개수(탐구)", "부분집합의 개수", "하", ACT, "(1) 16 (2) 8", "값(소문항별)", 2)
r(17, J3, "SET.UNION_INTERSECTION.BASIC", "합집합·교집합·서로소", "합집합과 교집합", "하", S, "(1) {1,2,3,4,6}, {1,2} (2) {0,1,…,6}, {3} (3) 합집합 12개 원소, A∩B=∅ → 서로소", "집합(소문항별)", 3)
r(18, J3, "SET.UNION_INTERSECTION.FIND_SET", "합·교집합 조건으로 B", "합집합과 교집합", "하", S, "B={2,4,6,7}", "집합")
r(19, J3, "SET.LAWS.ASSOCIATIVE_UNION_VENN", "결합법칙(합집합) 벤다이어그램 설명", "집합의 연산 법칙", "하", PRF, "벤다이어그램으로 양변 동일", "증명", fig="그림", final="해설참조")
r(20, J3, "SET.LAWS.ASSOCIATIVE_INTERSECTION_VENN", "결합법칙(교집합) 벤다이어그램 설명", "집합의 연산 법칙", "하", PRF, "벤다이어그램으로 양변 동일", "증명", fig="그림", final="해설참조")
r(21, J3, "SET.LAWS.DISTRIBUTIVE_VENN", "분배법칙(∩ over ∪) 설명", "집합의 연산 법칙", "하", PRF, "벤다이어그램으로 양변 동일", "증명", fig="그림", final="해설참조")
r(22, J3, "SET.LAWS.DISTRIBUTIVE_VENN", "분배법칙(∪ over ∩) 설명", "집합의 연산 법칙", "하", PRF, "벤다이어그램으로 양변 동일", "증명", fig="그림", final="해설참조")
r(23, J3, "SET.COMPLEMENT.BASIC", "여집합", "여집합", "하", S, "(1) {2,4,6,8,10} (2) {3,5,6,7,9,10}", "집합(소문항별)", 2)
r(24, J3, "SET.DIFFERENCE.BASIC", "차집합", "차집합", "하", S, "(1) {8} (2) {2,4,5}", "집합(소문항별)", 2)
r(25, J3, "SET.DIFFERENCE.AS_INTERSECTION_VENN", "A−B=A∩Bᶜ 설명", "차집합;여집합", "하", PRF, "벤다이어그램", "증명", fig="그림", final="해설참조")
r(26, J3, "SET.COMPLEMENT.PROPERTIES_VENN", "여집합 성질 설명", "여집합", "하", PRF, "벤다이어그램", "증명", 3, fig="그림", final="해설참조")
r(27, J3, "SET.DIFFERENCE.PROPERTIES_VENN", "차집합 성질 설명", "차집합", "하", PRF, "벤다이어그램", "증명", 2, fig="그림", final="해설참조")
r(28, J3, "SET.DE_MORGAN.UNION_VENN", "드모르간 법칙(합집합) 설명", "드모르간의 법칙", "하", PRF, "벤다이어그램", "증명", fig="그림", final="해설참조")
r(29, J3, "SET.DE_MORGAN.INTERSECTION_VENN", "드모르간 법칙(교집합)·(A−B)ᶜ 설명", "드모르간의 법칙", "하", PRF, "벤다이어그램", "증명", 2, fig="그림", final="해설참조")
r(30, J3, "SET.LAWS.TWO_METHODS", "벤다이어그램·연산법칙 두 방법 설명(탐구)", "집합의 연산 법칙;드모르간의 법칙", "중하", PRF, "두 방법 모두 성립 확인", "증명", 2, fig="그림", final="해설참조", i=M)
r(31, J3, "SET.CARDINALITY.INCLUSION_EXCLUSION", "n(A∩B) 구하기", "유한집합의 원소의 개수", "하", S, "8")
r(32, J3, "SET.CARDINALITY.COMPLEMENT_DE_MORGAN", "n(Aᶜ∩Bᶜ)로 n(B)", "유한집합의 원소의 개수;드모르간의 법칙", "중하", S, "31", c=M)
r(33, J3, "SET.CARDINALITY.CONTEXT_UNION", "동아리 가입 학생 수(예제)", "유한집합의 원소의 개수", "하", S, "26")
r(34, J3, "SET.CARDINALITY.CONTEXT_NEITHER", "어느 곳도 희망하지 않는 학생 수", "유한집합의 원소의 개수", "하", S, "2")
r(35, J1, "SET.INFINITE.HILBERT_HOTEL_FINITE", "힐베르트 호텔 5쌍 투숙(활동)", "무한집합", "하", ACT, "n호실 손님을 (n+5)호실로", "서술", i=M)
r(36, J1, "SET.INFINITE.HILBERT_HOTEL_INFINITE", "힐베르트 호텔 무한 투숙(활동)", "무한집합", "중하", ACT, "n호실 손님을 2n호실로(홀수 호실 비움)", "서술", i=M)
r(37, J1, "SET.DEFINITION.WELL_DEFINED", "집합인 것 찾기", "집합의 뜻", "하", S, "(2), (4)", "보기")
r(38, J1, "SET.MEMBERSHIP_SUBSET.STATEMENTS", "∈·⊂ 보기 판정", "원소와 집합의 관계;부분집합", "하", S, "ㄴ, ㄹ", "보기", trap="∅∈A는 거짓")
r(39, J3, "SET.OPERATIONS.ALL_FOUR", "합·교·여·차집합", "집합의 연산", "하", S, "(1) {1,2,3,4,5,6,8,10} (2) {2,4} (3) {6,7,8,9,10} (4) {1,3,5}", "집합(소문항별)", 4)
r(40, J3, "SET.CARDINALITY.INCLUSION_EXCLUSION", "n(A∩B)", "유한집합의 원소의 개수", "하", S, "8")
r(41, J2, "SET.SUBSET.CHAIN_FROM_OPERATIONS", "합·곱 원소 집합 포함관계", "부분집합", "중하", MC, "②", "선택지번호", final="② (A⊂C⊂B)", c=M)
r(42, J3, "SET.ASSOCIATIVE.APPLY", "결합법칙으로 A∩(B∩C)", "집합의 연산 법칙", "하", S, "{2, 4, 6}", "집합")
r(43, J2, "SET.SANDWICH.COUNT", "A⊂X⊂B인 X 개수(서술형)", "부분집합의 개수", "중하", D, "4")
r(44, J3, "SET.VENN.RECONSTRUCT", "조건으로 집합 A 복원", "집합의 연산", "중하", S, "A={1, 9, 27}", "집합", d=M)
r(45, J3, "SET.LAWS.ALGEBRAIC_PROOF", "연산 법칙으로 설명", "집합의 연산 법칙;드모르간의 법칙", "중하", PRF, "(1) A∩(Aᶜ∩Bᶜ)=∅ (2) (A∩Bᶜ)∩(A∩Cᶜ)=A∩(B∪C)ᶜ=A−(B∪C)", "증명", 2, final="해설참조", i=M)
r(46, J3, "SET.VENN.SHADED_EXPRESSION", "색칠 부분과 같은 집합", "집합의 연산", "중하", MC, "③", "선택지번호", fig="그림", final="③", **FK)
r(47, J3, "SET.CARDINALITY.SYMMETRIC_DIFFERENCE", "대칭차 원소 개수", "유한집합의 원소의 개수", "중하", S, "42")
r(48, J3, "SET.INTERSECTION.FIND_PARAM", "A∩B 조건으로 a 구해 A∪B(서술형)", "합집합과 교집합", "중", D, "A∪B={0, 1, 3, 5}", "집합", d=M, trap="a=−1 배제")
r(49, J3, "SET.UNION_EQUALITY.COUNT_C", "A∪C=B∪C인 C 개수", "집합의 연산;부분집합의 개수", "중", S, "8", i=M)
r(50, J3, "SET.CARDINALITY.MAX_MIN_INTERSECTION", "x의 최댓값·최솟값", "유한집합의 원소의 개수", "중하", S, "최댓값 16, 최솟값 6", "값", final="최댓값 16, 최솟값 6", chk="독립풀이 일치(파일 빠른 정답 표기는 최솟값 6, 해설에 최댓값 16)")
r(51, P1, "SET.SUBSET.SYMBOL", "⊂, ⊄ 판정(준비)", "부분집합", "하", S, "(1) A⊂B (2) A⊄B", "기호(소문항별)", 2)
r(52, P1, "INEQUALITY.PROPERTIES.PREP", "부등식 성질(준비)", "부등식의 성질", "하", S, "(1) < (2) < (3) > (4) <", "기호(소문항별)", 4, trap="음수 곱하면 반전")
r(53, P1, "PROPOSITION.IDENTIFY_TRUTH", "명제 찾고 참·거짓", "명제", "하", S, "(1) 참 (2) 거짓 (4) 참", "판정")
r(54, P1, "PROPOSITION.PROOF.ODD_SUM", "두 홀수의 합은 짝수 증명(예제)", "명제의 증명", "하", PRF, "a=2m−1, b=2n−1 → a+b=2(m+n−1)", "증명", final="해설참조")
r(55, P1, "PROPOSITION.PROOF.ODD_PRODUCT", "두 홀수의 곱은 홀수 증명", "명제의 증명", "하", PRF, "ab=2(2mn−m−n)+1", "증명", final="해설참조")
r(56, P1, "CONDITION.TRUTH_SET", "조건의 진리집합", "조건과 진리집합", "하", S, "(1) {2,4,6,8,10} (2) {1,2,3,5,6,10,15,30}", "집합(소문항별)", 2)
r(57, P1, "CONDITION.NEGATION", "조건의 부정", "부정", "하", S, "(1) x는 2의 배수가 아니다 (2) x<−3", "서술(소문항별)", 2)
r(58, P1, "PROPOSITION.NEGATION_TRUTH", "명제의 부정과 참·거짓", "부정", "하", S, "(1) 5는 소수가 아니다(거짓) (2) 2+3=5(참)", "서술(소문항별)", 2)
r(59, P1, "CONDITION.NEGATION_TRUTH_SET", "조건의 부정과 진리집합", "부정;진리집합", "하", S, "(1) x는 6의 약수가 아니다, {4,5,7} (2) x²−6x+8≠0, {1,3,5,6,7}", "서술+집합(소문항별)", 2)
r(60, P1, "CONDITION.NEGATION_AND", "'그리고' 조건의 부정(탐구)", "부정;드모르간의 법칙", "하", ACT, "x는 12의 약수가 아니거나 10의 약수가 아니다; {3,4,5,…,12}", "서술+집합")
r(61, P1, "CONDITION.NEGATION_OR", "'또는' 조건의 부정(탐구)", "부정;드모르간의 법칙", "하", ACT, "x는 12의 약수도 아니고 10의 약수도 아니다; {7,8,9,11}", "서술+집합")
r(62, P1, "PROPOSITION.HYPOTHESIS_CONCLUSION", "가정과 결론", "명제 p→q", "하", S, "(1) 가정 a,b 짝수, 결론 a+b 짝수 (2) 가정 x=3, 결론 2x+3=9", "서술(소문항별)", 2)
r(63, P1, "PROPOSITION.TRUTH_BY_SETS", "진리집합으로 참·거짓(예제)", "명제 p→q의 참, 거짓", "하", S, "(1) 거짓 (2) 참", "판정(소문항별)", 2)
r(64, P1, "PROPOSITION.TRUTH_BY_COUNTEREXAMPLE", "명제 참·거짓 판별", "명제 p→q의 참, 거짓", "하", S, "(1) 거짓 (2) 참 (3) 거짓 (4) 참", "판정(소문항별)", 4, trap="반례 2, π")
r(65, P1, "PROPOSITION.TRUTH_SET.PARAM_RANGE", "p→~q 참인 a 범위", "명제 p→q의 참, 거짓;진리집합", "중하", S, "a≥1", "부등식", d=M)
r(66, P1, "PROPOSITION.QUANTIFIERS.TRUTH", "'모든'·'어떤' 명제 참·거짓", "모든과 어떤", "하", S, "(1) 참 (2) 거짓", "판정(소문항별)", 2)
r(67, P1, "PROPOSITION.QUANTIFIERS.NEGATION", "'모든'·'어떤' 명제 부정", "모든과 어떤;부정", "중하", S, "(1) 어떤 x에 대해 |x−2|≤0 (참) (2) 모든 x에 대해 x²≠x+3 (거짓)", "서술(소문항별)", 2)
r(68, P2, "PROPOSITION.CONVERSE_CONTRAPOSITIVE", "역과 대우", "명제의 역과 대우", "하", S, "(1) 역: x²=y²이면 x=y, 대우: x²≠y²이면 x≠y (2)~(4) 해설 표기대로", "서술(소문항별)", 4)
r(69, P2, "PROPOSITION.CONTRAPOSITIVE.TRUTH", "대우로 참·거짓", "명제의 역과 대우", "하", S, "(1) 대우: a,b 모두 0 이상이면 a+b≥0 (참) (2) 참", "서술+판정", 2)
r(70, P2, "PROPOSITION.SYLLOGISM.TRUTH_SETS", "삼단논법 진리집합 설명(활동)", "삼단논법", "하", ACT, "P⊂Q⊂R → P⊂R", "서술", final="해설참조")
r(71, P2, "PROPOSITION.SYLLOGISM.CONTRAPOSITIVE", "대우+삼단논법으로 q→r", "삼단논법;대우", "중하", ACT, "~p→~q 대우 q→p, p→r → q→r", "서술", final="해설참조", i=M)
r(72, P2, "CONDITION.SUFFICIENT_NECESSARY.EXAMPLE", "충분·필요조건 판정(예제)", "충분조건과 필요조건", "하", S, "(1) 충분조건 (2) 필요조건 (3) 필요충분조건", "판정(소문항별)", 3)
r(73, P2, "CONDITION.SUFFICIENT_NECESSARY", "충분·필요조건 판정", "충분조건과 필요조건", "하", S, "(1) 필요충분조건 (2) 필요조건 (3) 충분조건", "판정(소문항별)", 3)
r(74, P3, "PROOF.CONTRAPOSITIVE.SQUARE_EVEN", "대우 증명(예제)", "대우를 이용한 증명", "하", PRF, "n 홀수 → n² 홀수", "증명", final="해설참조")
r(75, P3, "PROOF.CONTRAPOSITIVE.BASIC", "대우로 증명", "대우를 이용한 증명", "하", PRF, "(1) n 짝수 → n² 짝수 (2) x=0 또는 y=0 → xy=0", "증명", 2, final="해설참조")
r(76, P3, "PROOF.CONTRADICTION.SQRT2", "√2 무리수 귀류법(예제)", "귀류법", "중하", PRF, "서로소 m,n 가정 → 모순", "증명", final="해설참조", i=M)
r(77, P3, "PROOF.CONTRADICTION.ONE_PLUS_SQRT2", "1+√2 무리수 귀류법", "귀류법", "하", PRF, "√2=a−1 유리수 → 모순", "증명", final="해설참조")
r(78, P3, "LOGIC.PUZZLE.ONE_TRUE", "한 명만 참일 때 골 넣은 사람(활동)", "명제;추론", "중", ACT, "B", "서술", i=M, **CK)
r(79, P3, "LOGIC.PUZZLE.ONE_FALSE", "한 명만 거짓일 때 골 넣은 사람(활동)", "명제;추론", "중", ACT, "C", "서술", i=M, **CK)
r(80, P4, "ABS_INEQ.COMPLETING_SQUARE", "a²−ab+b²≥0 증명(예제)", "절대부등식", "하", PRF, "(a−b/2)²+3b²/4≥0", "증명", final="해설참조")
r(81, P4, "ABS_INEQ.COMPLETING_SQUARE", "완전제곱 절대부등식 증명", "절대부등식", "하", PRF, "(1) (a+b/2)²+3b²/4≥0 (2) (a+b)²+b²≥0", "증명", 2, final="해설참조")
r(82, P4, "ABS_INEQ.AM_GM.PROOF", "산술·기하평균 부등식 증명(예제)", "산술평균과 기하평균의 관계", "하", PRF, "(√a−√b)²/2≥0", "증명", final="해설참조")
r(83, P4, "ABS_INEQ.AM_GM.APPLY", "a+1/a≥2, a/b+b/a≥2 증명", "산술평균과 기하평균의 관계", "하", PRF, "산술·기하평균 적용", "증명", 2, final="해설참조")
r(84, P4, "ABS_INEQ.TRIANGLE.ABS_SUM", "|a|+|b|≥|a+b| 증명(예제)", "절대부등식;절댓값", "중하", PRF, "양변 제곱 차 2(|ab|−ab)≥0", "증명", final="해설참조", i=M)
r(85, P4, "ABS_INEQ.TRIANGLE.ABS_DIFF", "|a|+|b|≥|a−b| 등 증명", "절대부등식;절댓값", "중", PRF, "제곱 차 2(|ab|±ab)≥0 및 경우 분류", "증명", 2, final="해설참조", i=M)
r(86, P4, "ABS_INEQ.AM_GM.GEOMETRIC", "그림으로 산술·기하평균 설명(탐구)", "산술평균과 기하평균의 관계", "중하", ACT, "넓이 비교 (a+b)²≥4ab, 반원 DE=√ab≤반지름", "서술", 2, fig="그림", final="해설참조", i=M)
r(87, P1, "PROPOSITION.IDENTIFY", "명제 찾기", "명제", "하", S, "(1), (2), (4)", "보기")
r(88, P1, "PROPOSITION.TRUTH_SET.PARAM_RANGE", "p→q 참인 a 범위", "명제 p→q의 참, 거짓;진리집합", "중하", S, "−1<a≤4", "부등식", **CK)
r(89, P2, "PROPOSITION.CONVERSE_CONTRAPOSITIVE", "역과 대우", "명제의 역과 대우", "하", S, "(1) 역: ac=bc이면 a=b, 대우: ac≠bc이면 a≠b (2) 역: a+b>0이면 a>0이고 b>0, 대우: a+b≤0이면 a≤0 또는 b≤0", "서술(소문항별)", 2)
r(90, P2, "CONDITION.SUFFICIENT_NECESSARY", "충분·필요·필요충분 써넣기", "충분조건과 필요조건", "하", S, "(1) 충분 (2) 필요 (3) 필요충분", "판정(소문항별)", 3)
r(91, P4, "ABS_INEQ.ROOT_SUM.PROOF", "√a+√b>√(a+b) 증명", "절대부등식", "하", PRF, "제곱 차 2√(ab)>0", "증명", final="해설참조")
r(92, P1, "PROPOSITION.NEGATION_TRUTH", "명제 부정과 참·거짓", "부정;모든과 어떤", "하", S, "(1) 정사각형은 마름모가 아니다(거짓) (2) 어떤 x: x²≤0(참) (3) 모든 소수는 홀수(거짓)", "서술(소문항별)", 3)
r(93, P2, "PROPOSITION.CONVERSE.PARAM_RANGE", "역이 참인 a 범위", "명제의 역과 대우;진리집합", "중", S, "−2≤a≤6", "부등식", d=M)
r(94, P2, "PROPOSITION.SYLLOGISM.STATEMENTS", "반드시 참인 명제 보기", "삼단논법;대우", "중하", S, "ㄱ, ㄴ", "보기", **CK)
r(95, P2, "CONDITION.SET_EQUATION.NSC", "집합 등식의 필요충분조건", "충분조건과 필요조건;집합의 연산", "중", MC, "①", "선택지번호", final="① (A⊂B)", i=M)
r(96, P2, "CONDITION.INTERVALS.MIN_LENGTH", "필요·충분조건으로 b−a 최솟값(서술형)", "충분조건과 필요조건;진리집합", "중", D, "8", d=M, i=M, **CK)
r(97, P4, "ABS_INEQ.CAUCHY_SCHWARZ", "코시-슈바르츠 부등식 증명", "절대부등식", "중하", PRF, "차 (ay−bx)²≥0", "증명", final="해설참조")
r(98, P1, "PROPOSITION.TWO_CONDITIONS.PARAM", "두 명제 모두 참인 a 범위(서술형)", "명제;모든과 어떤", "중", D, "−2≤a<1", "부등식", d=M, **CK)
r(99, P2, "CONDITION.NECESSARY.FIND_PARAM", "필요조건으로 a", "충분조건과 필요조건;대우", "중하", S, "−6", i=M, trap="대우로 x=2 대입")
r(100, P4, "ABS_INEQ.AM_GM.ERROR_ANALYSIS", "산술·기하평균 오류 찾기", "산술평균과 기하평균의 관계", "중", D, "등호 조건(2x=3y, 2/x=3/y) 동시 성립 불가 → 전개 후 13+6(x/y+y/x)≥25, 최솟값 25", "서술+값", final="해설참조(최솟값 25)", i=M)
r(101, J1, "SET.MEMBERSHIP_SUBSET.NESTED", "집합을 원소로 갖는 집합 판정", "원소와 집합의 관계;부분집합", "중하", MC, "⑤", "선택지번호", final="⑤", d=M, trap="{1,2}는 원소이면서 부분집합")
r(102, J3, "SET.SUBSET.CONSEQUENCES", "A⊂B일 때 옳지 않은 것", "부분집합;집합의 연산", "하", MC, "⑤", "선택지번호", final="⑤")
r(103, J2, "SET.SANDWICH.COUNT", "조건 만족 X 개수", "부분집합의 개수", "하", S, "16")
r(104, J3, "SET.VENN.CHOOSE_DIAGRAM", "식에 맞는 벤다이어그램 고르기", "집합의 연산", "중하", MC, "①", "선택지번호", fig="그림", final="①", **FK)
r(105, J3, "SET.CARDINALITY.MULTIPLES", "배수 집합 n(A∪B)", "유한집합의 원소의 개수", "하", S, "27")
r(106, J3, "SET.CARDINALITY.ONLY_ONE", "A만 좋아하는 학생 수", "유한집합의 원소의 개수", "하", S, "10")
r(107, P1, "PROPOSITION.TRUTH_SET.DISJOINT", "p→~q 참일 때 진리집합 관계", "명제 p→q의 참, 거짓;진리집합", "하", MC, "②", "선택지번호", final="② (P∩Q=∅)")
r(108, P1, "PROPOSITION.EXISTENTIAL.PARAM_COUNT", "'어떤' 명제 참인 정수 k 개수", "모든과 어떤", "중", S, "6개", i=M)
r(109, P2, "PROPOSITION.TRUTH_SETS.STATEMENTS", "진리집합 보기 판정", "명제의 역과 대우;진리집합", "중", MC, "③", "선택지번호", final="③ (ㄱ, ㄷ)", **CK)
r(110, P2, "CONDITION.CHAIN.NOT_NECESSARILY_TRUE", "반드시 참이라 할 수 없는 명제", "충분조건과 필요조건;삼단논법", "중하", MC, "⑤", "선택지번호", final="⑤")
r(111, P2, "CONDITION.SUFFICIENT_NOT_NECESSARY.CHOICE", "충분조건이지만 필요조건 아닌 것", "충분조건과 필요조건", "중하", MC, "⑤", "선택지번호", final="⑤", d=M)
r(112, P3, "PROOF.CONTRAPOSITIVE.PYTHAGOREAN_PARITY", "피타고라스 수 짝수 포함 대우 증명", "대우를 이용한 증명", "중", PRF, "a,b,c 모두 홀수 → a²+b² 짝수, c² 홀수 → 불일치", "증명", final="해설참조", i=M)
r(113, J3, "SET.CONDITIONS.COUNT_X", "A∩X=∅, B∩X={2}인 X 개수(서술형)", "부분집합의 개수;집합의 연산", "하", D, "8")
r(114, J3, "SET.CARDINALITY.THREE_SETS", "세 문제 맞힌 학생 수(서술형)", "유한집합의 원소의 개수", "중", D, "8", d=M, fig="그림")
r(115, P2, "CONDITION.SUFFICIENT.MIN_INTEGER", "충분조건 되는 정수 k 최솟값(서술형)", "충분조건과 필요조건;진리집합", "하", D, "5")
r(116, P4, "ABS_INEQ.AM_GM.MIN_SHIFTED", "x+16/(x+2) 최솟값 a, b(서술형)", "산술평균과 기하평균의 관계", "중하", D, "ab=12", c=M, trap="x+2로 맞추고 −2")
r(117, P3, "LOGIC.PUZZLE.ANGEL_DEVIL_HUMAN", "천사·악마·인간 판별(활동)", "명제;추론", "중", ACT, "X: 인간, Y: 악마, Z: 천사", "서술", i=M)
r(118, P3, "LOGIC.PUZZLE.BIRTHDAY", "생일 맞히기 논리 퍼즐(활동)", "명제;추론", "중상", ACT, "8월 14일", "서술", i=H, **CK)
for i in range(12): build(f"Batch{506+i}", ROWS[i*10:(i+1)*10], 13460+i*10)
print(len(ROWS))
