from cfgy2 import *
import cfgy2, builder, bisect
SQ = hashlib.sha256(open(OUT+'h64/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y64.json'))
setup(QID="A02464", SRC="1wCZQW9BIOq5xhnfKWJJVcawXkGa-phFa", SHA=SQ, TAG="YMSS03", N=157, SUBJ="수학(상)", SEC="S03A",
      FNAME="03 도형의 방정식(신사고) 157제.hwp", UNIT="Ⅲ. 도형의 방정식", BIG="Ⅲ. 도형의 방정식", EXAM="3. 도형의 방정식 157제", MID="도형의 방정식")
cfgy2.P.update(BOOK="신사고 수학(상)", GRADE="고1", MEMO_X="빠른 정답 목록은 20번 정답 둘째 줄((2) x=(m₁x₁+m₂x₂)/(m₁+m₂))을 별도 항목으로 분리해 158개 — 이를 20번에 병합하면 157문항과 정렬 일치; ")
B = [1, 11, 21, 35, 43, 53, 59, 74, 85, 95, 109, 116, 123, 138]
MIDS = ["두 점 사이의 거리", "선분의 내분점과 외분점", "평면좌표(중단원 마무리)", "직선의 방정식", "두 직선의 평행과 수직", "점과 직선 사이의 거리", "직선의 방정식(중단원 마무리)",
        "원의 방정식", "원과 직선의 위치 관계", "원의 방정식(중단원 마무리)", "평행이동", "대칭이동", "도형의 이동(중단원 마무리)", "도형의 방정식 종합(대단원 마무리)"]
SECS = [f"S03{chr(65+j)}" for j in range(len(B))]
for s, mid in zip(SECS, MIDS): builder.SECTIONS[s] = ("3. 도형의 방정식 157제", mid)
L, M, H = "낮음", "보통", "높음"
S, D, ACT, PRF, DRW = "서술형(단답)", "서술형", "서술형(활동)", "서술형(증명)", "서술형(그래프 그리기)"
P1, P2, L1, L2, L3, C1, C2, T1, T2 = "두 점 사이의 거리", "선분의 내분점과 외분점", "직선의 방정식", "두 직선의 평행과 수직", "점과 직선 사이의 거리", "원의 방정식", "원과 직선의 위치 관계", "평행이동", "대칭이동"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치", **kw):
    cfgy2.P['SEC'] = SECS[bisect.bisect_right(B, q) - 1]
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final, **kw)
FK = dict(review="REVIEW-그림판독", chk="그림·좌표 객체 미추출 — 파일 정답 기준(그림 조건 독립검증 불가)")
CK = dict(review="REVIEW-조건미추출", chk="조건·보기(수식/표 객체) 본문 미추출 — 파일 정답 기준")
r(1, P1, "COORD.READ_POINTS", "좌표평면 위 점의 좌표 읽기(준비)", "좌표", "하", S, "A(1,2), B(−3,4), C(−4,−2), D(3,−1)", "좌표", fig="그림", **FK)
r(2, P1, "PYTHAGORAS.RIGHT_TRIANGLE", "직각삼각형 변의 길이(준비)", "피타고라스 정리", "하", S, "(1) 10 (2) 4√2", "값(소문항별)", 2, fig="그림", **FK)
r(3, P1, "DISTANCE.NUMBER_LINE", "수직선 위 두 점 사이 거리", "두 점 사이의 거리", "하", S, "(1) 3 (2) 5", "값(소문항별)", 2)
r(4, P1, "DISTANCE.PLANE.BASIC", "좌표평면 두 점 사이 거리", "두 점 사이의 거리", "하", S, "(1) 8 (2) 5 (3) 3√5 (4) 2√17", "값(소문항별)", 4)
r(5, P1, "DISTANCE.TRIANGLE_SHAPE.RIGHT_ISOSCELES", "직각이등변삼각형임을 설명(예제)", "두 점 사이의 거리;삼각형의 모양", "하", D, "AB=CA=√34, BC=√68, AB²+CA²=BC² → 직각이등변삼각형", "서술")
r(6, P1, "DISTANCE.TRIANGLE_SHAPE.RIGHT", "직각삼각형임을 설명", "두 점 사이의 거리;삼각형의 모양", "하", D, "AB²=8, BC²=18, CA²=26=8+18 → ∠B=90°", "서술")
r(7, P1, "DISTANCE.EQUIDISTANT.ON_AXIS", "x축 위 등거리 점(예제)", "두 점 사이의 거리", "하", S, "(2, 0)", "좌표")
r(8, P1, "DISTANCE.EQUIDISTANT.ON_AXIS", "y축 위 등거리 점", "두 점 사이의 거리", "하", S, "(0, 7)", "좌표")
r(9, P1, "DISTANCE.PROOF.PAPPUS_MEDIAN", "중선정리 좌표 증명(예제)", "두 점 사이의 거리;좌표를 이용한 증명", "중하", PRF, "M을 원점, BC를 x축으로 잡아 전개 → 성립", "증명", final="풀이참조", i=M)
r(10, P1, "DISTANCE.PROOF.RECTANGLE_BRITISH_FLAG", "직사각형 PA²+PC²=PB²+PD² 증명", "두 점 사이의 거리;좌표를 이용한 증명", "중하", PRF, "B를 원점으로 좌표 설정 후 전개 → 성립", "증명", final="풀이참조", i=M)
r(11, P2, "SECTION.INTERNAL.NUMBER_LINE", "수직선 내분점·중점", "선분의 내분점", "하", S, "(1) −3 (2) −2", "값(소문항별)", 2)
r(12, P2, "SECTION.INTERNAL.PLANE", "좌표평면 내분점·중점", "선분의 내분점", "하", S, "(1) (−3, 2) (2) (−2, 1)", "좌표(소문항별)", 2)
r(13, P2, "SECTION.CENTROID.DERIVE", "무게중심 좌표 유도(예제)", "삼각형의 무게중심", "하", D, "((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3)", "좌표")
r(14, P2, "SECTION.CENTROID.BASIC", "무게중심 좌표", "삼각형의 무게중심", "하", S, "(−1, 0)", "좌표")
r(15, P2, "SECTION.PARALLELOGRAM.FOURTH_VERTEX", "평행사변형 넷째 꼭짓점(활동)", "선분의 중점;평행사변형", "하", ACT, "(6, 0)", "좌표", trap="꼭짓점 순서 ABCD")
r(16, P2, "SECTION.EXTERNAL.NUMBER_LINE", "수직선 외분점", "선분의 외분점", "하", S, "(1) −35 (2) 7", "값(소문항별)", 2)
r(17, P2, "SECTION.EXTERNAL.PLANE", "좌표평면 외분점", "선분의 외분점", "하", S, "(1) (−7, −3) (2) (14, 25)", "좌표(소문항별)", 2)
r(18, P2, "SECTION.EXTERNAL.CONTEXT", "북극성 위치(외분점)", "선분의 외분점", "하", S, "(0, −1)", "좌표", fig="그림", **FK)
r(19, P2, "SECTION.MIXED.TREASURE_MAP", "보물 지도 내분·외분(활동)", "선분의 내분점;선분의 외분점", "중하", ACT, "(1) D(3, 13/3), E(5, 5) (2) DE의 중점(지도 표시)", "좌표", 2, fig="그림", **FK)
r(20, P2, "SECTION.INTERNAL.LEVER", "지레의 원리와 내분점(활동)", "선분의 내분점", "중하", ACT, "(1) 받침점은 AB를 2:3으로 내분하는 점 (2) x=(m₁x₁+m₂x₂)/(m₁+m₂)", "서술+식", 2, **CK)
r(21, P1, "DISTANCE.NUMBER_LINE", "수직선 두 점 거리", "두 점 사이의 거리", "하", S, "(1) 11 (2) 4", "값(소문항별)", 2)
r(22, P1, "DISTANCE.PLANE.BASIC", "좌표평면 두 점 거리", "두 점 사이의 거리", "하", S, "(1) √13 (2) 2√2", "값(소문항별)", 2)
r(23, P2, "SECTION.MIXED.NUMBER_LINE", "수직선 내분·외분·중점", "선분의 내분점;선분의 외분점", "하", S, "(1) 2 (2) 26 (3) 1", "값(소문항별)", 3)
r(24, P2, "SECTION.MIXED.PLANE", "좌표평면 내분·외분·중점", "선분의 내분점;선분의 외분점", "하", S, "(1) (4, 0) (2) (8, −8) (3) (7/2, 1)", "좌표(소문항별)", 3)
r(25, P1, "DISTANCE.RIGHT_ANGLE.FIND_PARAM", "∠A=90°인 a", "두 점 사이의 거리", "하", S, "a=−1")
r(26, P1, "DISTANCE.EQUIDISTANT.ON_LINE", "y축·y=x 위 등거리 점", "두 점 사이의 거리", "하", S, "(1) (0, 4) (2) (2, 2)", "좌표(소문항별)", 2)
r(27, P2, "SECTION.INTERNAL.ON_LINE_PARAM", "내분점이 직선 위일 때 a", "선분의 내분점", "하", S, "a=9")
r(28, P2, "SECTION.CENTROID.FIND_VERTEX", "무게중심으로 꼭짓점 C", "삼각형의 무게중심", "하", S, "(−4, 3)", "좌표")
r(29, P2, "SECTION.INTERNAL.QUADRANT_RANGE", "내분점이 제1사분면일 t 범위(서술형)", "선분의 내분점", "중하", D, "3/4<t<1", "부등식", d=M)
r(30, P2, "SECTION.EXTERNAL.FIND_PARAMS", "외분점으로 a, b", "선분의 외분점", "하", S, "a=0, b=2")
r(31, P2, "SECTION.RATIO_ON_LINE.BOTH_CASES", "AB=3BC인 C 모두", "선분의 내분점;선분의 외분점", "중", S, "(2, 6), (8, 10)", "좌표", d=M, trap="C가 B 양쪽 두 경우")
r(32, P1, "DISTANCE.CIRCUMCENTER", "외심 좌표·외접원 반지름(서술형)", "두 점 사이의 거리;외심", "중하", D, "외심 (1, 4), 반지름 √10", "좌표+값", final="(1, 4), √10", chk="독립풀이: 외심 (1,4), R=√10 — 파일 빠른 정답은 반지름 √10만 표기")
r(33, P1, "DISTANCE.MOVING_POINTS.MIN", "두 사람 사이 거리 최소 시각", "두 점 사이의 거리;이차함수 최솟값", "중", S, "14분 후", c=M, d=M, fig="그림")
r(34, P2, "SECTION.ANGLE_BISECTOR", "각의 이등분선과 대변 교점", "선분의 내분점;각의 이등분선 성질", "중하", S, "(2, −1)", "좌표", fig="그림", trap="AB=AC=√65")
r(35, L1, "LINE.SLOPE.TWO_POINTS", "두 점 지나는 직선 기울기(준비)", "직선의 기울기", "하", S, "2")
r(36, L1, "LINE.EQUATION.SLOPE_INTERCEPT", "기울기·y절편 직선(준비)", "직선의 방정식", "하", S, "y=−2x+3", "식")
r(37, L1, "LINE.GENERAL_FORM.READ", "일반형 직선 기울기·절편", "직선의 방정식", "하", S, "기울기 −1/2, x절편 3, y절편 3/2", "값")
r(38, L1, "LINE.EQUATION.POINT_SLOPE", "점·기울기 직선", "직선의 방정식", "하", S, "(1) y=2x+5 (2) y=4", "식(소문항별)", 2)
r(39, L1, "LINE.EQUATION.TWO_POINTS", "두 점 지나는 직선", "직선의 방정식", "하", S, "(1) y=−2x+3 (2) x=3", "식(소문항별)", 2, trap="x좌표 같으면 x=k")
r(40, L1, "LINE.INTERCEPT_FORM.PROOF", "절편형 x/a+y/b=1 설명", "직선의 방정식", "하", PRF, "두 점 (a,0),(0,b) 지나는 직선 정리 → x/a+y/b=1", "증명", final="해설참조")
r(41, L1, "LINE.GRAPH.DRAW", "일차방정식 직선 그리기", "직선의 방정식", "하", DRW, "해설참조(절편 이용)", "그래프", 4, fig="그래프", final="해설참조")
r(42, L1, "LINE.PENCIL.FIXED_POINT", "k에 관계없이 지나는 점 설명(활동)", "직선의 방정식;정점", "중하", ACT, "두 직선 교점 (−1/3, 5/3)을 항상 지남", "서술", final="해설참조", i=M)
r(43, L2, "LINE.PARALLEL.THROUGH_POINT", "평행한 직선(예제)", "두 직선의 평행", "하", S, "y=4x+6", "식")
r(44, L2, "LINE.PARALLEL.THROUGH_POINT", "평행한 직선", "두 직선의 평행", "하", S, "(1) y=3x−19 (2) y=−2x−2", "식(소문항별)", 2)
r(45, L2, "LINE.PERPENDICULAR.THROUGH_POINT", "수직인 직선(예제)", "두 직선의 수직", "하", S, "y=2x+10", "식")
r(46, L2, "LINE.PERPENDICULAR.THROUGH_POINT", "수직인 직선", "두 직선의 수직", "하", S, "(1) y=3x−13 (2) y=−x/2−3", "식(소문항별)", 2)
r(47, L2, "LINE.PERP_BISECTOR", "선분의 수직이등분선", "두 직선의 수직;선분의 중점", "하", S, "y=−x+7", "식")
r(48, L2, "LINE.PERPENDICULAR.CONTEXT_PROOF", "잔디밭 두 길 수직 설명", "두 직선의 수직", "하", D, "기울기 −4/3, 3/4의 곱 −1 → 수직", "서술", final="해설참조", fig="그림", **FK)
r(49, L2, "LINE.GENERAL_FORM.PARALLEL_PERP_CONDITIONS", "일반형 평행·수직 조건 설명(탐구)", "두 직선의 평행과 수직", "중하", PRF, "(1) a/a'=b/b'≠c/c' (2) aa'+bb'=0 유도", "증명", 2, final="해설참조", i=M)
r(50, L2, "LINE.TRIANGLE.CIRCUMCENTER_CONCURRENCY", "수직이등분선 한 점에서 만남(활동)", "두 직선의 수직;외심", "중", ACT, "(1) y=(b/a)x+(a²−b²)/(2a), x=(b+c)/2 (2) ((b+c)/2, (a²+bc)/(2a)) (3) 해설참조", "식+좌표", 3, fig="그림", i=M)
r(51, L2, "LINE.TRIANGLE.ORTHOCENTER_CONCURRENCY", "세 수선 한 점에서 만남(활동)", "두 직선의 수직;수심", "중", PRF, "세 수선이 (0, −bc/a)에서 만남", "증명", final="해설참조", fig="그림", i=M)
r(52, L2, "LINE.TRIANGLE.EULER_LINE", "외심·수심·무게중심 한 직선(활동)", "두 직선의 평행과 수직;무게중심", "중상", PRF, "세 점이 한 직선(오일러 직선) 위", "증명", final="해설참조", fig="그림", i=H)
r(53, L3, "DIST_POINT_LINE.BASIC", "점과 직선 사이 거리", "점과 직선 사이의 거리", "하", S, "(1) 3 (2) 2√5", "값(소문항별)", 2)
r(54, L3, "DIST_POINT_LINE.PARALLEL_LINES", "평행한 두 직선 사이 거리", "점과 직선 사이의 거리", "하", S, "√5/2", trap="계수 맞추기")
r(55, L3, "DIST_POINT_LINE.FIND_PARALLEL", "평행·거리 2인 직선 모두", "점과 직선 사이의 거리", "하", S, "4x+3y−16=0, 4x+3y+4=0", "식")
r(56, L3, "DIST_POINT_LINE.FIND_SLOPE", "원점 지나고 거리 √5인 직선", "점과 직선 사이의 거리", "중하", S, "y=−x/2, y=2x", "식", c=M)
r(57, L3, "DIST_POINT_LINE.CONTEXT_ROAD", "신도시와 도로 최단 거리", "점과 직선 사이의 거리", "하", S, "10 km", fig="그림")
r(58, L3, "DIST_POINT_LINE.TRIANGLE_AREA_FORMULA", "삼각형 넓이 공식 유도(활동)", "점과 직선 사이의 거리", "중", ACT, "(1) y=(y₂−y₁)/(x₂−x₁)(x−x₁)+y₁ (2) |x₁y₂−x₂y₁|/√((x₂−x₁)²+(y₂−y₁)²) (3) S=½|x₁y₂−x₂y₁|", "식+증명", 3, fig="그림", i=M)
r(59, L1, "LINE.EQUATION.POINT_SLOPE", "점·기울기 직선", "직선의 방정식", "하", S, "y=−3x−3", "식")
r(60, L1, "LINE.EQUATION.TWO_POINTS", "두 점 지나는 직선", "직선의 방정식", "하", S, "(1) y=x/4+5/2 (2) x=−5", "식(소문항별)", 2)
r(61, L2, "LINE.PARALLEL_PERP.IDENTIFY", "평행·수직 직선 찾기", "두 직선의 평행과 수직", "하", S, "평행 (1), 수직 (3)", "보기")
r(62, L2, "LINE.PARALLEL.FIND_COEFF", "평행 조건 a", "두 직선의 평행", "하", S, "−3/5")
r(63, L3, "DIST_POINT_LINE.BASIC", "점과 직선 거리", "점과 직선 사이의 거리", "하", S, "2")
r(64, L1, "LINE.THROUGH_INTERSECTION", "교점과 점 지나는 직선", "직선의 방정식", "하", S, "y=−3x+10", "식")
r(65, L1, "LINE.COLLINEAR.FIND_PARAM", "세 점 한 직선 위 a와 직선", "직선의 방정식", "중하", S, "a=3, y=2x+1", "값+식", final="y=2x+1 (a=3)", chk="독립풀이: a=3, y=2x+1 — 파일 빠른 정답은 직선만 표기")
r(66, L2, "LINE.SQUARE.SIDE_EQUATIONS", "정사각형 변 직선 방정식", "두 직선의 수직;직선의 방정식", "중하", S, "(1) y=x/2−1/2 (2) y=−2x+7", "식(소문항별)", 2, fig="그림", d=M)
r(67, L1, "LINE.PENCIL.FIXED_POINT", "k에 관계없이 지나는 점", "직선의 방정식;정점", "하", S, "(2, 0)", "좌표")
r(68, L2, "LINE.FOOT_OF_PERPENDICULAR", "수선의 발(서술형)", "두 직선의 수직", "중하", D, "(1, 3)", "좌표")
r(69, L3, "DIST_POINT_LINE.FIND_POINT_ON_AXIS", "거리 2√2인 x축 위 점(서술형)", "점과 직선 사이의 거리", "하", D, "(−10, 0), (−2, 0)", "좌표")
r(70, L3, "DIST_POINT_LINE.TRIANGLE_AREA", "삼각형 넓이 단계별", "점과 직선 사이의 거리;두 점 사이의 거리", "중하", S, "(1) √10 (2) x−3y+4=0 (3) 11√10/10 (4) 11/2", "값(소문항별)", 4)
r(71, L1, "LINE.BISECT_TWO_RECTANGLES", "두 직사각형 넓이 동시 이등분", "직선의 방정식", "중하", S, "y=5x/6−1/3", "식", fig="그림", **FK)
r(72, L2, "LINE.THREE_LINES.NO_TRIANGLE", "세 직선이 삼각형을 이루지 않는 m", "두 직선의 평행;직선의 방정식", "중", S, "m=2/3, −2, 1/3", "값", d=M, i=M, trap="평행 2가지 + 한 점 공유")
r(73, L3, "DIST_POINT_LINE.ANGLE_BISECTOR_LOCUS", "두 직선에서 같은 거리인 점의 자취", "점과 직선 사이의 거리", "중", S, "x+3y−4=0, 3x−y+4=0", "식", i=M)
r(74, P1, "DISTANCE.PLANE.BASIC", "두 점 사이 거리(준비)", "두 점 사이의 거리", "하", S, "(1) 2√10 (2) 5", "값(소문항별)", 2)
r(75, P2, "SECTION.MIDPOINT", "중점 좌표(준비)", "선분의 중점", "하", S, "(−2, 2)", "좌표")
r(76, L3, "DIST_POINT_LINE.BASIC", "점과 직선 거리(준비)", "점과 직선 사이의 거리", "하", S, "(1) 4√2 (2) 2√5", "값(소문항별)", 2)
r(77, C1, "CIRCLE.EQUATION.CENTER_RADIUS", "원의 방정식(표준형)", "원의 방정식", "하", S, "(1) (x+1)²+(y+6)²=16 (2) x²+y²=49 (3) (x−3)²+(y−4)²=25", "식(소문항별)", 3)
r(78, C1, "CIRCLE.EQUATION.DIAMETER_ENDPOINTS", "지름 양 끝 원(예제)", "원의 방정식", "하", S, "(x−2)²+(y−1)²=8", "식")
r(79, C1, "CIRCLE.EQUATION.DIAMETER_ENDPOINTS", "지름 양 끝 원", "원의 방정식", "하", S, "(x−2)²+(y−4)²=13", "식")
r(80, C1, "CIRCLE.EQUATION.THREE_POINTS", "세 점 지나는 원(예제)", "원의 방정식", "중하", S, "(x+1)²+(y−1)²=5", "식", c=M)
r(81, C1, "CIRCLE.EQUATION.THREE_POINTS", "세 점 지나는 원", "원의 방정식", "중하", S, "(1) (x−3)²+(y−2)²=13 (2) x²+(y+1)²=10", "식(소문항별)", 2, c=M)
r(82, C1, "CIRCLE.GENERAL_FORM.CENTER_RADIUS", "일반형 원의 중심·반지름", "원의 방정식", "하", S, "(1) (−2,−3), 4 (2) (1/2, −5/2), 3√2/2", "값(소문항별)", 2)
r(83, C1, "CIRCLE.GENERAL_FORM.CONDITION", "원을 나타낼 k 범위", "원의 방정식", "하", S, "k<17", "부등식")
r(84, C1, "CIRCLE.APOLLONIUS", "아폴로니오스의 원(활동)", "원의 방정식;두 점 사이의 거리", "중", ACT, "(x−8)²+(y−1)²=72", "식", c=M, i=M)
r(85, C2, "CIRCLE_LINE.POSITION.DISTANCE", "원과 직선 위치 관계(예제)", "원과 직선의 위치 관계", "하", S, "한 점에서 만난다(접한다)", "서술")
r(86, C2, "CIRCLE_LINE.POSITION.DISTANCE", "원과 직선 위치 관계", "원과 직선의 위치 관계", "하", S, "(1) 서로 다른 두 점 (2) 만나지 않는다", "서술(소문항별)", 2)
r(87, C2, "CIRCLE_LINE.TWO_POINTS.RANGE", "두 점에서 만날 k 범위(예제)", "원과 직선의 위치 관계", "하", S, "−2√2<k<2√2", "부등식")
r(88, C2, "CIRCLE_LINE.POSITION.PARAM_CASES", "위치 관계별 k", "원과 직선의 위치 관계", "하", S, "(1) −5<k<5 (2) k=±5 (3) k<−5 또는 k>5", "부등식(소문항별)", 3, final="(1) −5<k<5 (2) k=±5 (3) k<−5 또는 k>5", chk="독립풀이 일치 (파일 빠른 정답 (3)의 '−5' 부호 글리프 소실)")
r(89, C2, "TANGENT.GIVEN_SLOPE", "기울기 주어진 접선", "원의 접선의 방정식", "하", S, "(1) y=2x±3√5 (2) y=−3x±√10", "식(소문항별)", 2)
r(90, C2, "TANGENT.POINT_ON_CIRCLE", "원 위의 점에서의 접선", "원의 접선의 방정식", "하", S, "(1) x+y=−4 (2) y=−4", "식(소문항별)", 2)
r(91, C2, "TANGENT.EXTERNAL_POINT", "원 밖의 점에서 접선(예제)", "원의 접선의 방정식", "중하", S, "x+y=2, x−y=2", "식")
r(92, C2, "TANGENT.EXTERNAL_POINT", "원 밖의 점에서 접선", "원의 접선의 방정식", "중하", S, "x+2y=5, 2x−y=5", "식", c=M)
r(93, C2, "TANGENT.CONTEXT_SUPPORT", "구조물 지지대 직선", "원의 접선의 방정식", "중하", S, "y=4x/3+40/3", "식", fig="그림", c=M)
r(94, C2, "TANGENT.VERTICAL_MISSING.DISCUSS", "접선 하나만 구해지는 이유 토론", "원의 접선의 방정식", "중하", D, "x=1은 y−1=m(x−1) 꼴로 표현 불가(기울기 없음) → 누락", "서술", final="풀이참조", i=M)
r(95, C1, "CIRCLE.EQUATION.MIXED", "여러 조건의 원의 방정식", "원의 방정식", "하", S, "(1) (x−3)²+(y−3)²=5 (2) (x−2)²+(y+1)²=4 (3) (x−4)²+(y−3)²=25", "식(소문항별)", 3)
r(96, C2, "CIRCLE_LINE.POSITION.PARAM_CASES", "위치 관계별 m", "원과 직선의 위치 관계", "중하", S, "(1) m<−√3 또는 m>√3 (2) m=±√3 (3) −√3<m<√3", "부등식(소문항별)", 3, final="(1) m<−√3 또는 m>√3 (2) m=±√3 (3) −√3<m<√3", chk="독립풀이 일치 (파일 빠른 정답 (1)의 '−√3' 부호 글리프 소실)")
r(97, C2, "TANGENT.POINT_ON_CIRCLE", "원 위 점 접선", "원의 접선의 방정식", "하", S, "2x+y=10", "식")
r(98, C2, "TANGENT.EXTERNAL_POINT.VERTICAL", "원 밖 점 접선(수직선 포함)", "원의 접선의 방정식", "중", S, "x=2, 5x−12y=−26", "식", c=M, trap="x=2 누락 주의")
r(99, C1, "CIRCLE.TANGENT_TO_AXES", "두 축에 접하는 두 원 중심 거리", "원의 방정식", "중하", S, "4√2", fig="그림")
r(100, C1, "CIRCLE.BISECT_TWO_CIRCLES", "두 원 넓이 동시 이등분 직선", "원의 방정식;직선의 방정식", "하", S, "y=−2x+3", "식")
r(101, C2, "CIRCLE_LINE.CHORD_PERP_BISECTOR", "현의 수직이등분선(서술형)", "원과 직선의 위치 관계;두 직선의 수직", "중하", D, "y=−x/3+1/3", "식", i=M)
r(102, C2, "CIRCLE_LINE.MAX_MIN_DISTANCE", "원 위의 점과 직선 거리 최대·최소", "원과 직선의 위치 관계;점과 직선 사이의 거리", "중하", S, "최댓값 11, 최솟값 3", "값")
r(103, C2, "CIRCLE.TANGENT_LINE.RADIUS", "직선에 접하는 원", "원과 직선의 위치 관계", "하", S, "(x−3)²+(y−2)²=10", "식")
r(104, C2, "TANGENT.COMMON_TANGENT.FIND_K", "접선이 다른 원에 접할 k(서술형)", "원의 접선의 방정식", "중", D, "k=45", c=M)
r(105, C2, "TANGENT.EXTERNAL_POINT.SLOPE_SUM", "두 접선 기울기의 합", "원의 접선의 방정식;근과 계수의 관계", "중", S, "−5/4", c=M, i=M)
r(106, C2, "CIRCLE.BETWEEN_PARALLEL_LINES", "평행 두 직선에 접하고 원점 지나는 원", "원과 직선의 위치 관계", "중", S, "(x+11/5)²+(y+2/5)²=5, (x+1)²+(y−2)²=5", "식", c=M, d=M)
r(107, C2, "CIRCLE.TRIANGLE_MAX_AREA", "원 위 점 C로 삼각형 넓이 최대", "원과 직선의 위치 관계;점과 직선 사이의 거리", "중상", S, "10+5√5", c=M, i=H, fig="그림")
r(108, C2, "TANGENT.POINT_ON_CIRCLE.GENERAL_FORM", "일반형 원 위 점 접선이 지나는 점", "원의 접선의 방정식", "중하", S, "−1")
r(109, T1, "SYMMETRY.FIGURE.AXIS_CENTER", "선대칭·점대칭 도형 표시(준비)", "선대칭;점대칭", "하", S, "그림 답(대칭축·대칭의 중심 표시)", "그림", 2, fig="그림", final="그림 답", **FK)
r(110, T1, "TRANSLATION.PARABOLA.PARAMS", "포물선 평행이동 a, b, c(준비)", "평행이동", "하", S, "a=3, b=2, c=−1")
r(111, T1, "TRANSLATION.POINT", "점의 평행이동", "점의 평행이동", "하", S, "(1) (−4, 7) (2) (0, −1)", "좌표(소문항별)", 2)
r(112, T1, "TRANSLATION.CIRCLE", "원의 평행이동(예제)", "도형의 평행이동", "하", S, "(x−4)²+(y+1)²=1", "식")
r(113, T1, "TRANSLATION.LINE_CIRCLE", "직선·원 평행이동", "도형의 평행이동", "하", S, "(1) 2x+5y−14=0 (2) (x+3)²+(y−9)²=5", "식(소문항별)", 2)
r(114, T1, "TRANSLATION.CIRCLE.TO_ORIGIN", "중심이 원점 되게 하는 a, b", "도형의 평행이동", "하", S, "a=−1, b=2")
r(115, T1, "TRANSLATION.LINE.INVARIANT", "직선이 자기 자신과 일치하는 평행이동(탐구)", "도형의 평행이동", "중하", ACT, "(1) −4 (2) 2b+c=0", "값+식", 2, i=M)
r(116, T2, "REFLECTION.POINT.FOUR_WAYS", "점의 대칭이동", "점의 대칭이동", "하", S, "(1) (−3,−4) (2) (3,4) (3) (3,−4) (4) (4,−3)", "좌표(소문항별)", 4)
r(117, T2, "REFLECTION.POINT.ITERATE_PERIOD", "대칭이동 반복 P₄₀", "점의 대칭이동", "중", S, "(−5, 7)", "좌표", i=M, trap="주기 8")
r(118, T2, "REFLECTION.LINE_CIRCLE.FOUR_WAYS", "직선·원의 대칭이동", "도형의 대칭이동", "하", S, "(1) 2x+3y+7=0, 2x+3y−7=0, 2x−3y−7=0, 3x−2y−7=0 (2) (x+6)²+(y+3)²=4, (x−6)²+(y−3)²=4, (x−6)²+(y+3)²=4, (x−3)²+(y+6)²=4", "식(소문항별)", 8)
r(119, T2, "REFLECTION.LINE.COMPOSED", "x축→y=x 대칭이동 직선", "도형의 대칭이동", "하", S, "4x+y−2=0", "식")
r(120, T2, "REFLECTION.SHORTEST_PATH.X_AXIS", "x축 위 점 경유 최단 거리(활동)", "대칭이동;두 점 사이의 거리", "중하", ACT, "5√2", fig="그림")
r(121, T2, "REFLECTION.SHORTEST_PATH.RIVER", "강가 선착장 최단 거리(활동)", "대칭이동;두 점 사이의 거리", "중하", ACT, "5√13 km", fig="그림")
r(122, T2, "REFLECTION.BILLIARD.TWO_CUSHIONS", "당구공 두 번 반사 거리(활동)", "대칭이동;두 점 사이의 거리", "중", ACT, "3.9 m", fig="그림", c=M, i=M, chk="독립풀이 일치(B 원점·BC를 x축 배치 가정, 두 번 대칭 후 거리 √15.21=3.9)")
r(123, T1, "TRANSLATION.POINT.FIND_PARAMS", "점 평행이동 a, b", "점의 평행이동", "하", S, "a=−5, b=−5")
r(124, T1, "TRANSLATION.LINE_CIRCLE", "직선·원 평행이동", "도형의 평행이동", "하", S, "(1) 3x−4y−12=0 (2) (x+1)²+(y+2)²=6", "식(소문항별)", 2)
r(125, T2, "REFLECTION.POINT.FOUR_WAYS", "점의 대칭이동", "점의 대칭이동", "하", S, "(1) (2,7) (2) (−2,−7) (3) (−2,7) (4) (−7,2)", "좌표(소문항별)", 4)
r(126, T2, "REFLECTION.LINE.FOUR_WAYS", "직선의 대칭이동", "도형의 대칭이동", "하", S, "(1) y=−4x+9 (2) y=−4x−9 (3) y=4x+9 (4) y=x/4+9/4", "식(소문항별)", 4)
r(127, T2, "REFLECTION.CIRCLE.FOUR_WAYS", "원의 대칭이동", "도형의 대칭이동", "하", S, "(1) (x+3)²+y²=1 (2) (x−3)²+y²=1 (3) (x−3)²+y²=1 (4) x²+(y+3)²=1", "식(소문항별)", 4)
r(128, T1, "TRANSLATION.LINE.FIND_SHIFT_THEN_POINT", "직선 일치 조건 후 점 이동", "도형의 평행이동", "하", S, "(2, 4)", "좌표")
r(129, T1, "TRANSLATION.CIRCLE.FIND_PARAMS", "원 평행이동 a, b, c", "도형의 평행이동", "하", S, "a=2, b=−3, c=8")
r(130, T1, "TRANSLATION.CIRCLE.CONGRUENT_CHOICES", "평행이동으로 겹쳐지는 원 고르기", "도형의 평행이동", "하", S, "ㄴ, ㄷ", "보기", **CK)
r(131, T2, "REFLECTION.POINT.TRIANGLE_AREA", "대칭점 삼각형 넓이", "점의 대칭이동", "하", S, "24")
r(132, T2, "REFLECTION.LINE.COMPOSED_FIND_PARAM", "대칭 후 점 지날 a(서술형)", "도형의 대칭이동", "중하", D, "a=1")
r(133, T2, "REFLECTION.LINE.THEN_PERPENDICULAR", "대칭 직선에 수직인 직선", "도형의 대칭이동;두 직선의 수직", "하", S, "y=2x+2", "식")
r(134, T2, "REFLECTION_TRANSLATION.CIRCLE.MATCH", "대칭이동=평행이동 일치 a, b", "도형의 대칭이동;도형의 평행이동", "하", S, "a=−4, b=4")
r(135, T1, "TRANSLATION.CIRCLE.TANGENT_LINE", "평행이동한 원이 직선에 접할 양수 a(서술형)", "도형의 평행이동;원과 직선의 위치 관계", "중하", D, "17/2")
r(136, T2, "REFLECTION.TRIANGLE_AREA.FIND_POINT", "대칭점 삼각형 넓이 5인 A", "점의 대칭이동;점과 직선 사이의 거리", "중", S, "(2, 3)", "좌표", i=M)
r(137, T2, "REFLECTION.MIN_PERIMETER.TWO_LINES", "삼각형 둘레 최솟값(두 번 대칭)", "대칭이동;두 점 사이의 거리", "중", S, "2√10", fig="그림", i=M)
r(138, P1, "DISTANCE.FIND_PARAM.PRODUCT", "거리 조건 a의 값의 곱", "두 점 사이의 거리;근과 계수의 관계", "하", S, "−27")
r(139, P2, "SECTION.INTERNAL_EXTERNAL.DISTANCE", "내분점·외분점 사이 거리", "선분의 내분점;선분의 외분점", "하", S, "5√13")
r(140, P2, "SECTION.CENTROID.MIDPOINT_TRIANGLE", "중점 삼각형 무게중심", "삼각형의 무게중심", "하", S, "(1, 3)", "좌표", trap="원래 삼각형 무게중심과 같음")
r(141, L1, "LINE.POINT_ON_LINE.PARAM", "직선 위 점 (a, a+3)", "직선의 방정식", "하", S, "5")
r(142, L2, "LINE.PARALLEL_PERP.FIND_PARAMS", "수직·평행 조건 a+b", "두 직선의 평행과 수직", "하", S, "−1")
r(143, L1, "LINE.TRIANGLE_AREA.THREE_LINES", "세 직선으로 둘러싸인 넓이", "직선의 방정식", "중하", S, "33/10", fig="그림")
r(144, C1, "CIRCLE.X_AXIS_CHORD", "원이 x축과 만나는 두 점 거리", "원의 방정식", "하", S, "4")
r(145, C1, "CIRCLE.TWO_CIRCLES.MIN_DISTANCE", "두 원 위 점 거리 최솟값", "원의 방정식;두 점 사이의 거리", "중하", S, "2")
r(146, C2, "CIRCLE_LINE.INTERSECT.RANGE", "원과 직선 만날 k 범위", "원과 직선의 위치 관계", "중하", S, "k≤−2 또는 k≥1/2", "부등식", c=M)
r(147, C2, "TANGENT.EXTERNAL_POINT.AREA", "두 접선과 y축 사이 넓이", "원의 접선의 방정식", "중", S, "25/2", c=M)
r(148, T1, "TRANSLATION.LINE.THROUGH_ORIGIN", "평행이동 직선 원점 통과 k", "도형의 평행이동", "하", S, "−11")
r(149, T2, "REFLECTION.LINE.BISECT_CIRCLE", "대칭 직선이 원 이등분할 a", "도형의 대칭이동;원의 방정식", "하", S, "1")
r(150, T2, "REFLECTION_TRANSLATION.CIRCLE_SYMMETRIC_Y_EQ_X", "y=x 대칭인 원의 a", "도형의 대칭이동;도형의 평행이동", "중하", S, "−4")
r(151, T2, "REFLECTION.MIN_PATH.RECTANGLE_TWO_SIDES", "직사각형 꺾인 경로 최솟값", "대칭이동;두 점 사이의 거리", "중상", S, "√113", fig="그림", c=M, i=H, chk="독립풀이 일치(B 원점 좌표 설정, P·Q 대칭 후 거리)")
r(152, P1, "DISTANCE.SUM_SQUARES.MIN", "AP²+BP² 최솟값(서술형)", "두 점 사이의 거리;이차함수 최솟값", "하", D, "49")
r(153, L2, "LINE.PERPENDICULAR.X_INTERCEPT", "수직 직선의 x절편(서술형)", "두 직선의 수직", "하", D, "2")
r(154, C2, "TANGENT.PERPENDICULAR_PAIR", "두 접선이 수직일 a(서술형)", "원의 접선의 방정식", "중", D, "2√2", i=M)
r(155, T2, "REFLECTION.MIN_PATH.Y_AXIS_POINT", "AC+BC 최소 점 C(서술형)", "대칭이동;직선의 방정식", "중하", D, "(0, 7/4)", "좌표")
r(156, T2, "TRANSFORMATION.CHARACTER_DRAW", "도형의 이동으로 캐릭터 그리기(활동)", "도형의 이동", "하", ACT, "해설참조(그림)", "그림", final="해설참조", fig="그림", review="REVIEW-개방형")
r(157, T2, "TRANSFORMATION.CHARACTER_CREATE", "새 캐릭터 만들기(활동)", "도형의 이동", "하", ACT, "해설참조(개방형)", "그림", final="해설참조", fig="그림", review="REVIEW-개방형")
for i in range(16): build(f"Batch{477+i}", ROWS[i*10:(i+1)*10], 13187+i*10)
print(len(ROWS))
