from cfgy import *
SQ = hashlib.sha256(open(OUT+'h85/Q.hwp','rb').read()).hexdigest()
IT = json.load(open(OUT+'y85.json'))
setup(QID="A02485", SRC="1iSuWlZthUTTz26NE-jNKOHg7iBUvY2Zv", SHA=SQ, TAG="YMCAL01", N=107, SUBJ="미적분", SEC="C01",
      FNAME="1. 수열의 극한 107제(미래엔-용문아).hwp", UNIT="Ⅰ. 수열의 극한", BIG="Ⅰ. 수열의 극한", EXAM="Ⅰ 수열의 극한 107제", MID="수열의 극한")
L, M, H = "낮음", "보통", "높음"
S, MC, D = "서술형(단답)", "5지선다", "서술형"
A, B, C, G1, G2, G3 = "수열의 극한", "수열의 극한값의 계산", "등비수열의 극한", "급수", "등비급수", "등비급수의 활용"
def r(q, small, tid, tname, tags, diff, fmt, ans, atype="값", nsub=1, fig="없음", final=None, combo="단일개념", c=L, d=L, i=L, trap="", why="", chk="독립풀이 일치"):
    R(q, IT[q-1], small, tid, tname, tags, combo, diff, why or tname + ".", fmt, ans, atype, c, d, i, trap, chk, nsub=nsub, fig=fig, final=final)
r(1, A, "LIMSEQ.GENERAL_TERM.GUESS", "수열의 일반항 추측(준비)", "수열;일반항", "하", S, "(1) aₙ=1/n² (2) aₙ=2n−1", "식(소문항별)", 2)
r(2, A, "LIMSEQ.CONVERGE.GRAPH_INTUITION", "1/n의 그래프와 극한 직관(생각 열기)", "수열의 수렴;그래프", "하", "서술형(활동)", "0에 한없이 가까워진다", "서술", fig="좌표평면 활동")
r(3, A, "LIMSEQ.CONVERGE.SHIFTED_INDEX", "lim aₙ=α이면 lim aₙ₊₁=α", "수열의 극한", "하", S, "α", "식")
r(4, A, "LIMSEQ.CONVERGE.GRAPH_LIMIT", "그래프로 수열의 극한값", "수열의 수렴;그래프", "하", S, "1", fig="그래프")
r(5, A, "LIMSEQ.CONVERGE.GRAPH_LIMIT", "그래프로 수열의 극한값", "수열의 수렴;그래프", "하", S, "(1) 2 (2) 1", "값(소문항별)", 2, fig="그래프")
r(6, A, "LIMSEQ.DIVERGE.GRAPH_INTUITION", "n−1의 그래프와 발산 직관(생각 열기)", "수열의 발산;그래프", "하", "서술형(활동)", "한없이 커진다", "서술", fig="좌표평면 활동")
r(7, A, "LIMSEQ.DIVERGE.GRAPH_CHECK", "그래프로 발산 확인", "수열의 발산;그래프", "하", "서술형(확인)", "(1) {10−3n} 음의 무한대로 발산 (2) {n²−3} 양의 무한대로 발산", "서술(소문항별)", 2, fig="그래프", final="(1) −∞로 발산 (2) +∞로 발산")
r(8, A, "LIMSEQ.CONVERGE_DIVERGE.GRAPH_CLASSIFY", "그래프로 수렴·발산 조사", "수열의 수렴;발산;진동", "하", S, "(1) 수렴 0 (2) 발산 (3) 발산(진동) (4) 발산(+∞)", "서술(소문항별)", 4, fig="그래프", final="(1) 0 (2) 발산 (3) 진동 (4) +∞")
r(9, A, "LIMSEQ.SUBSEQUENCE.EVEN_ODD_CONVERGENCE", "홀수·짝수항 부분수열 수렴과 전체 수렴(생각 넓히기)", "수열의 극한;부분수열", "중", "서술형(탐구)", "aₙ이 α에 수렴하면 두 부분수열도 α에 수렴; 역은 거짓(1,0,1,0,… 반례)", "서술", i=M)
r(10, B, "LIMFN.AT_INFINITY.RATIONAL_IRRATIONAL", "함수의 극한값(준비)", "함수의 극한;유리화", "하", S, "(1) 2/5 (2) 1/2", "값(소문항별)", 2)
r(11, B, "LIMSEQ.PROPERTIES.SUM_INTUITION", "극한의 합 성질 직관(생각 열기)", "수열의 극한의 성질", "하", "서술형(활동)", "lim aₙ=2, lim bₙ=3, lim(aₙ+bₙ)=5로 같다", "서술")
r(12, B, "LIMSEQ.PROPERTIES.BASIC_COMPUTE", "극한의 성질로 계산", "수열의 극한의 성질", "하", S, "(1) −2 (2) 3 (3) −5/2", "값(소문항별)", 3)
r(13, B, "LIMSEQ.PROPERTIES.COMBINATION_GIVEN_LIMITS", "주어진 극한값으로 식의 극한", "수열의 극한의 성질", "하", S, "(1) 0 (2) −18 (3) 5", "값(소문항별)", 3)
r(14, B, "LIMSEQ.RATIONAL.DIVIDE_HIGHEST_AND_RATIONALIZE", "최고차항 나누기·유리화(예제)", "∞/∞ 꼴;∞−∞ 꼴;유리화", "하", S, "(1) 3 (2) 1/2", "값(소문항별)", 2)
r(15, B, "LIMSEQ.RATIONAL.DIVIDE_HIGHEST_AND_RATIONALIZE", "최고차항 나누기·유리화", "∞/∞ 꼴;∞−∞ 꼴;유리화", "하", S, "(1) −2 (2) 0 (3) −3/2 (4) 1", "값(소문항별)", 4, d=M)
r(16, B, "LIMSEQ.DIVERGE.POLY_RATIONAL", "다항·유리식 수열의 발산 판정(예제)", "수열의 발산", "하", S, "(1) 양의 무한대로 발산 (2) 음의 무한대로 발산", "서술(소문항별)", 2)
r(17, B, "LIMSEQ.DIVERGE.POLY_RATIONAL", "다항·유리식 수열의 발산 판정", "수열의 발산", "하", S, "(1) 양의 무한대로 발산 (2) 음의 무한대로 발산", "서술(소문항별)", 2)
r(18, B, "LIMSEQ.PROPERTIES.TRUTH_COUNTEREXAMPLE", "극한 성질 명제 참거짓·반례", "수열의 극한의 성질;반례", "중", "서술형(판정)", "(1) 거짓 aₙ=n, bₙ=−n (2) 참 (3) 거짓 aₙ=1/n, bₙ=n", "서술(소문항별)", 3, d=M, i=M, trap="반례 구성")
r(19, B, "LIMSEQ.SQUEEZE.TRIG_OVER_N", "sin nθ/n 조임정리(예제)", "수열의 극한의 대소 관계", "하", S, "0", d=M)
r(20, B, "LIMSEQ.SQUEEZE.TRIG_OVER_N", "삼각함수 포함 수열 조임정리", "수열의 극한의 대소 관계", "하", S, "(1) 0 (2) 0", "값(소문항별)", 2, d=M)
r(21, B, "LIMSEQ.SQUEEZE.INEQUALITY_BOUNDS", "부등식 조건 조임정리", "수열의 극한의 대소 관계", "중하", S, "5", d=M)
r(22, B, "LIMSEQ.RECURSIVE.TECH_TOOL_LIMIT", "점화식 수열 극한(공학적 도구)", "점화식;수열의 극한;공학도구", "중하", "서술형(활동)", "(1) 4 (2) 6", "값(소문항별)", 2, fig="프로그램 화면", final="(1) 4 (2) 6 (고정점 L=√(2L+8)→4, L=2√(3+L)→6)")
r(23, C, "LIMSEQ.GEOMETRIC.GENERAL_TERM", "등비수열 일반항(준비)", "등비수열", "하", S, "(1) aₙ=2ⁿ (2) aₙ=(−1/2)ⁿ⁻¹", "식(소문항별)", 2)
r(24, C, "LIMSEQ.GEOMETRIC.PAPER_CUTTING_INTUITION", "종이 자르기 등비수열 극한(생각 열기)", "등비수열의 극한", "하", "서술형(활동)", "aₙ=2ⁿ 한없이 커짐, bₙ=(1/2)ⁿ → 0", "서술", fig="그림·표")
r(25, C, "LIMSEQ.GEOMETRIC.RATIO_CONVERGENCE", "공비로 등비수열 수렴·발산", "등비수열의 수렴 조건", "하", S, "(1) 수렴 0 (2) 발산 (3) 발산 (4) 수렴 0", "서술(소문항별)", 4)
r(26, C, "LIMSEQ.GEOMETRIC.COS_NPI", "cos nπ 포함 등비수열", "등비수열의 수렴 조건", "하", S, "수렴, 0", "서술")
r(27, C, "LIMSEQ.GEOMETRIC.EXPONENTIAL_RATIO_LIMIT", "지수꼴 분수 수열 극한(예제)", "등비수열의 극한;최대 밑으로 나누기", "하", S, "수렴, 5", "서술")
r(28, C, "LIMSEQ.GEOMETRIC.EXPONENTIAL_RATIO_LIMIT", "지수꼴 분수 수열 극한", "등비수열의 극한;최대 밑으로 나누기", "중하", S, "(1) 발산 (2) 수렴 −6 (3) 수렴 0 (4) 발산", "서술(소문항별)", 4, d=M)
r(29, C, "LIMSEQ.GEOMETRIC.PARAM_R_CASES", "r 범위별 수렴값(예제)", "등비수열의 극한;경우 분류", "중하", S, "0<r<1: 1, r=1: 0, r>1: −1", "서술", d=M, i=M)
r(30, C, "LIMSEQ.GEOMETRIC.PARAM_R_CASES", "r 범위별 수렴·발산", "등비수열의 극한;경우 분류", "중", S, "(1) |r|>1: r, r=1: 1/2, |r|<1: 0 (2) |r|>1: 0, r=1: 1, |r|<1: r, r=−1: 발산", "서술(소문항별)", 2, d=M, i=M, trap="r=−1")
r(31, C, "LIMSEQ.GEOMETRIC.DOMINANT_BASE_CHOICE", "큰 밑 지배 조건 선택(생각 넓히기)", "등비수열의 극한", "중하", "서술형(탐구)", "선영: a>b, 경수: a<b", "서술", i=M)
r(32, A, "LIMSEQ.CONVERGE_DIVERGE.LIST_CLASSIFY", "나열된 수열 수렴·발산", "수열의 수렴;발산", "하", S, "(1) 발산 (2) 수렴 0 (3) 발산 (4) 수렴 0", "서술(소문항별)", 4)
r(33, B, "LIMSEQ.RATIONAL.DIVIDE_HIGHEST_AND_RATIONALIZE", "∞/∞·∞−∞ 꼴 극한", "유리화", "하", S, "(1) 1/2 (2) −2 (3) 2/3", "값(소문항별)", 3)
r(34, B, "LIMSEQ.SQUEEZE.INEQUALITY_BOUNDS", "부등식 조건 조임정리", "수열의 극한의 대소 관계", "하", S, "2")
r(35, C, "LIMSEQ.GEOMETRIC.RATIO_CONVERGENCE", "공비로 등비수열 수렴·발산", "등비수열의 수렴 조건", "하", S, "(1) 발산 (2) 수렴 0 (3) 발산 (4) 수렴 0", "서술(소문항별)", 4)
r(36, B, "LIMSEQ.SUM_FORMULA.RATIO_OF_SUMS", "합 공식 이용 극한", "자연수의 합;수열의 극한", "중하", S, "3", d=M)
r(37, B, "LIMSEQ.RATIONAL.COEFF_FROM_LIMIT", "극한값 조건으로 계수 결정", "∞/∞ 꼴;미정계수", "중하", S, "a=0, b=4", d=M)
r(38, B, "LIMSEQ.PROPERTIES.SOLVE_FOR_LIMIT", "극한식에서 lim aₙ 구하기", "수열의 극한의 성질", "중하", S, "(1) 3 (2) 8", "값(소문항별)", 2, d=M)
r(39, B, "LIMSEQ.SQUEEZE.INEQUALITY_BOUNDS", "부등식 조건 조임정리(서술)", "수열의 극한의 대소 관계", "중하", D, "1/3", d=M)
r(40, C, "LIMSEQ.GEOMETRIC.CONVERGENCE_RANGE_X", "등비수열 수렴 조건 x 범위", "등비수열의 수렴 조건;로그", "중", S, "(1) −1<x≤1/3 (2) 1<x≤100", "범위(소문항별)", 2, d=M, trap="r=1 포함")
r(41, C, "LIMSEQ.GEOMETRIC.PARAM_R_CASES", "r 범위별 수렴값", "등비수열의 극한;경우 분류", "중", S, "|r|>1: 1/r, |r|<1: r, r=1: 1", "서술", d=M, i=M, final="(1) |r|>1이면 1/r (2) |r|<1이면 r (3) r=1이면 1")
r(42, A, "LIMSEQ.SUBSEQUENCE.TRIG_EVEN_ODD", "sin(nπ/2) 홀짝 부분수열", "부분수열;삼각함수", "중하", S, "a₂ₙ₋₁: 1, −1 반복으로 발산(진동), a₂ₙ: 0에 수렴", "서술", d=M, final="{a₂ₙ₋₁} 발산(진동), {a₂ₙ} 수렴 0")
r(43, B, "LIMSEQ.SQUEEZE.TELESCOPING_SQRT", "유리화 망원합 + 조임정리", "유리화;망원합;대소 관계", "중", S, "1", d=M, i=M)
r(44, C, "LIMSEQ.GEOMETRIC.EXPONENTIAL_GAP_RATIO", "지수함수 그래프 사이 길이 비 극한", "지수함수;등비수열의 극한", "중", D, "4", fig="그래프", final="4", d=M)
r(45, G1, "SERIES.PARTIAL_SUM.TELESCOPING_PREP", "부분합(준비)", "부분분수;망원합", "하", S, "(1) n/(n+1) (2) √(n+1)−1", "식(소문항별)", 2)
r(46, G1, "SERIES.INTUITION.HALVING_AREAS", "넓이 이등분 급수 직관(생각 열기)", "급수", "하", "서술형(활동)", "1", fig="그림")
r(47, G1, "SERIES.TELESCOPING.CONVERGE_DIVERGE", "망원합 급수 수렴·발산(예제)", "급수;부분분수;유리화", "하", S, "(1) 수렴 1 (2) 발산", "서술(소문항별)", 2)
r(48, G1, "SERIES.TELESCOPING.CONVERGE_DIVERGE", "망원합 급수 수렴·발산", "급수;부분분수;유리화;로그", "중하", S, "(1) 수렴 −1/2 (2) 수렴 1/2 (3) 발산 (4) 발산", "서술(소문항별)", 4, d=M)
r(49, G1, "SERIES.NTH_TERM.LIMIT_ZERO_PROOF", "수렴 급수 일반항 극한 0(함께하기)", "급수의 성질", "하", "서술형(활동)", "0", "값")
r(50, G1, "SERIES.NTH_TERM.DIVERGENCE_TEST", "일반항 극한≠0으로 발산 보이기", "급수의 발산 판정", "중하", "서술형(증명)", "(1) 일반항 → 1≠0 이므로 발산 (2) 일반항 → 1/3≠0 이므로 발산", "서술(소문항별)", 2, d=M, final="(1)(2) 일반항 극한이 0이 아니므로 발산")
r(51, G1, "SERIES.PROPERTIES.PRODUCT_NOT_DISTRIBUTIVE", "급수 곱 분배 불성립(생각 톡톡)", "급수의 성질", "하", "서술형(판단)", "성립하지 않는다", "서술", i=M)
r(52, G1, "SERIES.PROPERTIES.LINEAR_COMBINATION", "급수의 선형성", "급수의 성질", "하", S, "(1) 4 (2) 33", "값(소문항별)", 2)
r(53, G2, "SERIES.GEOMETRIC.PARTIAL_SUM_PREP", "등비수열 합·극한(준비)", "등비수열의 합;등비수열의 극한", "하", S, "(1) 2−(1/2)ⁿ⁻¹ (2) −1", "값(소문항별)", 2)
r(54, G2, "SERIES.GEOMETRIC.SIERPINSKI_INTUITION", "정삼각형 반복 색칠 넓이(생각 열기)", "등비급수", "하", "서술형(활동)", "공비 1/4 등비수열, 넓이 합 4/3", "서술", fig="그림", final="aₙ=(1/4)ⁿ⁻¹, 합 4/3")
r(55, G2, "SERIES.GEOMETRIC.CONVERGE_SUM", "등비급수 수렴·합(예제)", "등비급수의 수렴 조건", "하", S, "(1) 수렴 1/4 (2) 발산", "서술(소문항별)", 2)
r(56, G2, "SERIES.GEOMETRIC.CONVERGE_SUM", "등비급수 수렴·합", "등비급수의 수렴 조건;삼각함수", "중하", S, "(1) 수렴 2/3 (2) 발산 (3) 수렴 3/10 (4) 발산", "서술(소문항별)", 4, d=M, trap="sin(nπ/2) 부호 패턴")
r(57, G2, "SERIES.GEOMETRIC.SPLIT_SUM", "분리하여 두 등비급수 합(예제)", "등비급수의 합", "하", S, "3/2")
r(58, G2, "SERIES.GEOMETRIC.SPLIT_SUM", "분리하여 두 등비급수 합", "등비급수의 합", "하", S, "(1) 8/3 (2) −1/2", "값(소문항별)", 2)
r(59, G2, "SERIES.GEOMETRIC.CONVERGENCE_RANGE_AND_VALUE", "등비급수 수렴 범위와 합 조건(생각 넓히기)", "등비급수의 수렴 조건", "중하", "서술형(탐구)", "0<x<4, x=3", "범위·값", d=M)
r(60, G3, "SERIES.GEOMETRIC.SUM_PREP", "등비급수 합(준비)", "등비급수의 합", "하", S, "(1) 3/4 (2) 2/3", "값(소문항별)", 2)
r(61, G3, "SERIES.REPEATING_DECIMAL.SERIES_FORM", "순환소수 등비급수 표현(생각 열기)", "순환소수;등비급수", "하", "서술형(활동)", "0.1̇3̇=13/100+13/100²+…, 첫째항 13/100, 공비 1/100", "서술")
r(62, G3, "SERIES.REPEATING_DECIMAL.TO_FRACTION", "순환소수를 분수로(예제)", "순환소수;등비급수", "하", S, "(1) 13/99 (2) 5/18", "값(소문항별)", 2)
r(63, G3, "SERIES.REPEATING_DECIMAL.TO_FRACTION", "순환소수를 분수로", "순환소수;등비급수", "하", S, "(1) 328/999 (2) 401/198", "값(소문항별)", 2)
r(64, G3, "SERIES.GEOMETRIC.SQUARES_IN_TRIANGLE", "직각이등변삼각형 반복 정사각형 넓이 합", "등비급수의 활용;닮음", "중하", S, "1/3", fig="그림", d=M)
r(65, G3, "SERIES.GEOMETRIC.NESTED_CIRCLE_TRIANGLE", "원·정삼각형 반복 내접 둘레 합", "등비급수의 활용;닮음", "중하", S, "16π", fig="그림", d=M)
r(66, G3, "SERIES.GEOMETRIC.APPLIED_RECYCLING", "재생산 총량(실생활)", "등비급수의 활용;실생활", "하", S, "1.5톤", combo="급수+실생활")
r(67, G3, "SERIES.GEOMETRIC.APPLIED_FUND", "장학 기금 총액(실생활)", "등비급수의 활용;실생활", "중하", S, "40억 원", combo="급수+실생활", d=M)
r(68, G3, "SERIES.GEOMETRIC.APPLIED_DOUBLE_GLASS", "이중 유리 투과광(생각 넓히기)", "등비급수의 활용", "중", "서술형(탐구)", "a/4, a/16, a/3", "값", fig="그림", d=M)
r(69, G3, "SERIES.GEOMETRIC.KOCH_SNOWFLAKE", "코흐 눈송이 넓이 유한·둘레 무한", "등비급수의 활용;등비수열의 발산", "중", "서술형(탐구)", "넓이 8/5 A(유한), 둘레 (4/3)ⁿ⁻¹·l → ∞", "서술", fig="그림", final="넓이 (8/5)A 유한, 둘레 무한", d=M, i=M)
r(70, G1, "SERIES.CONVERGE_DIVERGE.ARITH_GEOM", "등차·등비 급수 수렴·발산", "급수;등비급수", "하", S, "(1) 발산 (2) 수렴 4", "서술(소문항별)", 2)
r(71, G1, "SERIES.TELESCOPING.CONVERGE_DIVERGE", "망원합 급수", "부분분수;유리화", "하", S, "(1) 수렴 1/2 (2) 발산", "서술(소문항별)", 2)
r(72, G2, "SERIES.GEOMETRIC.CONVERGE_SUM", "등비급수 수렴·합", "등비급수의 수렴 조건", "하", S, "(1) 발산 (2) 수렴 8/9", "서술(소문항별)", 2)
r(73, G2, "SERIES.GEOMETRIC.SPLIT_SUM", "분리하여 등비급수 합", "등비급수의 합", "하", S, "(1) 8/5 (2) 2", "값(소문항별)", 2)
r(74, G1, "SERIES.PARTIAL_SUM.LIMIT_OF_SN", "부분합 Sₙ의 극한", "급수와 부분합", "하", S, "1/2")
r(75, G1, "SERIES.TELESCOPING.PARTIAL_FRACTION_3N", "부분분수 망원합(3n 간격)", "부분분수;망원합", "하", S, "1/6")
r(76, G1, "SERIES.PARTIAL_SUM.LIMIT_EXPRESSION", "Sₙ·aₙ 극한 결합(서술)", "급수와 부분합;일반항 극한 0", "중하", D, "11/2", d=M)
r(77, G2, "SERIES.GEOMETRIC.SUM_OF_GEOM_PARTIALS", "등비수열 합을 일반항으로 하는 급수", "등비수열의 합;등비급수", "중하", S, "5/8", d=M)
r(78, G2, "SERIES.GEOMETRIC.FIND_RATIO_FROM_SUMS", "연속 세 항 합으로 공비 결정 후 급수", "등비수열;등비급수", "중하", S, "16", d=M)
r(79, G3, "SERIES.REPEATING_DECIMAL.DIGIT_SERIES", "순환소수 자릿수 급수", "순환소수;등비급수", "중", S, "27/35", d=M, i=M)
r(80, G3, "SERIES.GEOMETRIC.NESTED_CIRCLES_AREA", "반복 내접원 넓이 합", "등비급수의 활용", "중하", S, "16π/3", fig="그림")
r(81, G1, "SERIES.TELESCOPING.LATTICE_POINTS", "직선 위 격자점 급수", "부분분수;망원합;격자점", "중", S, "1/3", d=M, i=M)
r(82, G2, "SERIES.GEOMETRIC.SQUARE_TERMS_SUM", "짝수항 급수로 공비 결정 후 제곱 급수", "등비급수", "중", S, "12", d=M, i=M)
r(83, G3, "SERIES.GEOMETRIC.NESTED_SQUARES_DIAGONAL", "대각선 정사각형 반복 넓이 합(서술)", "등비급수의 활용", "중하", D, "32", fig="그림")
r(84, A, "LIMSEQ.CONVERGE_DIVERGE.SELECT", "수렴하는 수열 고르기", "수열의 수렴;발산", "하", MC, "④", "선택지번호", final="④ ((−1)ⁿ/n)")
r(85, B, "LIMSEQ.PROPERTIES.COMBINATION_GIVEN_LIMITS", "극한의 성질 식 계산", "수열의 극한의 성질", "하", S, "4")
r(86, B, "LIMSEQ.SUM_FORMULA.RATIO_OF_SUMS", "제곱합 공식 극한", "자연수 거듭제곱 합;수열의 극한", "하", MC, "③", "선택지번호", final="③ (3)")
r(87, B, "LIMSEQ.PROPERTIES.RATIO_TRANSFER", "주어진 극한식으로 다른 극한", "수열의 극한의 성질", "하", S, "8")
r(88, B, "LIMSEQ.PROPERTIES.TRUTH_SELECT", "극한 성질 보기 판정", "수열의 극한의 성질;대소 관계", "중", MC, "①", "선택지번호", final="① (ㄱ)", d=M, i=M)
r(89, B, "LIMSEQ.SQUEEZE.INEQUALITY_BOUNDS", "부등식 조건 조임정리", "수열의 극한의 대소 관계", "하", S, "1")
r(90, B, "LIMSEQ.PARTIAL_SUM.SN_OVER_AN", "Sₙ에서 aₙ 구해 극한", "수열의 합과 일반항;극한", "중하", MC, "②", "선택지번호", final="② (2)", d=M)
r(91, B, "LIMSEQ.RATIONAL.DISTANCE_ON_PARABOLA", "포물선 위 두 점 거리 극한", "두 점 사이 거리;수열의 극한", "중하", S, "6", d=M)
r(92, B, "LIMSEQ.PROPERTIES.DIFFERENCE_BOUNDED", "차가 수렴하는 두 발산 수열 비 극한", "수열의 극한의 성질", "중", S, "2/3", d=M, i=M)
r(93, C, "LIMSEQ.GEOMETRIC.EXPONENTIAL_RATIO_LIMIT", "지수꼴 분수 극한", "등비수열의 극한", "중하", MC, "④", "선택지번호", final="④ (3/2)")
r(94, C, "LIMSEQ.GEOMETRIC.FUNCTION_DEFINED_BY_LIMIT", "극한으로 정의된 함수값", "등비수열의 극한;경우 분류", "중", S, "1/4", d=M, i=M)
r(95, C, "LIMSEQ.GEOMETRIC.CONVERGENCE_RANGE_X", "등비수열 수렴 정수 x 개수", "등비수열의 수렴 조건;지수", "중하", S, "2", d=M)
r(96, G1, "SERIES.NTH_TERM.LIMIT_ZERO_APPLICATION", "급수 수렴 → 일반항 0 활용", "급수의 성질", "중하", MC, "①", "선택지번호", final="① (−5/3)", d=M)
r(97, G1, "SERIES.PROPERTIES.TRUTH_SELECT", "급수 성질 보기 판정", "급수의 성질;반례", "중상", MC, "①", "선택지번호", final="① (ㄴ)", d=H, i=H, trap="ㄷ 반례")
r(98, B, "LIMSEQ.SQUEEZE.SUM_RIEMANN_LIKE", "합의 조임정리", "수열의 극한의 대소 관계;합", "중", S, "1", d=M, i=M)
r(99, G1, "SERIES.TELESCOPING.REMAINDER_THEOREM_TERM", "나머지정리로 일반항 후 망원합", "나머지정리;부분분수", "중", S, "3", combo="나머지정리+급수", d=M)
r(100, G2, "SERIES.GEOMETRIC.LOG_SERIES", "로그 등비급수", "로그;등비급수", "중하", MC, "②", "선택지번호", final="② (1/2)", d=M)
r(101, G2, "SERIES.GEOMETRIC.ALTERNATING_FROM_CONDITIONS", "조건으로 일반항 결정 후 교대 등비급수", "급수의 성질;등비급수", "중", S, "−1/3", d=M, i=M)
r(102, G2, "SERIES.GEOMETRIC.SEGMENT_LENGTHS_EXPONENTIAL", "지수곡선 사이 선분 길이 급수", "지수함수;등비급수", "중", S, "19", d=M)
r(103, G3, "SERIES.GEOMETRIC.SEMICIRCLE_ARCS_DIVISION", "내분점 반복 반원 호 길이 합", "내분점;등비급수의 활용", "중", S, "8π", fig="그림", d=M)
r(104, C, "LIMSEQ.GEOMETRIC.DOMINANT_BASE_PARAM", "큰 밑으로 나눠 매개변수 결정(서술)", "등비수열의 극한", "중하", D, "b=4", final="b=4", d=M)
r(105, G2, "SERIES.GEOMETRIC.COS_RATIO_EQUATION", "cos x 공비 등비급수 방정식(서술)", "등비급수;삼각함수", "중", D, "x=2π/3", final="x=2π/3", d=M)
r(106, G2, "SERIES.GEOMETRIC.SAME_RATIO_PRODUCT_SERIES", "공비 같은 두 등비수열 곱의 급수", "등비급수", "중", S, "16", d=M, i=M)
r(107, G3, "SERIES.GEOMETRIC.SECTOR_AREAS_TRIANGLE", "직각삼각형 반복 부채꼴 넓이 합(서술)", "등비급수의 활용;삼각비", "상", D, "9π", fig="그림", c=M, d=M, i=H)
for i in range(11): build(f"Batch{336+i}", ROWS[i*10:(i+1)*10], 11835+i*10)
